solgenomics/sgn

- mason/search/stocks.mas
Allows up to 1,000 stock search results to be copied to a list. Closes #1081
> allow longer output in stock search results table

- db/00086/AddTimestampToNdTables.pm
this patch will add a 'create_date' timestamp to the stock, project, phenotype, genotype, and nd_protocol tables. will be useful for creating reports showing projects, stocks, etc that were added over time periods.
> patch to add timestamps to tables

- lib/SGN/Controller/AJAX/Accessions.pm
- mason/tools/available_seedlots.mas
Switched the availible_seedlots AJAX method from GET to POST and move the list of names from the URL to the POST body.
> Fixed long-url error issue with the availible_seedlots table for long lists

- db/00086/AddTimestampToNdTables.pm
Description 
Added timestamp column called 'create_date' to nd_experiment, project, stock, phenotype, genotype, nd_protocol, stock_relationship, and project_relationship tables.
This patch will need to be run on all dbs.
Checklist 
> timestamps on stock_relationship and project_relationship

- mason/search/traits.mas
Description 
Simple fix to make it possible to select multiple items in the list without holding <kbd>CMD</kbd> / <kbd>CTRL</kbd>
Checklist 
> changed trait search select behavior to be more intuitive

- mason/homepage/github_pullrequests.mas
Description 
Fixes PR template showing on the homepage by splitting the response.body string on section headers.
closes #1354 
Checklist 
> Fixed homepage PR preview to remove PR template

- lib/CXGN/Stock/Seedlot.pm
You can edit seedlot info at any point; however, you cannot edit the seedlot contents (accession) once the seedlot has been used in transactions.
closes #1438 
Description 
Checklist 
> fixes seedlot editing issue

- docs/01_basic_website_usage.md
- docs/02_searching_the_database.md
- docs/03_managing_breeding_data/03_06.md
- docs/03_managing_breeding_data/03_08.md
- docs/04_data_analysis_tools.md
Replaces direct references to CassavaBase with "SGN databases" or "the database". Some cassavabase-specific (but also rather intuitive) documentation was also removed. It would be helpful for someone to look over the diff just to make sure I didn't remove anything important (or accidentally mangle a sentence that I didn't notice.)
Description 
#1336
Checklist 
> Replace direct references to CassavaBase in the documentation

- lib/SGN/Controller/AJAX/Pedigrees.pm
- mason/pedigree/stock_pedigree.mas
Description 
Fixes issue where crosses and populations would appear in the pedigree tree.
closes #1062 
Checklist 
> Filter pedigree relationship edges such that the unknown terminal node must be an accession

- lib/CXGN/BrAPI/v1/Germplasm.pm
Array was slicing past end causing null values to be returned when the number of fetched items was less than the page size.
Description 
Checklist 
> Fixes BrAPI Progeny call null values bug

- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
This fixes BrAPI calls to enable JSON-body parsing. Also enables the content-type header in Access-Control-Allow-Headers responses for BrAPI calls.
Checklist 
> Fix BrAPI JSON body data params

- lib/CXGN/Stock/Search.pm
- mason/breeders_toolbox/upload_seedlots_dialogs.mas
Description 
Minor bug in the error response of uploading seedlots. Now if you upload a file of seedlots and the accession names for those seedlots are missing, you can add those missing accessions to a list to ease addition of those accessions.
Checklist 
> fix upload of seedlot with missing accessions

- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
Fixes a bug where pagination/token arguments were ignored when present in a POST body.
Checklist 
> Fixes issue with BrAPI pagination/token arguments in POST body

- bin/merge_stocks.pl
Description 
merge stocks script works well, but it is much safer to do this for exact uniquenames.
also it is necessary to do exact uniquenames in the case of merging two case sensitive stocks (e.g. Mo17 vs Mo17)
Checklist 
> case sensitive exact uniquename

- js/CXGN/BreedersToolbox/Accessions.js
- js/CXGN/BreedersToolbox/AddTrial.js
- js/CXGN/BreedersToolbox/UploadTrial.js
- lib/CXGN/BreedersToolbox/StocksFuzzySearch.pm
- lib/CXGN/Trial/TrialDesignStore.pm
- lib/SGN/Controller/AJAX/Accessions.pm
- mason/breeders_toolbox/add_accessions_dialogs.mas
- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
Description 
Allows option to bypass fuzzy search when adding accessions using list.
Also fixes an issue with how fuzzy search was marking exactly matched synonyms.
related to #1816 
Checklist 
> fuzzy search option

- sgn.conf
Description 
Add Slurm as the default backend in sgn.conf. (the backend property will be Slurm by default, can be over-ruled by sgn_local.conf)
Checklist 
> Make Slurm the default backend by adding it to sgn.conf.

- bin/delete_images.pl
Description 
For wrongly uploaded batches of images, handy script to delete images by image ids. Be very careful!
Checklist 
> Add a script to hard delete images

- lib/SGN/Controller/AJAX/LabelDesigner.pm
Description 
Pedigree label works when custom label applied.
closes #2043 
Checklist 
> pedigree string works with custom pedigree

- lib/CXGN/Trial.pm
- lib/CXGN/Trial/ParseUpload/Plugin/TrialPlantsWithPlantNumberXLS.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/trial/add_plants_per_plot.mas
- mason/breeders_toolbox/trial/design_section.mas
Description 
New option to upload plant entries from the trial detail page using the following formatted xls file:
plot_name | plant_index_number
The database will create plant names by concatenating the plot_name + _ + plant_index_number
closes #2075 
Checklist 
> upload plants using plant index number

- lib/CXGN/BrAPI/v1/Germplasm.pm
Description 
Prevents brapi pedigree from fetching siblings if there are no female and male parents.
@dauglyon will speed up the pedigree search
closes #2052 
Checklist 
> prevent get siblings if no male and female parents

- js/CXGN/BreedersToolbox/AddTrial.js
- lib/SGN/Controller/AJAX/Trial.pm
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
Description 
When designing splitplot design, you can give as many treatments as you need
Checklist 
> Flexible number of treatments in splitplot design

- js/tools/LabelDesigner.js
- lib/SGN/Controller/AJAX/LabelDesigner.pm
- mason/tools/label_designer.mas
Description 
On label designer, it is useful to be able to download only the first 5 or 10 labels for testing. This PR adds a select for printing All, First1, First5, or First10 labels
Checklist 
> on label designer select number of labels to print

- js/CXGN/List.js
- lib/CXGN/List.pm
- lib/SGN/Controller/AJAX/List.pm
- mason/site/list.mas
Description 
Public lists now shows the owner username, and gives option to curators to return public lists to private lists.
closes #1974 
Checklist 
> curator can set public lists back to private

- js/CXGN/BreedersToolbox/GenotypingTrial.js
- js/CXGN/Trial.js
- lib/CXGN/Trial.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
When a genotyping plate is uploaded and it uses field entities as its source observation units (plots/plants/tissue samples), the database automatically creates linkage between the genotyping plate and those field trial(s) (i.e. the trial linkage section). Trial deletion will now check if a field trial / genotyping plate has linkage to genotyping plates / field trials before allowing deletion (on either the web interface or the backend script).
Trial deletion will now always delete the layout and the project entry, preventing #2185 from happening
Description 
closes #2221 
closes #2185
Checklist 
> trial deletion checks

- lib/CXGN/Stock/Seedlot/ParseUpload/Plugin/SeedlotInventoryCSV.pm
- t/data/stock/seedlot_inventory_android_app
Description 
Allows 0 as a value for seedlot inventory upload. Test now covers this use case.
closes #2273
Checklist 
> seedlot inventory upload works for 0

- mason/breeders_toolbox/cross_wishlist.mas
Description 
Changes the cross wishlist creation interface tabs to read: "Using Accession Lists" and "Using Crossing Blocks"
closes #2279 
Checklist 
> change cross wishlist interface tab names

- lib/SGN/Controller/BreedersToolbox.pm
- lib/SGN/Controller/Seedlot.pm
- mason/breeders_toolbox/manage_upload.mas
- mason/breeders_toolbox/upload_crosses_dialogs.mas
Description 
The manage seedlot page crashes because the old format for geolocation data was fed to it, and it expected the new geojson format.
This was fixed for the seedlot page, but similar misalignments may still exist on other pages, and will have to be checked carefully. Stay tuned.
Checklist 
> fix issue with new location geojson format and metadata.

- lib/SGN/Role/Site/Files.pm
--fixes site- specific directory creation problem for in-house sites.
> refine cluster shared dir naming for ip address using site (in-house site)

- lib/SGN/Controller/AJAX/Contact.pm
Description 
Contact form message includes the name of the website that the message originated from. Also includes a helper message reminding people to include the recipient's email and the github.reply email during email replying.
closes #2429 
Checklist 
> contactform body message includes website

- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/download.mas
Description
change 'genotyping_protocols' to 'genotyping_protocol' argument in getSelectBox()
Add 'Genotyping Protocol' Header to 'GBS Genotype QC' section
Fixes #2440 
Checklist 
> Fix Genotype Protocol lists on Download Page

- lib/CXGN/BrAPI/v1/GenomeMaps.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
- lib/SGN/Controller/Cview.pm
Description 
**The Problem:**
On triticumbase and cassavabase, when listing all of the system genetic maps (https://cassavabase.org/cview/ and in the [new Comparative Map Viewer](https://maps.triticeaetoolbox.org/Map/map_list/)) a Tomato Pachytene Chromosomes map is included in the list.
------
The default SGN CView DB backend for the `CXGN::Cview::MapFactory` was always being used, which has some hard-coded maps for demonstration purposes.
This passes a hashref of the local config properties to the `CXGN::Cview::MapFactory` constructor so the `cview_db_backend` property will be used.
Checklist 
> Fix listing of genetic maps

- lib/SGN/Controller/AJAX/Trial.pm
Description 
In the 'Design New Trial' wizard, set the default plot number increment to 1
and display an error if the starting plot number has not been selected
Fixes #2381 
Checklist 
> Set Default Plot Increment

- lib/SGN/Controller/AJAX/Stock.pm
- lib/SGN/Controller/Stock.pm
- mason/page/detail_page_2_col_section.mas
- mason/stock/direct_genotypes.mas
- mason/stock/index.mas
- t/unit_fixture/CXGN/Uploading/VCFGenotypes.t
Description 
The genotype data table on the stock detail page is now asynchronous. Does not request all markers and actual genotype values for populating this table.
closes #2438 
Checklist 
> Stock detail page genotype data table is asynchronous

- db/00108/GenotypepropUserPermissions.pm
Description 
This patch gives permissions for inserting and using genotype and genotypeprop table. Your database may already have been modified manually, but this patch explicitly grants the needed permissions.
closes #2220 
Checklist 
> Adds genotype permissions patch

- mason/cookie_popup.mas
Description 
The cookie popup will now expire in 30 days and is set to the browser's global path.
closes #2464 
Checklist 
> Fixes cookie popup expiration and path

- mason/tools/blast/index.mas
Description 
BLAST finishes but does not report results because of a javascript problem on blast mason page. 
Issue #2417.
Fixed in this pull request.
Checklist 
> fix issue with blast

- bin/loading_scripts/load_stock_data.pl
Description 
fix an issue with a split command that split synonyms into individual letters. Tweak POD.
Checklist 
> add POD and fix bug that caused synonyms to be loaded as single letters.

- js/source/legacy/CXGN/BreederSearch.js
- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
- js/source/legacy/CXGN/BreedersToolbox/AddTrial.js
- js/source/legacy/CXGN/BreedersToolbox/Crosses.js
- js/source/legacy/CXGN/BreedersToolbox/FieldBook.js
- js/source/legacy/CXGN/BreedersToolbox/GenotypingTrial.js
- js/source/legacy/CXGN/BreedersToolbox/MarkerSet.js
- js/source/legacy/CXGN/List.js
- js/source/legacy/CXGN/Trial.js
- js/source/legacy/solGS/cluster.js
- js/source/legacy/solGS/listTypeSelectionPopulation.js
- js/source/legacy/solGS/listTypeTrainingPopulation.js
- js/source/legacy/solGS/pca.js
- js/source/legacy/tools/LabelDesigner.js
- mason/breeders_toolbox/accessions/find_trials_by_accessions.mas
- mason/breeders_toolbox/cross_wishlist.mas
- mason/breeders_toolbox/download.mas
- mason/breeders_toolbox/manage_plot_phenotyping.mas
- mason/breeders_toolbox/manage_trial_phenotyping.mas
- mason/breeders_toolbox/selection_index.mas
- mason/breeders_toolbox/trial/create_datacollector_dialog.mas
- mason/breeders_toolbox/trial/create_spreadsheet_dialog.mas
- mason/breeders_toolbox/trial/download_layout_interface_dialog.mas
- mason/breeders_toolbox/trial/download_trials_phenotypes_dialog.mas
- mason/search/genotype.mas
- mason/search/stocks_using_genotypes.mas
- mason/search/traits.mas
- mason/tools/graphicalfiltering/index.mas
- mason/tools/trial_comparison/index.mas
- mason/util/styleguide.mas
Description 
The public lists needed to be hidden in the addToListMenu interface.
Standardizes the listSelect to include all passed parameters in all uses.
closes #1557 
Checklist 
> listSelect can hide public lists. useful for addToListMenu

- mason/image/print_images.mas
- mason/page/detail_page_2_col_section.mas
Description 
Allows for different html identifiers to be used in the "show additional images" sections on the stock detail page, in order to differentiate the direct images section from the related stock images section.
closes #2497 
Checklist 
> different html ids for the two different image sections on stock page

- lib/SGN/Controller/AJAX/Trials.pm
Description 
Cached trees on manage trials, genotyping plates, and crosses is now stored in static_content_path instead of tmp directory.
Cached trees are regenerated automatically if it is not available already.
closes #2456 
Checklist 
> Cached tree moved to static content path out of tmp

- mason/breeders_toolbox/cross_wishlist.mas
Description 
Cross wishlist dialog would select the first list in the list select in order to draw the cross wishlist grid select, and when the selected list was too large the user's browser would run out of memory and the page would crash. Now the accession lists are loaded with an empty element.
closes #2507 
Checklist 
> cross wishlist with blank accessions list element

- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
- lib/CXGN/Stock/ParseUpload.pm
- lib/CXGN/Stock/ParseUpload/Plugin/AccessionsXLS.pm
- lib/SGN/Controller/AJAX/Accessions.pm
- mason/breeders_toolbox/add_accessions_dialogs.mas
Description 
Fuzzy search optional during accession file upload. Only curator can skip fuzzy search
Checklist 
> Do fuzzy search option on accession file upload

- lib/CXGN/BrAPI/v1/Trials.pm
- lib/CXGN/Trial/Folder.pm
Description 
Fixes error in BrAPI /trials call that retrieved study and location ids incorrectly and did not retrieve location name
Closes #2437
Checklist 
> fix trials call studies object

- db/00114/AddGenotypeProjectSearchTables.pm
Description 
The 00114/AddGenotypeProjectSearchTables db patch was not working for me, so i modified it to operate like the other materialized view db patches.
Checklist 
> fix running db patch

- js/source/legacy/CXGN/ComposeTrait.js
- lib/SGN/Controller/AJAX/Onto.pm
- lib/SGN/Controller/Ontology.pm
- mason/ontology/compose_trait.mas
- ontology/cxgn_time.obo
- sgn.conf
Description 
Adds new terms to time ontology for specifying events. For example specifiying that `virus symptoms | 1 month`is `virus symptoms | 1 month | after planting`,  or `beta carotene | week 4` is `beta carotene | week 4 | after harvest`
closes #2589
Checklist 
> add event relation terms to time ontology and related code

- lib/SGN/Controller/solGS/Files.pm
Description 
Compile time error occurs here, but only in Debian 9!  (Perl tightened its type checking... )
Checklist 
> fix error in lib/SGN/Controller/solGS/Files.pm.

- mason/breeders_toolbox/location_map.mas
Description 
When there are no stored locations in the DB, there are no map bounds to calculate and the map
does not display on /breeders/locations
This fix sets the map bounds to the entire world if the calculated map bounds are not provided
Checklist 
> Bug Fix: Location Map does not display if no locations

- mason/search/stocks.mas
Description 
The organization input in the Accession Search (Advanced -> Properties) did not autocomplete and did not filter search results
This adds the autocomplete source URL for the input
and updates the organization stock prop search term when the input field is changed
Checklist 
> Bug Fix: Accession search by Organization

- mason/breeders_toolbox/manage_upload.mas
Description 
Changed name associated with link to create the plate such that it pulls up the workflow to Add Genotyping Plate.
Issue #2697 
Checklist 
> fix link to create genotyping plate

- lib/CXGN/BreedersToolbox/StocksFuzzySearch.pm
- lib/CXGN/List/Validate/Plugin/Accessions.pm
- lib/SGN/Controller/AJAX/DeriveTrait.pm
Description 
Derived trait module can now handle ontology database names with more than 2 characters. 
Also fixed accession validation in lists to be case insensitive and fixed a typo in a variable in StocksFuzzySearch.pm.
Checklist 
> fixed derived trait to allow ontology database names with more than 2 caracters

- lib/CXGN/Genotype/Download/DosageMatrix.pm
- lib/CXGN/Genotype/Search.pm
- lib/SGN/Controller/Stock.pm
Description 
Fixes genotype download cache in dosage matrix format to account for chromosome list, start, and end position
addendum to PR #2748 
Checklist 
> Addendum to PR/2748 for genotype download fixes

- mason/breeders_toolbox/genotyping_trials/upload_genotyping_data_dialogs.mas
Description 
Adds IBRC Japan as a genotyping facility when uploading VCF
Checklist 
> add ibrc japan genotyping facility

- db/00117/AddNOAAGeolocationPropCvterms.pm
Description 
Adds a missing cvterm for storing the NOAA location identifier for a location. NOAA identifier useful for extracting weather information from NOAA databases.
Checklist 
> add NOAA geolocation prop cvterm

- mason/breeders_toolbox/folder/folder_set.mas
Description 
This adds the `multiple` attribute to the trials select box so multiple trials can be moved into a folder at once.
Fixes #2760 
Checklist 
> Add 'multiple' attribute to trials list

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
There were changes to the brapi calls that were causing the ID in the selectbox to not be registered.
Heatmap is now downloadable as a PNG image
closes #2793
closes #2725 
closes #2796 
Checklist 
> Trial detail page heatmap now working again

- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
- lib/SGN/Controller/AJAX/Accessions.pm
Description 
When a non-curator was uploading an accession template:
In some cases the disabled (but checked) fuzzy search checkbox was not being sent as checked to the `verify_accessions_file` endpoint and the user was receiving an error stating only a curator can disable the fuzzy search.
This fix will only disable the fuzzy search in the `verify_accessions_file` endpoint if the user is a curator when the checkbox is off.
It also displays error messages sent in the `error_string` property of some responses (others use the `error` property).
Checklist 
> Upload Accessions: fuzzy search and error message

- lib/SGN/View/Mason.pm
Description 
This pull request will enable UTF-8 in mason files, thereby allowing foreign language fonts to be displayed correctly on the site.
Checklist 
> enable UTF-8 in Mason.

- mason/user/change_account.mas
Description 
fixes #2871 - system displayed a debugging alert box. It has been removed.
Checklist 
> remove debugging alert box after account into change.

- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
Description 
This fixes an incorrect column id for getting the accession_name from the upload template
This was causing the synonym lookup to fail
Fixes #2885 
Checklist 
> Parse Multi-Trial Upload Bug: accession name column

- lib/CXGN/Trait/Search.pm
- lib/SGN/Controller/AJAX/Search/Trait.pm
- mason/search/traits.mas
Description 
The trait search table checks for VARIABLE_OF before adding to list. also shows the relationship term in the table.
Gives the user information that only observation variables can have phenotypes collected, meaning the term must have a VARIABLE_OF relationship.
closes #2831 
Checklist 
> Fixes to trait search to check for VARIABLE_OF relationship

- mason/breeders_toolbox/trial/download_phenotypes_dialog.mas
The download phenotypes dialog (from the trial and folder detail pages) was only allowing a single trait to be selected.  This changes the single select box to a multi-select box.
> Phenotype Download: Allow multiple traits to be selected

- lib/SGN/Controller/AJAX/User.pm
- mason/site/login_dialog.mas
- t/unit_mech/AJAX/Login.t
Description 
Revert login form ids to how they were previously because of selenium tests using these html ids.
Checklist 
> revert login form ids

- lib/SGN/Controller/AJAX/User.pm
Description 
Fixes the link that points back to the quick account creation page after successful account creation.
Checklist 
> fix link for account creation page.

- mason/breeders_toolbox/breeder_search_page.mas
Description 
There is an issue generating the wizard GRM heatmap download in some cases. The three-column and matrix formats are working as expected.
Checklist 
> hide wizard grm heatmap for now

- mason/tools/blast/index.mas
Description 
A javascript event was added that changes the default for word_size when a new program is selected with the program pull down menu. 
Checklist 
> fix defaults for word_size in blastp, blastx, tblastx and tblastn

- ontology/cxgn_plant_cycle.obo
- ontology/cxgn_plant_level.obo
Description 
Musabase needs separate plant cycle terms  (attribute) from plant level terms (object) 
Checklist 
> separate plant levels and cycles into different namespaces

- js/source/entries/wizard.js
Description 
This PR fixes a bug that enables public lists (created by a different user) to be accessible in the "Select Column Type" selectbox in the Search Wizard.
Fixes solgenomics/sgn#3027
Checklist 
> Search Wizard: get public lists

- lib/SGN/Controller/User.pm
- mason/site/login_dialog.mas
This PR reinstates the `/user/new` URL for directly bringing up the new user registration page.
We've found that some people have a hard time finding the new user registration page when its link is only found on the login dialog.  Having a direct link we can add to the homepage and send in an email has been helpful.
Checklist 
> User: dedicated URL for new user registration

- lib/CXGN/Project.pm
Description 
Phenotypic values that shouldn't be deleted are sometimes deleted when "overwrite values" is selected in the phenotype upload dialog. The extra deletes occurred because all of the nd_experiments associated with the phenotypes in question were deleted, but sometimes nd_experiments have more phenotypes associated with them, which were then left dangling in the database. The fix checks if there are any phenotypes still associated with the nd_experiment and deletes only  nd_experiments with no associated phenotypes.
Closes issue #3159 
Checklist 
> When phenotypes are uploaded, the "overwrite" option sometimes deletes phenotypic values that shouldn't be deleted

- mason/breeders_toolbox/trial/phenotype_summary.mas
Description 
Option to select 5 as the page length on trial phenotype summary table.
closes #3151 
Checklist 
> add trial pheno summary options for page length

- lib/SGN/Controller/AJAX/BreedersToolbox.pm
Description 
The delete button on the Manage > Phenotyping page (`/breeders/phenotyping/`) always resulted in an error due to an undefined reference to `$self->bcs_schema`.
This PR fixes that bug, only attempts to delete phenotypes and nd_experiment values if they still exist (so the file can still be set as obsolete), and refreshes the matviews after the deletion is complete.
Checklist 
> Bug Fix: Delete phenotyping spreadsheet file

- js/source/modules/wizard-search.js
Description 
Fixes bug where search filters were ignored when using select all buttons in the wizard.
closes #3181
Checklist 
> incorporate search filter in select all feature

- lib/SGN/Controller/AJAX/Search/Trait.pm
- mason/search/traits.mas
Description 
This fixes a bug where the trait list item names were using the wrong values
Add back the plain text trait name and trait accession values to the AJAX response
Update the indices of the values used to create the trait list item names
Checklist 
> Bug Fix: creating list of traits from the trait search page

- mason/breeders_toolbox/trial.mas
Description 
Trial page crashes if database does not have country information in location tables. This makes the parameter to the trial page optional.
Checklist 
> make country_name an optional parameter.

- lib/CXGN/Trial/TrialLayout/AbstractLayout.pm
Description 
Bug caused the cache rebuild for a trial to fail.
Checklist 
> fix typo in cvterm_id function on line 610 (cvterm should be cvterm_id)

- js/source/modules/wizard-search.js
Description 
This fixes a bug with the Search Wizard's "Select All" buttons.  It was using the filter/search text from the first column for all of the columns.  This gets the text from the appropriate column.
Checklist 
> Search Wizard: fix Select All button

- R/solgwas/solgwas_script.R
- lib/CXGN/Genotype/Search.pm
- lib/CXGN/Phenotypes/PhenotypeMatrix.pm
Description - Fix errors when running solgwas tool. 
1. long trial descriptions would give wrong number of columns when reading in file by R scripts
2. R script could not match trait provided in arguement with trait in phenotype file because of the trait name was being changed using the default check.names = TRUE
https://github.com/solgenomics/sgn/issues/3212
#3212 
Checklist 
> Gwas clay fixes

- lib/SGN/Controller/AJAX/Pedigrees.pm
Add a check that the headers are correct in the pedigree upload, as the upload crashes silently when the headers are not correct.
Addresses issue #3294.
Description 
Checklist 
> add a check that the headers are correct in the pedigree upload

- lib/CXGN/Contact.pm
- lib/CXGN/Login.pm
Description 
This allows the test sites to also send emails, by removing the constraint that suppressed emails when production_server = 0.
Note that you still may have to 
* configure the correct github_access_token in sgn_local.conf (it can be copied from a production server), and that 
* the main_production_site_url, also in sgn_local.conf, needs to be set to the correct domain such that the confirmation link in the verification email goes to the correct site.
* set disable_emails = 0 in sgn_local.conf (this should be the default)
* postfix needs to be installed on the vm/server
* there might be additional firewall issues in sending mail
Closes issue #3302.
Checklist 
------------------------------------------------------------------- …
> Allow test sites to send emails (contact and registration verification emails)

- lib/CXGN/Trial/TrialDesign/Plugin/Augmented.pm
- lib/CXGN/Trial/TrialDesign/Plugin/RCBD.pm
Description 
1 - Augmented design was creating wrong number of blocks.
2 - Both (RCBD and Augmented) were numbering the plots sequentially when changing from block to another. Now it is in this way:
101 - blc1
201 - blc2
301 - blc3
...
Checklist 
- [ X] Bug fix
> fixing trial design and plot numbering for Augmented and RCBD

- lib/SGN/Controller/AJAX/Pedigrees.pm
Description 
added a line that removes the line feeds from the header. The rest of the lines in the files were already processed correctly.
Checklist 
> remove DOS style line feed characters in the header line.

- lib/CXGN/Phenotypes/ParseUpload/Plugin/PhenotypeSpreadsheetCSV.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
Description 
The phenotype download does not list values of zero when the CSV format is chosen. The values need to be checked for definedness, not true or false, as 0 is a false value in Perl.
Checklist 
> Phenotype download in CSV format does not report values of zero

- lib/SGN/Controller/AJAX/TrialMetadata.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/breeders_toolbox/trial.mas
Implement policy: Curators can edit, submitters when associated with respective breeding program, users cannot edit.
Also, edit button is only active when these conditions are met.
closes #3347
Description 
Checklist 
> tweak trial metadata editing permissions

- lib/SGN/Controller/Bulk.pm
- t/legacy/integration/bulk_feature.t
- t/legacy/integration/bulk_gene.t
Description 
fixes issue #3378 
Digest::SHA is already installed in the local-lib.
Checklist 
> remove Digest::SHA1 and replace with Digest::SHA.

- cgi-bin/search/markers/markerinfo.pl
- lib/CXGN/Marker/SearchJson.pm
- lib/SGN/Controller/Marker.pm
- mason/markers/indexGenotype.mas
- mason/markers/locationsGenotype.mas
adds a section to marker details page that will display markers from nd_protocolprop table
this pull request does not change the marker search page because that has been heavily modified for Triticeae Toolbox
the query for nd_protocolprop can be slow depending on the size of the table and how many protocols contain the marker
#3351 
Checklist 
- [ x] New feature
- [ x] User-Facing Change
> displays markers from nd_protocolprop table

- lib/CXGN/Analysis/AnalysisCreate.pm
- lib/CXGN/Dataset/File.pm
- lib/CXGN/Phenotypes/File.pm
- lib/CXGN/Phenotypes/Search/MaterializedViewTable.pm
- lib/SGN/Controller/AJAX/MixedModels.pm
Description 
The phenotype download in CXGN::Dataset::File was changed to contain quotes, which breaks the mixed model tool and possibly other tools. In this pull request, the CXGN::Dataset::File now has an additional method, quotes, which is by default true. Setting it to false (0) will generate files without quotes.
Check your tools to see if the quotes affect them... In general, I think the quotes are cleaner, and we should stay with the quotes for the general case.
Checklist 
> provide an option to download phenotype file with or without quotes; fix mixed model tool

- cgi-bin/search/markers/markersearch.pl
- lib/CXGN/Search/CannedForms.pm
query markers from genotype studies in marker search page
when "find only markers on map" is not selected the query will use nd_protocolprop table
#3351
Checklist 
- [x ] New feature
> add option to search nd_protocolprop in marker search page

- lib/SGN/Controller/AJAX/TrialMetadata.pm
When phenotypic data is already stored in the field plot, user is warned that trait data already exists in the field plot and is restricted from changing accessions in change accessions feature.
Description 
Checklist 
> Adds error message for user changing accession on fieldmap with existing phenotypic data

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
There was no event handler for pressing enter on the change accessions form so it's default behavior was just to refresh the page
without calling the appropriate function. 
Now pressing enter does not refresh the page and calls the hm_replace_plotAccession_fieldMap() function as it should.
Description 
Checklist 
> Pressing enter in change plot accession feature functions properly

- js/source/modules/wizard-downloads.js
- lib/CXGN/Genotype/Download/DosageMatrix.pm
- lib/CXGN/Genotype/Download/VCF.pm
- lib/CXGN/Genotype/DownloadFactory.pm
- lib/CXGN/Genotype/Search.pm
- lib/CXGN/Genotype/StoreVCFGenotypes.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/breeder_search_page.mas
Option on wizard download to include duplicate genotypes in returned VCF or DosageMatrix. If the option is selected, the downloaded file will have the unique database genotype_id appended in the header columns.
Fixes bug in upload of duplicate genotypes in the same protocol. If duplicate genotypes were uploaded for the same stock in the same protocol, only the most recent genotypes were stored. Now the upload will actually store all the duplicate genotypes.
Description 
closes #3453 
Checklist 
> Duplicate Genotypes Download

- mason/site/footer/body.mas
Description 
This adds git status information about the sgn repo to the footer, such as the latest commit hash, the latest tag, and the timestamp of the last commit.
This is added to the base mason component in /mason/site/footer/body.mas but will probably need to be incorporated into the site-specific mason file.
Checklist 
> Footer: add git status information

- bin/load_marker_dbxref.pl
- db/00141/AddVcfType.pm
- lib/SGN/Controller/AJAX/Marker.pm
- mason/markers/external_links.mas
use nd_protocol and nd_protocolprop table to store marker annotations
main use is to store links to external references (EnsemblPlant, Graingenes, haplotypes, etc
use type_id and cvterm "vcf_snp_dbxref"
#3482 
Checklist 
- [x ] New feature
> add marker annotation feature to nd_protocolprop table

- lib/CXGN/BrAPI/v2/BreedingMethods.pm
Description 
Switch Brapi breeding methods call to use female parent value (as is now done with brapi germplasm breeding methods).
Closes #3523
Checklist 
> update breeding methods call to use female parent values

- bin/download_trials.pl
Description 
Adds a script that downloads trial data without relying on mat views. Useful if data needs to be urgently downloaded, but matviews are not updated.
Checklist 
> Add script that downloads trial phenotype data without going through mat views

- lib/CXGN/BrAPI/v2/Observations.pm
Description 
- Refresh only `phenotype` materialized views for observations POST
- Should speed up the refresh
- The `traits` materialized view was breaking the refresh with an error ` ERROR: more than one row returned by a subquery used as an expression`, this change avoids that view. 
- Updated errors to return error codes instead of `200` responses. 
Checklist 
> [BI-956] - Bug fixes for brapi observations endpoint

- lib/SGN/Controller/AJAX/BrAPI.pm
Fixes a bug where the brapi controller expects a json array body for search calls because its a POST call.
> fix brapi data type check for search calls

- mason/breeders_toolbox/create_seedlots_from_trial_dialogs.mas
Description 
For the "Create Seedlots from Trial" workflow:
This adds the ability to use a formula to compute the initial seedlot contents using one or more trait values.
Checklist 
> Create Seedlots from Trial: use formula for initial seedlot contents

- bin/refresh_matviews.pl
- lib/CXGN/BrAPI/v1/Observations.pm
- lib/SGN/Controller/AJAX/PhenotypesUpload.pm
Description 
Currently, the `refresh_matviews.pl` script does not refresh the `materialized_phenotype_jsonb_table` matview with a '**fullview**' refresh and the '**phenotypes**' refresh does not update the `materialized_phenoview` matview.  This PR changes the '**phenotypes**' refresh to update both matviews.
The '**phenotypes**' refresh was only being used by the BrAPI v2 store observations function.  This changes the refresh in the BrAPI v1 store observations function and the phenotypes upload AJAX function to use the '**phenotypes**' refresh instead of the '**fullview**' option.
Fixes #3616 
Checklist 
> Refresh both phenoview and the jsonb matview after adding trait data

- js/package.json
- mason/breeders_toolbox/trial/field_trial_from_field_trial_linkage.mas
- mason/page/detail_page_2_col_section.mas
Description 
Adds a tree viewing diagram in the form of a d3 sankey. Trials that are linked via accessions/germplasm may be represented as a sankey, where nodes represent trials and links represent the flow of germplasm from parent trial to offspring trial. Doubleclicking a node will open a tab of the clicked trial. Single click will show the sankey diagram of the clicked trial. 
Note: requires some new javascript dependencies. Not quite sure how you guys manage those, so perhaps it should be addressed before merging.
#3267 
Checklist 
- [x ] New feature
> 3267 create historical tree visualization

- lib/SGN/Role/Site/Files.pm
Description
Addresses following error apparently caused by sgn/static/documents/tempfiles being a symlink to /tmp/root/SGN-site: 
```
the following error occurred while attempting to generate /home/production/cxgn/sgn/static/documents/tempfiles : mkdir /home/production/cxgn/sgn/static/documents/tempfiles: File exists at /home/production/cxgn/sgn/t/../lib/SGN/Role/Site/Files.pm line 233.
(may be ok)
dir '/home/production/cxgn/sgn/static/documents/tempfiles' creation failed (No such file or directory) at /home/production/cxgn/sgn/t/../lib/SGN/Role/Site/Files.pm line 241.
tempfiles dir '/home/production/cxgn/sgn/static/documents/tempfiles' does not exist, and could not create (No such file or directory) at …
```
> Handle mkpath() "file exists" error when tempfiles_subdir is a symlink

- mason/breeders_toolbox/genotyping_protocol/genotype_data.mas
- mason/breeders_toolbox/genotyping_protocol/index.mas
Description 
Adds download buttons on protocol detail page for downloading all data in VCF and Dosage Matrix formats
Checklist 
> Adds download buttons on protocol detail page

- t/unit_fixture/CXGN/Uploading/VCFGenotypes.t
Description 
Fix t/unit_fixuture/CXGN/Uploading/VCFGenotype.t test by skipping some tests that depdend on Java and high memory, if these are not available.
Checklist 
> skip tests with dependency on java and high memory.

- lib/CXGN/Trial/TrialDesign/Plugin/Augmented.pm
- lib/CXGN/Trial/TrialDesign/Plugin/RCBD.pm
Description 
Like breedbase agricolae creates trial designs with 3 plot numbering options, but they don't match up exactly. Argricolae has no option to start plot numbering at 1, so the easiest way to do that in breedbase is use the row names. 
closes #3673
Checklist 
> overwrite unwanted agricolae plot numbers with correct pattern

- js/source/entries/wizard.js
- js/source/legacy/CXGN/List.js
Description 
Previously, if a List of Seedlots was selected in the Search Wizard, nothing would be displayed.  This PR allows Lists of Seedlots to be selected in the Search Wizard by supporting `seedlot` as a list type in the `CXGN/List.js` `transform2Ids()` function.
It also updates the URL for a Seedlot item to use the specific Seedlot detail page (instead of the general Stock detail page).
Checklist 
> Allow Lists of Seedlots in Search Wizard

- lib/SGN/Controller/AJAX/Solgwas.pm
Description 
fix the same issue for the solgwas tool - getting traits from the dataset now gives you a list of lists with [trait_id, name] instead of just trait_id.
Checklist 
> fix also solgwas.

- lib/SGN/Controller/AJAX/People.pm
- mason/breeders_toolbox/manage_roles.mas
Description 
when roles are submitted, they sometimes are added multiple times, depending on how many times the dialog was opened (#3700). 
The issue was fixed by removed the event registration for the dialog submission outside of the event loop itself.
Checklist 
> fix multiple submit problem on user roles

- lib/CXGN/Stock/Seedlot/Maintenance.pm
- mason/breeders_toolbox/seedlot_maintenance/record.mas
- mason/breeders_toolbox/seedlot_maintenance/table.mas
- mason/breeders_toolbox/seedlot_maintenance/tools/split_seedlot.mas
Description 
This adds some minor improvements and bug fixes related to the Seedlot Maintenance Features
**Bug Fixes:**
- workaround for jQuery bug setting values for random inputs when returning to the record page via the browser back button
**Improvements:**
- allow the Seedlot Maintenance Event filter function to accept multiple seedlot name filters with passed comparisons
- add seedlot name "includes" input to event filters
- truncate list of displayed seedlot names for long lists
Checklist 
> Seedlot Maintenance: minor improvements and fixes

- js/source/legacy/tools/LabelDesigner.js
- lib/SGN/Controller/AJAX/LabelDesigner.pm
- mason/tools/label_designer/label_designer_modals.mas
Description 
This add options to the Additional Settings of the Label Designer to manually set the column and row positions of the first label -- useful if you want to print labels on a sheet that's been partially used.
Checklist 
> Label Designer: add options for start col and row

- lib/SGN/Controller/AJAX/User.pm
- mason/user/reset_password_form.mas
We had several users who forgot their username so were not able to login or reset password
This change adds username to the email that gives link to password reset
After resetting password the screen was disabled with popup that could not be closed
This change adds redirect to home screen after succesfull password reset
goto home page after password reset
Checklist 
- [x ] Bug fix
> identify username for account when resetting password

- lib/SGN/Controller/AJAX/HTMLSelect.pm
- mason/breeders_toolbox/trial/download_layout_interface_dialog.mas
Description 
This adds the option for the user to create more than one Fieldbook Layout file at a time by selecting a List of trials to generate the files for.
**Changes:**
The HTMLSelect endpoint for trials (`/ajax/html/select/trials`) now as an `include_lists` option that when set to `1` will include the user's trial lists and any public trial lists after the individual trial options.
The Trial Select in the `download_layout_interface_dialog.mas` component now includes Lists of Trials as an option.  Additional changes were made to handle more than one selected trial:
- Management Factors are only selectable if a single Trial is selected
- The checks for data levels occur for each Trial - if one does not include the selected data …
> Create Multiple Fieldbook Layouts from Trial List

- .github/workflows/test.yml
Runs all tests for PRs in a breedbase/breedbase_dockerfile environment.
A few relevant nice-to-haves before merging:
* Uses a non-main breedbase/breedbase_dockerfile branch
* The docker-compose.test.yml `cache_from: breedbase/breedbase:v0.31` doesn't seem to use layers from that image as a cache. As a result, the entire image is rebuilt each time (~16 minutes or so).
* Currently the `Run tests` step passes if `docker compose run` of the tests completes, despite test failures. Once all tests pass, the exit status of this step should probably reflect the existence of any test failures.
> GitHub Actions workflow to test PRs

- lib/CXGN/Stock/Search.pm
- mason/search/stocks.mas
Description 
This PR get optional stock prop parameters given in the url to load the search page
Parameters are prop and value
Ex.
/search/stocks?prop=variety&value=NASE3
Checklist 
> adding get stockprops params to the search page

- lib/SGN/Controller/AJAX/User.pm
- lib/SGN/Controller/User.pm
- mason/site/login_dialog.mas
- sgn.conf
- t/unit_mech/AJAX/Login.t
Description 
Some minor improvements to the user registration workflow:
- Rephrase confirmation email message ('The return address is not valid' was confusing some users - thought their request for an account failed)
- Usernames should not contain spaces (this caused the confirmation link in the email to break, possibly other issues?)
- Email addresses can only be registered to one account (we had users creating a lot of duplicate accounts)
- Replace back navigation after registration with closing the modal dialogs
- Fix confirmation error message display on confirmation page
- Fix redirect on login page, if `goto_url` is not specified
- Add a forgot username function (sends email with username(s) associated with the email address)
- …
> User Registration Improvements

- .github/workflows/test.yml
- t/test_fixture.pl
- t/unit/CXGN/PRepDesign.t
Description
test_fixture.pl currently exits with exit status 0 if nothing happens that prevents the tests from running.
This PR proposes making test_fixture.pl exit with a non-zero exit status if any test fails, to allow such failures to be propagated to automated testing (via an existing GitHub Actions workflow).
Checklist 
> test_fixture.pl exits with non-zero exit status if any tests fail

- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
Description 
A minor bug fix for the error message displayed in the multi-trial upload when multiple synonyms are found.
The`multiple_synonyms` array is a 2D-array where each item is an array of the uniquename and synonym.  This changes the error message to display the name and synonym (rather than the array reference).
**Before:**
**After:**
Checklist 
> Multi Trial Upload: improve error message for multiple synonyms

- lib/CXGN/Phenotypes/ParseUpload/Plugin/FieldBook.pm
Description 
Interestingly, File::Slurp is not intelligent enough to remove DOS style line endings! Adding a line to do that here, otherwise DOS style file cause the` upload to fail.
Checklist 
> remove \r characters from line endings in fieldbook file upload

- .github/workflows/test.yml
Description 
Redirect stderr of tests run in GitHub Actions to /dev/null to reduce output volume.
Checklist 
> Reduce output from GitHub Actions tests

- mason/breeders_toolbox/genotyping_data_project/protocols.mas
Viewing the trial detail page causes a javascript error popup with DataTable error. This is caused by the genotyping protocols section that has an extra column. Removing the extra column "Sample Type" fixes the problem
Checklist 
- [ x] Bug fix
> remove extra column in table to fix DataTable warning

- db/00154/AddFamilyTypeCvterm.pm
- lib/CXGN/Pedigree/AddFamilyNames.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/FamilyNameExcel.pm
- lib/SGN/Controller/AJAX/Cross.pm
- lib/SGN/Controller/Cross.pm
- mason/breeders_toolbox/cross/family.mas
- mason/breeders_toolbox/cross/progenies_in_crossingtrial.mas
- t/unit_fixture/CXGN/Uploading/UploadAndAddCrossesCrossingtrial.t
> Allow reciprocal crosses to be included in the same family

- lib/SGN/Controller/AJAX/List.pm
Description 
Changes list download behavior from displaying list in browser to giving a pop up to download list.
Resolves : https://github.com/solgenomics/sgn/issues/3883 
Checklist 
> Download lists instead of displaying in browser

- lib/SGN/Controller/AJAX/LabelDesigner.pm
Description 
Fix 1D barcode initialization so that all barcodes are appropriately printed instead of only the first.
Resolves Issue: https://github.com/solgenomics/sgn/issues/3917
Checklist 
> Fix 1D barcode bug 

- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
Description 
when management factors are specified, the upload expects them to be either undef or 1, but the excel parser returns empty string or 1. This PR allows fields to be empty string as well as undef.
Checklist 
> Fixes issue with multi trial upload

- R/solGS/gs.r
-- fix rlang package upgrade issue: replace `parse_quosure()` with  `parse_expr()`
-- use `all_of` when passing external variables to dplyr functions
> replace deprecated rlang function

- js/source/legacy/CXGN/List.js
- js/source/legacy/icon_nav.js
- js/source/legacy/jquery/simpletooltip.js
remove unsupported jQuery.browser call that was used to accommodate IE weirdness. This affected the ability to create lists.
Description 
Checklist 
> remove unsupported jQuery.browser call

- Search.pm
- lib/CXGN/Genotype/Search.pm
When downloading from multiple genotype projects there are empty values in the genotype results.
This add a "./." value when there is no GT entry 
#3769 
Checklist 
> if genotype is missing set value to ./. for VCF download

- lib/CXGN/Trial/ParseUpload/Plugin/TrialExcelFormat.pm
Excel parser returns empty string, not undef, for empty cells. (multi trial upload has already been fixed.)
Description 
Checklist 
> fix treatment upload for single trial also

- lib/CXGN/Genotype/ParseUpload/Plugin/GridFileIntertekCSV.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/IntertekCSV.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/VCF.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/transposedVCF.pm
Description 
When uploading genotyping data, uncallable or missing data will be coded as './.' instead of 'NA'. Dosage still coded as 'NA'.
Resolves #3769 
Checklist 
> Change VCF missing genotypes from NA to ./.

- lib/CXGN/List/Validate/Plugin/Accessions.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
Description 
This improves the speed of:
- The accession list validation:
- For a list of 10,000 accessions it would take ~8 minutes to validate, now it takes ~2 seconds
- The validation function now makes 1 query to find all of the items that have an exact (case-sensitive) match on the uniquename
- Then it performs additional searches (case-insensitive uniquename and synonyms) for the items that did not have an exact match 
- The accession properties download (from `/breeders/download`):
- For a list of 10,000 accessions it would take almost 30 minutes (validation ~8 minutes + download ~18 minutes), now it takes <10 seconds
- The download function was creating a new Accession/Stock object for each list item, now it makes 1 query to …
> Speed Improvements: Accession List Validation & Accession Properties Download

- js/package.json
- lib/SGN.pm
- lib/SGN/Script/Server.pm
with appropriate backslashing (two in this case).
Description 
Checklist 
> another npm fix. Numeric user ids require a leading # sign 

- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
Realized the main issue was not the matview refreshing, but the cache regeneration. Added a refresh cache function to trialmetadata and made submit fieldmap layout invoke it.
Checklist 
> fixed cache generation upon changes to fieldmap submission

- bin/refresh_matviews.pl
Description 
The update_in_progress info is not correctly updated for materialized_phenoview when 'phentoypes' is selected. Similar issues with 'all_but_genoview'.
Checklist 
> fix how matview info is updated.

- db/00158/AddCascadeDeletes.pm
Description 
Edits cascade delete patch to handle databases that do not have the altered foreign keys in the first place.
Checklist 
> add IF EXISTS to handle dbs that are missing fkey constraints

- lib/SGN/Controller/BreedersToolbox/Download.pm
Description 
Symptom: Certain values are repeated in the columns, such as in the organization column, IITA is repeated n times when there are n populations present (similar with other keys), when a download is made from the ```/breeders/download``` page, "Download Accession Properties" section.
Solution: report only distinct values for the string aggregation function.
Closes #4086.
Checklist 
> The accession attribute download repeats certain entries

- .github/workflows/test.yml
add shm_size: 2g option to breedbase_db container, which may fix randomly crashing tests due to memory limitations.
Description 
Checklist 
> Potential fix for randomly crashing tests on github

- .github/workflows/test.yml
Unfortunately, github service does not support all the options of docker-compose. See https://github.com/moby/moby/issues/25303
Description 
Checklist 
> The shm_size option is not supported on github service

- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
Description 
Adds missing trial design types to multi-trial upload documentation
closes #4115
Checklist 
> add missing design type info to docs

- js/source/legacy/CXGN/BreedersToolbox/AddTrial.js
- lib/CXGN/Trial/TrialDesign/Plugin/Prep.pm
Description 
This fixes the accessor error when creating a p-rep trial (first reported 2+ years ago!)
It also confirms that the p-rep trial design code still works with the latest version of DiGGer (v1.0.5), which requires R v4+.
Fixes #2834
Fixes #3822 
Checklist 
> P-rep Trial Design Plugin: fix replicated/unreplicated accessors

- mason/breeders_toolbox/create_tissue_samples_dialogs.mas
- mason/breeders_toolbox/sampling_trials/create_sampling_trials_dialogs.mas
- mason/breeders_toolbox/trial/add_tissue_sample_per_plant.mas
- mason/help/workflow_guided/tissue_sample_help.mas
Description 
The PR provide info to users that seed and fruit can also be used as tissue types during tissue sampling trial creation and adding of tissue samples to field trials. 
Checklist 
> add seed and fruit as options for tissue samples.

- lib/CXGN/Trial/ParseUpload/Plugin/SamplingTrialXLS.pm
Description 
Added seed and fruit as valid tissue types that pass the .xls file checks on upload of sampling trial.
Checklist 
> Allow seed and fruit to pass xls file check

- js/source/legacy/tools/LabelDesigner.js
Description 
Fixes bug where sets of exactly 1000 labels did not trigger normal download or batch download.
closes #4082
Checklist 
> handle exactly 1000 labels, and clarify text details

- lib/SGN/Model/solGS/solGS.pm
Description 
Change phenotype data search type to 'Native' from 'MaterializedViewTable'. This allows users to analyze data immediately after upload, with out having to wait for the matviews to be updated.
Checklist 
> change phenotype data search_type to Native

- js/package.json
- js/source/entries/fieldmap.js
Description 
This removes the optional chaining JS syntax from the fieldmap.js file
Checklist 
> Fieldmap.js: remove optional chaining syntax

- R/heritability/h2_blup_rscript.R
- lib/SGN/Controller/AJAX/Heritability.pm
- mason/tools/heritability/index.mas
Description 
This fixes a small typo in the heritability R script:
https://github.com/solgenomics/sgn/blob/86c31e7fdf3fa280497c97ba72b69ffba58dc43c/R/heritability/h2_blup_rscript.R#L85
It also adds a few more try/catch blocks and writes all of the error messages encountered in the R script to a file which is used to return the error messages to the website.
Checklist 
> Heritability: Return error messages to website

- lib/CXGN/BrAPI/v2/ObservationTables.pm
- lib/CXGN/BreedersToolbox/Projects.pm
- lib/CXGN/Phenotypes/PhenotypeMatrix.pm
Description 
Shortens the treatment query lengths in wizard downloads by using trial ids then filtering the results by observation unit ids
closes #4326
Checklist 
> refactor treatment query in wizard download

- lib/SGN/Controller/Blast.pm
The db_id parameter query joined to the group table, instead of the linking table, not retrieving datasets if the blast_db_group_id was not set in sgn.blast_db. This should now go through the linking table and that column in sgn.blast_db should be removed. This PR only changes the query.
Description 
Checklist 
> db_id parameter in blast url not working correctly

- bin/transpose_matrix.pl
- lib/CXGN/Genotype/Search.pm
replace missing values in POS field of VCF output with 0
when values in VCF were specified as missing with dot '.' the transform_matrix.pl would remove those columns. This patch fixes that problem. The VCF specification also say that the POS column must be an integer and the TASSEL program will fail if POS is not an integer. To fix this case, the VCF output converts the dot '.' entry to a 0
fixes #4328
Checklist 
- [ x] Bug fix
> allow missing values to be specified with dot '.' for VCF input

- lib/SGN/Controller/AJAX/Cvterm.pm
Description 
Topic/fix accession query on trait detail page
The section "Phentoyped accessions" does not work on most Breedbases because the query is based on an outdated data storage scheme. With this PR the accessions should be shown correctly on most instances.
Checklist 
> Fix the datatable on cvterm detail page that shows associated accessions

- lib/CXGN/Login.pm
- lib/SGN/Controller/AJAX/Login.pm
Description 
Issue caused certain tools relying on datasets not to work, because a dialog box "Login required!" erroneously appeared.
Checklist 
> fix an issue with the /user/logged_in ajax call.

- lib/CXGN/BrAPI/v2/ObservationUnits.pm
BrAPI Search Observations Units:
when the `includeObservations` parameter is included, it is being converted to an array somewhere, but the search function is expecting a "true"/"false" value.  This checks to see if the param is an array and uses the first value if it is.
This was causing the Compare Trials tool to fail since no observations were being returned from the BrAPI call.
Checklist 
> BrAPI: Search Observations Units - includeObservations param

- lib/CXGN/List/Validate/Plugin/Locations.pm
- lib/CXGN/Trial/ParseUpload.pm
- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
Description 
This allows the multi-trial upload template to use location codes/abbreviations, in addition to the full location name.
- List Validation: 
- adds a `codes` key returned with the list validation that matches valid location codes with full location names
- a code match is still considered 'missing' so this doesn't change the behavior of other code using the location list validation
- Multi-Trial Excel Upload Plugin:
- returns a warning if a location code is going to be substituted with a location name, so the user has to approve the substitution
- the parsed trial design will have the location code replaced with the full location name
Checklist 
-------------------------------------------------------------------------------- …
> Location Validation: Check for code/abbreviation matches

- sgn.conf
Description 
Allow ClimMob to login with breedbase instance credentials.
Checklist 
> Provide ClimMob with redirect login access

- lib/CXGN/BrAPI/v1/Observations.pm
- lib/CXGN/BrAPI/v2/Observations.pm
- lib/CXGN/List/Validate.pm
- lib/CXGN/List/Validate/Plugin/Traits.pm
- lib/CXGN/Phenotypes/StorePhenotypes.pm
- lib/SGN/Controller/AJAX/DeriveTrait.pm
- lib/SGN/Controller/AJAX/DroneImagery/DroneImagery.pm
- lib/SGN/Controller/AJAX/HighDimensionalPhenotypes.pm
- lib/SGN/Controller/AJAX/PhenotypesUpload.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
- sgn.conf
- t/unit_fixture/CXGN/Trial.t
- t/unit_fixture/CXGN/Trial/DeriveTrait.t
- t/unit_fixture/CXGN/Uploading/Phenotype.t
- t/unit_fixture/CXGN/Uploading/ValidateNIRS.t
Description 
When uploading trait observations, the column header uses the format of `trait_name|trait_id` (such as `Grain yield - kg/ha|CO_321:0001218`).  The trait validation just checks to make sure the DB and Accession (`CO_321:0001218`) are valid and ignores the trait name (this allows users to use different trait names, such as just `yield|CO_321:0001218`).
This isn't a problem for traits in the official trait ontology, since all of the traits share the same DB and Accession for all of the instances using the same crop trait ontology.
However, problems can arise for the composed traits.  If we add the same composed trait to two different databases, they will most likely have a different accession in each database (`COMP:0000043` …
> Trait Validation: Check trait name for COMP traits

- lib/CXGN/BreedersToolbox/Projects.pm
- lib/CXGN/Phenotypes/Search/Native.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/stock/download_stock_phenotypes_dialog.mas
Description 
On the accession detail page, the accession phenotype download crashes. Turns out that some code in the process relies on trial ids, which are not always provided. In that case, that part of the query is ignored.
Checklist 
> Fix accession phenotype download

- mason/site/toolbar/login.mas
Description 
When the `require_login` conf key is set, the login dialog is shown on the password reset page, preventing the user from entering their new password.
This PR stops the login dialog from being shown on the password reset page.
Checklist 
> Don't show login dialog on password reset page

- js/source/legacy/CXGN/BreedersToolbox/HTMLSelect.js
- mason/stock/download_stock_phenotypes_dialog.mas
Description 
Fixed selection of all traits from the dialog box.
functionality is here:
Manage/Accessions  
-> Accession detail page   
-> Traits Assayed ( panel ) 
-> Download Phenotypes ( button ) 
-> Additional Search Options
[Screencast from 05-11-2023 08:24:33 PM.webm](https://github.com/solgenomics/sgn/assets/7416921/f74b5cc2-7a5b-4820-9355-92664a66e1a7)
Checklist 
> download all traits from phenotype dialog box fixed

- lib/CXGN/Stock.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/download.mas
- t/unit_mech/AJAX/DownloadPedigrees.t
Description 
This modifies the Pedigree download from the "Download Using Lists" page:
- Adds a [helium](https://helium.hutton.ac.uk/#/) format for the web-based and desktop pedigree viewers (Fixes #2401)
- Adds an option to include descendants/children in the pedigree file
- Removes duplicate rows from the downloaded pedigree file (before: if an accession was found more than once in the pedigree tree, it would have a row in the file listing it and its parents for each occurrence)
Checklist 
> Pedigree Download: Helium Format

- mason/solgs/tools/anova/analysis.mas
- mason/solgs/tools/select_menu.mas
Description 
fixes buttons positioning that was overflowing or overlapping with long list/dataset names in select menu
Checklist 
> position html elements next to each other properly

- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
- lib/SGN/Controller/AJAX/Accessions.pm
Description 
Accession Upload:
unicode characters (such as accented letters) were not being properly returned from the `verify_accessions_file` endpoint.
This prevents the JSON serializer from re-encoding text that is already utf-8 encoded
Checklist 
> Accession Upload: verify accessions file character encoding

- lib/CXGN/Genotype/ParseUpload/Plugin/SSRExcel.pm
- lib/CXGN/Genotype/StoreVCFGenotypes.pm
- lib/SGN/Controller/AJAX/Search/Genotype.pm
> Allow SSR genotyping data with less number of markers to be included in previously stored protocol

- lib/SGN/Controller/AJAX/FieldBook.pm
- sgn.conf
Description 
Original functionality would look for any synonym of a trait that was all caps, and use that synonym in the Field Book trait file.  Added a config flag to toggle the original functionality, or just using the trait name in the file.
Checklist 
> Added a config flag to control if the Field Book trait export file should use a trait's synonym or not

- db/00167/MakeRankNumberStockPropViews.pm
- lib/CXGN/Stock/Search.pm
- lib/CXGN/Stock/SearchVector.pm
Description 
When querying for additionalInfo, the code was prepending `RANK` to the `stockprop.rank` value.  This works fine when there are less than 10 fields in the `additionalInfo` of a `stockprop`, 10 or more causes the `additionalInfo` to become invalid JSON once reconstructed.  Removed the `RANK` keyword so that sorting on the `stockprop.rank` field can be a comparison of numbers and not strings.
Checklist 
> Remove RANK keyword from additionalInfo storage and retrieval

- lib/CXGN/BrAPI/v2/Germplasm.pm
- lib/CXGN/BreederSearch.pm
Description 
Allowing the refresh_matviews script to be run synchronously.
Checklist 
> Allowing the refresh_matviews script to be run synchronously.

- lib/CXGN/BrAPI/v2/Locations.pm
Description 
When trying to update a location, the update code would throw a validation error due to the location name already existing.  Updated the existing name check to exclude the location attempting to be updated.
Checklist 
> Fix bug when trying to update a location

- lib/CXGN/BrAPI/v1/Studies.pm
- lib/CXGN/BrAPI/v2/ObservationUnits.pm
Description 
Fixed a SQL bug where sorting observation units was casting the order by field to an `int`.  Changed this to cast to `numeric` as it is more inclusive 
Checklist 
> Fixing observation unit sort order

- lib/Bio/BLAST2/Database.pm
- lib/Bio/BLAST2/Database/Seq.pm
Description 
The BLAST code checks extensions of BLAST databases, some of which are remnants of the BLAST 1 code. BLAST 2 has different extensions which interfered with the retrieval of sequences from the BLAST databases.
Note that all BLAST databases need to be re-indexed with makeblastdb to continue working!
makeblastdb example:
```
makeblastdb -in Nitabv6-assembly_Chrs+Ch0.fa -dbtype nucl -parse_seqids
```
(-parse_seqids is important for sequence retrieval with blastdbcmd)
Checklist 
> fix the extension for the new(er) version of BLAST.

- lib/CXGN/People/Roles.pm
- lib/SGN/Controller/AJAX/People.pm
Description 
if users have disabled='t' or censor=1 they should not be shown in the manage user page or the user search
Checklist 
> do not show users on manage users that have been censored

- lib/CXGN/BrAPI/v2/ObservationUnits.pm
- lib/CXGN/List/Validate/Plugin/Traits.pm
- sgn.conf
Description 
1. Update list validation to allow observationVariable names without CO number
2. The call to refresh the mat. view was changed from asynchronous to synchronous to avoid potential race conditions.
_**Depends on https://github.com/solgenomics/sgn/pull/4632 being merged first!**_
Checklist 
> Update list validation to allow variable names without CO number

- lib/CXGN/BrAPI/v2/Observations.pm
Description 
Observations (phenotypic data) were missing from exports when BreedBase was the backing service. The cause was that the Observations search endpoint wasn't returning any data. BreedBase was interpreting the `trialDbIds` sent in the search POST body as both Trial and Study DbIds. This is likely due to conflicting terminology between BrAPI and BreedBase: https://gist.github.com/mlm483/b5e1590fdedd0c3dcd116bd29ef19423.
1. Upload an experiment with Observations (phenotypic data) to a BreedBase-backed program.
2. Download the experiment's Observation dataset.
3. Check that downloaded file has Observations (phenotypic data).
**Alternatively:**
1. Use this query to find valid folder and program DbIds:
```sql
SELECT …
```
> fix BrAPI observation search endpoint

- db/00182/UpdateNdGeolocationDbxrefTablePermissions.pm
Description 
Fixes issue with nd_geolocation_dbxref doesn't have permissions. So it adds nd_geolocation_dbxref web_usr permmisions
Closes #4733 
Checklist 
> Add nd_geolocation_dbxref web_usr permmisions

- lib/CXGN/Stock/Seedlot/ParseUpload/Plugin/SeedlotHarvestedXLS.pm
- lib/CXGN/Stock/Seedlot/ParseUpload/Plugin/SeedlotXLS.pm
Description 
This adds a check to the seedlot upload validation that returns an error if the seedlot name already exists as a stock name (excluding existing seedlots, which would be updated).
This addresses the immediate problem in Issue #4138
Checklist 
> Seedlot Upload: check if name already exists as any stock

- js/source/legacy/tools/LabelDesigner.js
- lib/CXGN/List.pm
Description 
Two small fixes to support Public Lists in the label designer when sorting labels by trial layout:
- recognize the data type of 'Public Lists' in addition to 'Lists'
- in `CXGN::List`, allow the `exists_list` function to return information for public lists
Checklist 
> Label Designer Sorting: support Public Lists

- mason/tools/fieldmap.mas
Description 
-- remove duplicate d3 loading from fieldmap mason template and fix conflict with a d3 version loaded in fieldmap.js
Checklist 
> remove d3v4 lfrom fieldmap.mas

- lib/SGN/Controller/solGS/Utils.pm
- mason/solgs/search/selection_populations.mas
Description 
-- bring back generic_message func, was removed accidentally.
-- fixes private analysis results display breakage when user is not logged in.
Checklist 
> bring back generic_message func, removed accidentally

- bin/replace_plots.pl
Description 
With this change plot_id is not required field anymore, just have to add plot name (it is easier to find).
Checklist 
> Adapting replace_plots.pl to get plot id

- lib/CXGN/Phenotypes/ParseUpload/Plugin/PhenotypeSpreadsheetSimple.pm
- mason/breeders_toolbox/upload_phenotype_spreadsheet.mas
Description 
This PR allows the first column of the "simple" phenotype upload to be one of any:
- observationunit_name
- plot_name
- subplot_name
- plant_name
- observationUnitName
- plotName
- sublotName
- plantName
We frequently have some users trying to upload data with 'plot_name' or copying the column from some of the downloads on the website, which may use 'observationUnitName'.  The upload will accept any of these as a valid first column header.
Checklist 
> Phenotype Upload: additional acceptable column headers

- lib/SGN/Model/solGS/solGS.pm
- lib/solGS/queryJobs.pm
Description 
-- extract accession ids from Dataset's retrieve_accessions query result
Checklist 
> make get_genotypes_from_dataset return accession ids

- mason/breeders_toolbox/create_seedlots_from_trial_dialogs.mas
Description 
Adds `{plot_name}` as a possible variable for the seedlot name template
Fixes #4843 
Checklist 
> Create Seedlot From Trial: add plot_name to name template

- js/source/legacy/brapi/BrAPIFieldmap.js
- mason/tools/fieldmap.mas
Description 
This speeds up the process for updating the plot coordinates in the Geo Field Map tool by submitting all of the plots in one BrAPI call instead of one at a time.  Since the mat views are refreshed after updating an observationunit, it was taking about ~1 min per plot for the update to complete.  Now, the mat views are refreshed just once after all of the obervationunits have been updated.
It also adds some UI feedback for when the plots are saving and adds a help section with more detailed instructions.
Checklist 
> Geo Field Map: Speed and UI Improvements

- lib/CXGN/BrAPI/v2/Observations.pm
- lib/CXGN/Trial/TrialLayoutSearch.pm
Description 
This stops the BrAPI `/observations` from filtering out trait values of 0.
This fixes #4851, but there might be other places where 0s are being filtered out...
Checklist 
> BrAPI Observations: include trait values of 0

- mason/breeders_toolbox/create_seedlots_from_trial_dialogs.mas
Description 
This fixes a bug that was preventing the Create Seedlots from Trial tool from continuing if the trial has no trait data.
Fixes #4431
Checklist 
> Create Seedlots from Trial: fix bug if no trait data

- lib/SGN/Controller/AJAX/TrialMetadata.pm
Description 
This fixes the Content-Disposition header for the plot order download.
The download file name will now include planting/harvest and the trial id(s) in the name.
Fixes #4907 
Checklist 
> Plot Order Download: fix content-disposition header

- lib/CXGN/Trial/Folder.pm
Description 
CXGN::Trial::Folder has a 'breeding_program' attribute that is required by some BrAPI calls.
A trial can be located in a folder and a folder will have a project relationship to the breeding program it is within.  This is used to set the 'breeding_program' attribute of the folder.
However, if a trial is not within a folder (it exists directly under the breeding program), then the "folder" is the breeding program itself.  The problem is the breeding program folder does not have the 'breeding_program' attribute set.  This fix sets the breeding program of a folder of type 'breeding_program' as itself.
Checklist 
> Trial Folder: set breeding program for folders of type 'breeding_program'

- js/source/legacy/brapi/BrAPIFieldmap.js
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
This adds some improvements to the Geo Field Map:
- allow missing plots (plots with no geo coordinates)
- display a list of plots with missing geo coordinates
- add ‘viewOnly’ mode that disables the edit features (when just viewing the map on the trial detail page)
- add loading banner when loading plots via BrAPI
- hide regular field map legend when viewing the geo field map or phenotype heatmap
[Screencast from 05-01-2024 02:20:03 PM.webm](https://github.com/solgenomics/sgn/assets/7526014/3bb7c62a-ecd6-48aa-8793-93ab43a12921)
Checklist 
> Geo Field Map improvements

- lib/CXGN/Trial/TrialDesign/Plugin/Westcott.pm
Description 
-- the devtools package is not used in the trial designs. So not required to load it.
-- pass unit tests for TrialCreate.t and TrialForCrossesFamilyNames.t
Checklist 
> remove loading of devtools R package...not necessary

- .github/workflows/test.yml
- .github/workflows/test_static.yml
- js/install_node.sh
- js/package.json
- t/selenium2/03_dataset/dataset.t
fix dependabot error by changing  jsdom package from v13 to v16
changed action/checkout from v2 to v4 may fix random crash in dataset.t
Checklist 
> fix for dependabot

- js/source/legacy/CXGN/BreedersToolbox/UploadTrial.js
- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
- lib/CXGN/Trial/ParseUpload/Plugin/TrialExcelFormat.pm
- lib/CXGN/Trial/TrialDesignStore/PhenotypingTrial.pm
- lib/SGN/Controller/AJAX/Trial.pm
- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
- t/unit_fixture/CXGN/Trial/ParseUpload.t
- t/unit_fixture/CXGN/Uploading/TrialUpload.t
Description 
This updates the trial upload templates to allow for flexible column headers:
- only the required columns need to be included
- optional columns can be added as needed
- columns can be in any order
It also adds support for an additional `entry_number` column which will assign entry numbers to accessions for the trial.  (Entry numbers were previously added with PR #3770 as a separate upload).
Checklist 
> Single/Multi Trial Upload: flexible headers & entry numbers

- lib/SGN/Controller/AJAX/Stock.pm
Description 
The stock property autocomplete on the stock search page essentially crashes because sometimes millions of rows are returned. Limiting autocomplete to 100 rows.
Checklist 
> limit stock property autocomplete to 100 lines in stock search

- js/source/legacy/tools/LabelDesigner.js
- lib/SGN/Controller/AJAX/LabelDesigner.pm
- t/lib/SGN/Test/WWW/WebDriver.pm
- t/selenium2/tools/label_designer.t
Description 
This adds accession synonyms as a possible label property when the data source is a list of accessions, a single field trial, or a list of field trials.
It also adds the `wait_for_working_dialog` function to the `SGN::Test::WWW::WebDriver` class that can be used to pause a selenium test to wait for the working dialog to be dismissed (rather than setting an arbitrary sleep time).
Fixes #4964 
Checklist 
> Label Designer: add synonyms

- lib/CXGN/File/Parse/Plugin/Excel.pm
Description 
This fixes a bad bug in the generic excel file parser that could result in a previous column's value being assigned to another column!
Checklist 
> Generic Excel File Parser: fix cell value assignment

- lib/SGN/Controller/AJAX/Stock.pm
Description 
This fixes the pedigree string displayed in the pedigree tool when great-grandparents is selected
Fixes #5054 
Checklist 
> Fix pedigree string when using great grandparents

- js/build.webpack.config.js
- js/package.json
dependabot "requirejs" vulnerability - update version
core-js@2 no longer maintained, used by babel
deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. 
babel/polyfill deprecated - function replaced by core-js@3
deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
Checklist 
---------------------------------------------------------------------- …
> upgrade packages to fix warnings

- lib/SGN/Controller/AJAX/Trial.pm
Description 
This quotes the parameters to the `upload_multiple_trial_design.pl` script so it doesn't break when parameters have spaces.
Fixes #5082 
Checklist 
> Multi Trial Upload: quote parameters to upload script

- lib/CXGN/Phenotypes/Search/Native.pm
Description 
This updates the Native phenotype search to include all rows when one or more traits are selected.  Before, if a trait was used in the filter, the search would only include rows that had an observed value for that trait.  Now, rows without a value for that trait will also be included (which is what the MatView search returns).
Fixes #5084 
Checklist 
> Native Pheno Search: include missing data when trait is selected

- lib/CXGN/Stock/Search.pm
Description 
This update changes the CXGN::Stock::Search->search() function when filtering by stockprop values.  The original search used the materialized_stockprop table which did not include the additional stock props added in the `editable_stock_props` key in the local config file.  The search now uses the native stockprops table for the search, so is no longer limited to the hard-coded stock props in the mat view.
This is used by the advanced search (search by another property) feature on the accession search page.
Fixes #3653
Fixes #3284
Checklist 
> Accession Search: Fix stock prop advanced search

- lib/SGN/Controller/AJAX/MixedModels.pm
Description 
fixes #5059 
Checklist 
> fix run_model invocation in mixed model ajax so that it works with non-default options as well.

- js/source/entries/wizard.js
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/breeder_search_page.mas
Wizard currently filters genotype data by markerset
These changes allow it to also filter by list of markers
> wizard add marker filter

- mason/breeders_toolbox/trial/trial_details.mas
Description 
This preserves line breaks in the trial description box on the trial detail page
Checklist 
> Trial Detail Page: preserve line breaks in trial description

- lib/CXGN/Trial/TrialDesign/Plugin/greenhouse.pm
Description 
This removes a sort on the stock list that is causing plants in greenhouse trials to be allocated to the wrong stocks during trials design.
Closes #5080
Checklist 
> Fix plants being allocated incorrectly in greenhouse/nursery trial design

- js/source/legacy/solGS/cluster.js
- js/source/legacy/solGS/kinship.js
- lib/SGN/Controller/solGS/Feedback.pm
Description 
-- fixes loading issue for kinship and cluster plots from results url. Users following the link to results page from the email sent to them had to click run analysis again to view the output plot. Now, results are automatically loaded.
Checklist 
> fix kinship and cluster result load from result url

- lib/CXGN/Stock.pm
Description 
When two stocks have the same dbxref (in the table stock_dbxref) then the transfer of the dbxrefs to the other stock will violate a unique constraint on that table. The fix includes a check if they have the same dbxrefs and if present, skips the merge of the dbxrefs 
Checklist 
> fix an issue in the stock merge function

- lib/CXGN/Stock/Seedlot.pm
Description 
This fixes the Seedlot search when filtering by either count or weight by filtering out NAs and then casting the stockprop.value to numeric.
Fixes #5127 
Checklist 
> Seedlot Search: fix filter by count or weight

- mason/breeders_toolbox/trial/create_datacollector_dialog.mas
- mason/breeders_toolbox/trial/create_spreadsheet_dialog.mas
Description 
This improves an error message when creating a phenotype spreadsheet/datacollector file and the user hasn't selected a trait list first.
Fixes #5132 
Checklist 
> Create pheno files: show error message if no trait list is selected

- mason/breeders_toolbox/add_seedlot_dialogs.mas
Description 
Gives user an error message if they enter non-numeric values in the seed amount or weight fields, rather than allowing the seedlot to be created.
Closes #5149
Checklist 
> Add extra checks for non-numeric values in weight and count fields during seedlot creation

- bin/load_genotypes_vcf_cxgn_postgres.pl
Add checks for protocol and markers during VCF upload.
These are the same test used in the web based upload
If new markers are loaded into an existing protocol they will not be available for download. The upload should fail if the markers are not defined.
Checklist 
> add protocol checks for vcf upload using scripts

- js/source/legacy/solGS/cluster.js
Description 
Code for display of static dendrogram plot was lost during refactoring to make  k-means plot interactive. This brings back display of static hierarchical clustering plot.
Checklist 
> display static hierarchical clustering plot

- mason/tools/available_seedlots.mas
…toggled, all checkboxes in the open available seedlots modal are selected/deselected. List creation works. Disabled checkboxes are ignored.
Description 
Added a javascript function to enable users to select/deselect all available seedlots in the available seedlots modal. Disabled seedlots are ignored. Works with list creation. 
Checklist 
> Enable select all seedlots in available seedlots dialog

- lib/SGN/Controller/Dataset.pm
…erver error message
Description 
Solves issue #5183 by checking to see if missing dataset ID propagates error upward. Missing dataset ID requests are met with a message saying the dataset does not exist. 
Checklist 
> 5183 Viewing page for deleted dataset gives server error

- lib/CXGN/Stock.pm
- lib/SGN/Controller/AJAX/Stock.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/breeders_toolbox/accessions/find_trials_by_accessions.mas
- mason/page/detail_page_2_col_section.mas
- mason/stock/index.mas
- mason/stock/trials.mas
Description 
Split the experiment usage table in the accessions detail page into two tables: one that shows field trials and another that shows stored analyses using this accession. Attempting to use an analysis ID to go to a trial detail page now redirects to the analysis detail page. The field trials in common table in the manage accessions page now makes stored analyses distinct. They are labeled and colored for clarity. 
Checklist 
> 5022 show stored analysis

- lib/SGN/Controller/Analysis.pm
Description 
Added an eval statement to catch server error when analysis_id is missing. Displays a clean info message to user. 
Checklist 
> Fix server error on missing analysis ID

- js/source/legacy/solGS/pca.js
Description 
-- fixes pca analysis arguments parsing issue in pca results pages. 
Checklist 
> fix pca analysis args parsing issue in pca results page

- lib/CXGN/Stock/Seedlot.pm
Description 
This fixes a subquery in the Seedlot Trial usage filter.
It was missing stocks (plots, subplots, plants) from a trial if there were no traits observed for that stock.
Checklist 
> Seedlot Trial Filter: fix query to get stocks in trial

- js/source/legacy/CXGN/BreedersToolbox/UploadPhenotype.js
- lib/CXGN/Phenotypes/ParseUpload/Plugin/PhenotypeSpreadsheetSimple.pm
- lib/CXGN/Phenotypes/ParseUpload/Plugin/PhenotypeSpreadsheetSimpleGeneric.pm
- lib/SGN/Controller/AJAX/PhenotypesUpload.pm
- mason/breeders_toolbox/upload_phenotype_spreadsheet.mas
- t/unit_fixture/CXGN/Uploading/Phenotype.t
- t/unit_fixture/CXGN/Uploading/Phenotype_with_multi_categories.t
Description 
Add a generic file parser plugin for the simple phenotype observations spreadsheet
Checklist 
> Generic Simple Phenotype Observations Upload

- js/source/legacy/CXGN/BreedersToolbox/UploadTrial.js
- lib/CXGN/Trial/ParseUpload/Plugin/TrialExcelFormat.pm
- lib/CXGN/Trial/ParseUpload/Plugin/TrialGeneric.pm
- lib/SGN/Controller/AJAX/Trial.pm
- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
- t/data/trial/trial_layout_bad_accessions.csv
- t/data/trial/trial_layout_example.csv
- t/data/trial/trial_layout_example_flexible.csv
- t/data/trial/trial_layout_example_with_management_factor.csv
- t/data/trial/trial_layout_with_seedlot_example.csv
- t/unit_fixture/CXGN/Trial/ParseUpload.t
- t/unit_fixture/CXGN/Uploading/TrialUpload.t
Description 
- Add a generic file parser plugin for the Single Trial upload
- Remove the usage of the iFramePostForm plugin and use the standard jQuery ajax function instead.
- Fix the single trial upload tests (changes row indices from 0-based to 1-based)
- Add tests for CSV uploads
Checklist 
> Generic Single Trial Upload

- lib/CXGN/BrAPI/v2/ObservationUnits.pm
- mason/tools/graphicalfiltering/index.mas
Description 
Updates graphical filtering tool add to list feature to dynmically retrieve index of the column in the table that contains accession names.
closes #5253
Checklist 
> Fix bug in graphical filtering tool add to list 

- lib/SGN/Controller/AJAX/PhenotypesUpload.pm
Description 
This wraps the verify and store functions of PhenotypesUpload in a try/catch block to return uncaught error messages to the user.
Checklist 
> Store Phenotypes: wrap verify & store in try/catch

- mason/stock/index.mas
Description 
Replaces the QR code in the stock details section of accession page with the first uploaded image of the accession. Also adds a button to show and hide the QR code above the image.
#5250 
Checklist 
> Display accession image

- lib/SGN/Controller/Analysis.pm
Description 
--fixes an issue accessing analysis object instantiated in an eval block.
Checklist 
> declare analysis object before eval block

- js/source/legacy/CXGN/List.js
- mason/site/list.mas
- t/selenium2/01_list/list_groups.t
Description 
This adds some improvements to the List Manager Dialog:
- Add some filter options to make it easier for users to find a list they're interested in.  You can now filter by list data type and toggle the display of the autocreated accession lists (these tend to pollute the table of lists if the user has done a lot of uploads).
- It retains the current page and sorting column when the table is refreshed after an event (ie, making a list public)
- Updates the function for combining 2 or more lists.  You can now combine list items from multiple lists into a new list using a union or intersection operation.
- It also fixes a long-standing bug when selected lists in the group column after the page size has changed
Fixes #2230 …
> List Manager Improvements

- js/source/entries/mixedmodels.js
- lib/CXGN/Dataset.pm
- lib/SGN/Controller/AJAX/Dataset.pm
- mason/analyses/analysis_details.mas
- mason/analyses/model_details.mas
- mason/dataset/index.mas
- t/selenium2/breeders/breeder_search.t
Description 
Stored analyses that use a dataset will now be listed on the dataset details page. Likewise, the stored analysis details page now links to the dataset details page. 
#5154 
Checklist 
> Show analyses on dataset details page

- mason/breeders_toolbox/upload_nirs_spreadsheet_dialogs.mas
- mason/tools/high_dimensional_phenotypes/upload_high_dim_spreadsheet_dialogs.mas
- mason/tools/nirs/nirs_analysis_train_dialogs.mas
Description 
Fixes #5278 
Checklist 
> Adding new NIRS analyzer FTIR6X

- sgn.conf
Description 
The brapi_require_login config key is duplicated in sgn.conf which may cause issues
Checklist 
> remove duplicate key from sgn.conf (brapi_require_login)

- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/trial/trial_entry_numbers.mas
- mason/breeders_toolbox/trial/trial_entry_numbers_upload_dialog.mas
Description 
The entry number file that can be downloaded from the trial detail page is an xlsx file, but was erroneously coded as being xls. This led to strange errors when opening the file in Excel. 
This pull request adjusts the file format to the correct xlsx format.
It also adds the ability to delete the entry numbers from the trial, for curators.
fixes #5325
Checklist 
> fix the download format of the Entry List xlsx file.

- bin/delete_nd_experiment_entries.pl
- bin/extract_pheno_zeros.pl
- lib/CXGN/File/Parse.pm
- lib/CXGN/File/Parse/Plugin/Plain.pm
- lib/CXGN/Phenotypes/ParseUpload/Plugin/DataCollectorSpreadsheet.pm
- lib/CXGN/Phenotypes/ParseUpload/Plugin/PhenotypeSpreadsheetCSV.pm
- lib/CXGN/Phenotypes/ParseUpload/Plugin/PhenotypeSpreadsheetSimpleGeneric.pm
- lib/CXGN/Phenotypes/StorePhenotypes.pm
- lib/CXGN/Project.pm
- t/data/fieldbook/fieldbook_phenotype_file.csv
- t/lib/SGN/Test/Fixture.pm
- t/test_fixture.pl
- t/unit_fixture/CXGN/Uploading/Phenotype.t
Description 
fixes #5328
Checklist 
> the value zero is not stored correctly in certain phenotype uploads

- mason/index_logged_in_user.mas
Description 
Replace the [deprecated center tag](https://www.w3schools.com/tags/tag_center.ASP) with a div and remove an unused/unclosed table.
Checklist 
> Personalized Homepage: replace center tag, remove unused table

- lib/CXGN/Stock/ParseUpload/Plugin/AccessionsGeneric.pm
Description 
Add a check to the Accession upload to look for existing stock names that are not an accession and return an error message if any are found.
Fixes #5371 
Checklist 
> Accession Upload: check for existing non-accession stocks

- lib/SGN/Controller/AJAX/Search/Image.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/trial.mas
- mason/image/plot_images.mas
- mason/page/detail_page_2_col_section.mas
- t/unit_mech/AJAX/TrialImages.t
- t/unit_mech/AJAX/_BrAPIv2_phenotyping.t
Description 
Adds an image section to the trial details page that displays all of the images from every plot associated with the trial
Closes #5276 
Checklist 
> Add image section to trial details page

- lib/SGN/Controller/AJAX/Search/Image.pm
- mason/image/plot_images.mas
- mason/search/images.mas
- t/unit_mech/AJAX/TrialImages.t
Description 
Change ajax requests to image_search method to POST to fix errors when sending many params
Checklist 
> Change image search requests to POST

- mason/breeders_toolbox/manage_phenotyping.mas
On the manage phenotyping table, the delete button does not work on other pages than the first, presumably because these buttons represent dynamically generated items, which need to be handled using the ".on" function
Fixes #5344
Description 
Checklist 
> detect click event on a dynamically generated entry

- js/source/modules/wizard-search.js
- mason/breeders_toolbox/breeder_search_page.mas
- static/css/wizard.css
- t/selenium2/breeders/breeder_search.t
Description 
This expands the search filter in each column of the Search Wizard from a single-line text input to a multi-line textarea, where matches are found for each line of input - useful for filtering by multiple items or pasting in a list of items.
It also adds a "Contains" vs "Exact" match type.  Contains (the default and original behavior) will find matches the contain the case-insensitive search term in the database term and Exact will find an exact case-insensitive match.  For example, if the search term is "BP25-123", a "contains" match will match to "BP25-123" and "BP25-123-A" while an "exact" match will only match to "BP25-123".
Here's a demo:
https://github.com/user-attachments/assets/9bca6270-07b0-4e51-a9d8-1f2ec3afc813 …
> Search Wizard: multi-line filter

- lib/SGN/Controller/AJAX/User.pm
- t/unit_mech/AJAX/Login.t
> fix a missing constructor name that caused certain password resets to fail.

- mason/stock/index.mas
Description 
This moves the no accession image message out of the img tag so that an image icon is no longer displayed when there are no images
Fixes #5410 
Checklist 
> Move 'no accession image to display' message out of img tag

- lib/CXGN/Trial/FieldMap.pm
Description 
has indents that are too large and not standard (4 spaces)
Checklist 
> fix indentation in CXGN::Trial::FieldMap

- db/00190/AddOrganismsToMaterializedview.pm
- js/source/entries/wizard.js
- lib/SGN/Controller/AJAX/BreederSearch.pm
Description 
Fixes #5374 
Checklist 
> adding organisms to search wizard

- R/mixed_models_sommer.R
- R/mixed_models_spl2D.R
- lib/CXGN/MixedModels.pm
- lib/SGN/Controller/AJAX/MixedModels.pm
- mason/tools/mixedmodels.mas
- t/unit/CXGN/MixedModels.t
> Add Spatial correction to mixed model - sommer 

- lib/SGN/Controller/AJAX/ImageAnalysis.pm
- lib/SGN/Controller/ImageAnalysis.pm
- mason/tools/image_analysis.mas
- sgn.conf
Description 
Currently the image analysis options are hardcoded in the mason file and in the ImageAnalysis.pm class. This pull request makes it configurable in sgn_local.conf using the image_analysis_services key with the data string in JSON format.  Example is in sgn.conf.
Checklist 
> Make image analysis services parametrizable

- R/urdd_design.R
- js/source/legacy/CXGN/BreedersToolbox/AddTrial.js
- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignGeneric.pm
- lib/CXGN/Trial/ParseUpload/Plugin/TrialMetadataGeneric.pm
- lib/CXGN/Trial/TrialDesign.pm
- lib/CXGN/Trial/TrialDesign/Plugin/URDD.pm
- lib/CXGN/Trial/TrialDesignStore/PhenotypingTrial.pm
- lib/SGN/Controller/AJAX/Trial.pm
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
- mason/breeders_toolbox/trial/update_experimental_design_type.mas
- sgn.conf
Description 
Creates un-replicated trial design with diagonal checks. It uses R package FielDHub.
To test or run this design, you will need to synchronize your R_libs to ensure that the latest version of FielDHub is available in the environment: debian_bullseye_R4.4
Fixes #5417 
Checklist 
> Add an unreplicated design with diagonal checks.

- mason/breeders_toolbox/location_table.mas
- mason/site/header/head.mas
Description 
This adds an optional filter to the Manage > Locations page where a user can select a list of locations.  This will filter the displayed locations in the table and map.
It also restores the download buttons in the data table by using the non-minified jquery/databtables script in production.
Fixes #4990 
Checklist 
> Manage Locations: filter by list

- sgn.conf
Description 
This PR sets the default value for brapi_require_login to 1 in the sgn.conf file. It seems desirable to have this as the default now, since we are setting up more breedbase instances with data that needs to be private/protected.
Checklist 
> Set brapi_require_login to 1 by default

- lib/CXGN/Trial/ParseUpload.pm
- lib/CXGN/Trial/ParseUpload/Plugin/SamplingTrialXLS.pm
- lib/SGN/Controller/AJAX/SamplingTrial.pm
- lib/SGN/Controller/BreedersToolbox.pm
- lib/SGN/Controller/Root.pm
- mason/breeders_toolbox/manage_nirs.mas
- mason/breeders_toolbox/manage_samples.mas
- mason/breeders_toolbox/manage_transcriptomics.mas
- mason/breeders_toolbox/sampling_trials/create_sampling_trials_dialogs.mas
- mason/page/detail_page_2_col_section.mas
- mason/tools/nirs/manage_nirs_main.mas
- mason/tools/transcriptomics/manage_transcriptomics_main.mas
- sgn.conf
Description 
This pull request makes the list of acceptable/allowed tissue types for sampling trials configurable in sgn_local.conf using a key called sample_tissue_types. The list that was current up to this point (leaf, root, stem, seed, fruit, and tuber) is included in the sgn.conf and serves as a default if not overridden by the sgn_local.conf value.
Checklist 
> Configurable sampling trial tissue types

- js/build.webpack.config.js
- js/package.json
replace deprecated npm package uglifyjs-webpack-plugin with terser-webpack-plugin
this is used to minify JavaScript
gives smaller code download and better performance
Checklist 
- [ x] Refactoring only
> replace deprecated minify package

- lib/CXGN/Onto.pm
Description 
error in okra.breedbase 
No cvterm for composed traits, so has to be created from the post composing tool the first time a COMP trait is generated 
Checklist 
> create 'composed traits' cvterm if does not exist

- bin/upload_multiple_trial_design.pl
- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignGeneric.pm
- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
- t/selenium2/breeders/upload_multi_trial_file.t
Description 
This updates the multi-trial upload to allow crosses to be used instead of accessions.  The accession_name column can be changed to stock_name, cross_name or cross_unique_id and the validation will check the name of the stock against existing accessions and crosses.  Previously, the multi-trial upload only allowed accession names as the stocks in plots.
Checklist 
> Multi-Trial Upload: allow crosses

- mason/site/footer/body.mas
This pr will substitute version information from the config file for version information stuffed into environment variables during the build process. 
The issue with the config variable in sgn.conf was that the version is not available before all the commits are complete for a new version. Putting the version in sgn_local.conf is inconvenient because all sites would have to be updated every time. This solution avoids these problems.
Note: This feature depends on a modification in the Dockerfile, which sets the required environment variables during build time.
Closes #5002.
Description 
Checklist 
> fix version info in footer

- js/source/legacy/CXGN/List.js
- t/selenium2/01_list/list_groups.t
Description 
This updates the table of lists in the lists manager:
- Force date format (for all locales) to YYYY-MM-DD to enable logical sorting
- Sort the lists table by modified date by default
Fixes #5505
Checklist 
> List Manager: change date format to fix sorting

- lib/CXGN/Phenotypes/ParseUpload/Plugin/FieldBook.pm
Description 
Allow headers in fieldbook file to be in any order. Files exported from fieldbook now work with the uploader
Checklist 
> Flexible headers in fieldbook file upload

- lib/CXGN/List/Validate/Plugin/Traits.pm
- lib/CXGN/Phenotypes/StorePhenotypes.pm
Description 
This adds some improved suggestions for missing terms in the trait validation:
- When finding matching term for a missing term, only return matches that are variables
- When a missing term is not a variable, return suggestions that are variables related to the missing term
- Improves the error messages returned to the user on the observations upload workflow
Fixes #5608
Example Error Messages:
Checklist 
> Observation Upload: improve error messages

- mason/tools/image_analysis.mas
The link to the paper for that specific analysis is not appropriate for the generic image analysis page.
closes #5617.
Description 
Checklist 
> remove the link to the necrosis analysis

- lib/CXGN/List/Validate/Plugin/NotObsoletedAndObsoletedAccessions.pm
- lib/CXGN/Stock/ParseUpload/Plugin/TransgenicHistoricalDataGeneric.pm
> Allow obsoleted accessions to be included in transgenic historical data upload

- bin/load_images.pl
Description 
using the mapping file (-m option), a new optional column "cvterm" can be added that will link the cvterm to the image.
Checklist 
> link images to cvterms in load_images.pl

- js/source/legacy/CXGN/List.js
fix issue with response keys that may not be returned (undefined), causing an error in the list validation.
fixes #5690.
Description 
Checklist 
> fix list validation errors

- mason/tools/gcpc/index.mas
> fix link from GCPC tools to selection index tool by providing a semiabsolute url.
