- lib/CXGN/Trial/TrialLayout.pm
- mason/breeders_toolbox/trial.mas
> accessions and controls on trial detail page have links to their stock detail page

- lib/CXGN/Trial.pm
> sort by name instead of cvterm_id

- lib/SGN/Controller/AJAX/TrialMetadata.pm
Added ontology id to trait name in the Traits assayed section on Trial detail page
> add ontology id to trait name

- mason/chado/cvterm.mas
> Modified trait name in list

- lib/SGN/Controller/AJAX/PhenotypesUpload.pm
> log out error check

- js/solGS/combineTrials.js
- js/solGS/listTypeTrainingPopulation.js
- js/solGS/solGS.js
- lib/SGN/Controller/solGS/AnalysisProfile.pm
- lib/solGS/AnalysisReport.pm
-- provides informative feedback by email for job queuing failures, for some at least. 
-- fixes job queuing issue for single population training dataset creation.
> add informative feedback for job queuing failures..

- ontology/cxgn_units.obo
a generic unit ontology that can certainly be refined and expanded.
relates to issue #860
> Generic units ontology

- js/CXGN/BreedersToolbox/Accessions.js
> option to change all options at once in fuzzy search response

- ontology/cxgn_units.obo
> fixes to synonyms

- mason/site/toolbar/about.mas
- mason/site/toolbar/genomes.mas
- mason/site/toolbar/maps.mas
- mason/site/toolbar/search_menu.mas
- mason/site/toolbar/tools.mas
removed the links from the sgn toolbar, need to do the same from the other websites
> remove links to static pages from toolbar menu headers

- mason/homepage/affiliated_sites.mas
- mason/homepage/tomato_genome_release.mas
there was a problem with affiliated sites that was crashing sgn homepage
> fixes to affiliated sites

- lib/SGN/Controller/BreedersToolbox/Download.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- lib/SGN/Controller/ExpressionTool.pm
- mason/breeders_toolbox/trial.mas
- mason/breeders_toolbox/trial/export_trial_to_expression_atlas.mas
- mason/tools/expression/expression_atlas.mas
can provide a list of trials, traits, and accessions to filter down the dataset that is shown in expression atlas
> export to expression atlas works

- lib/SGN/Controller/BreedersToolbox/Download.pm
> combine accession uniquename with batch number for genotype downloads

- Build.PL
- lib/SGN.pm
- mason/site/header/head.mas
Please see this [issue](/solgenomics/sgn/issues/1083). To the best of my knowledge, no similar functionality exists yet.
> Added single-page CSS importing via Catalyst::Plugin::Assets functionality

- mason/homepage/github_pullrequests.mas
- mason/index.mas
Using the Github API, the 5 most recent pull requests are displayed on the homepage. This uses a mason component that can be loaded on any page.
> Display Recent Database Changes

- js/CXGN/List.js
- lib/SGN/Controller/AJAX/PhenotypesUpload.pm
- mason/breeders_toolbox/manage_plot_phenotyping.mas
This pull request adds option for a user to specify custom made list of traits to be used on the direct plot phenotyping page.
> Trait list option added to direct plot phenotyping page.

- mason/stock/index.mas
This pull request adds link for database direct plot phenotyping to stock pages for plots.
> Direct plot phenotyping link added to stock pages for plots.

- lib/CXGN/BrAPI/v1/Germplasm.pm
- lib/CXGN/BrAPI/v1/Studies.pm
- lib/CXGN/Stock.pm
- lib/CXGN/Stock/Search.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
- lib/SGN/Controller/AJAX/Stock.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- lib/SGN/Controller/StockBarcode.pm
> Pedigree download updated to include cross type and prevent parent switching

- lib/CXGN/Stock.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- t/unit_fixture/CXGN/Stock/Accession.t
> Fixes multiple population error and parent overwrite error in pedigree downloads

- lib/SGN/Controller/Pedigree.pm
> Fix to prevent pedigree and descendant graphs from getting stuck in infinite loops

- lib/SGN/Controller/StockBarcode.pm
Barcode printing was adjusted to fit the new sets of labels recently purchased by IITA.
> Adjusting barcode printing to fit 10 and 20 label printing per page.

- lib/CXGN/Trial/TrialDesign.pm
Modification done to plot names as requested by IITA.
> Plot names modified.

- lib/SGN/Controller/AJAX/BrAPIAndroidApp.pm
Added storage and retrieval functions for Android App to display available BrAPI databases.
> BrAPI Android App Functions

- lib/SGN/Controller/AJAX/TrialMetadata.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/breeders_toolbox/trial.mas
On cassavabase the trial detail page was slow to load because of the trial completion check. This was moved to AJAX.
> Trial Detail Page Loads Quicker

- lib/CXGN/Onto.pm
- mason/ontology/compose_trait.mas
> MatViews refreshed Asynchronously after Composed Traits are saved.

- lib/CXGN/QRcode.pm
- lib/SGN/Controller/Barcode.pm
- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
-fixes error with stock page barcode
-closes 2-D barcode file after generation
-remove field information checkbox
-improved retrieved accession query, specifying accession cvterm_id
> Improved barcode printing.

- lib/CXGN/Phenotypes/Search/Native.pm
Location id search should work with the new "complete" phenotype search
> Fixed pheno search

- db/00082/AddNewProjectType.pm
- system_cvterms.txt
Heterosis
Genetic Gain
Storage
Health Status
> Added requested project_types

- lib/SGN/Controller/AJAX/Search/Cross.pm
It fills up the error log and maxes out the VM disk space.
> Comment out Dumpers in cross search page. 

- lib/SGN/Controller/AJAX/Stock.pm
- mason/pedigree/stock_pedigree.mas
> adding female parent from stock page allows addition of cross_type info

- mason/help/contact.mas
After the contact form message is sent, a success or error message is displayed on the page.
For #1206
> Contact form success/error message

- js/CXGN/List.js
- lib/CXGN/Trial/Download/Plugin/ExcelBasic.pm
- lib/SGN/Controller/AJAX/List.pm
when choosing a list using listSelect function, available public lists are shown below the user's lists.
useful for creating a trial, creating trait file, creating phenotype spreadsheet, etc.
for #989
> Public lists available by default

- mason/breeders_toolbox/cross_wishlist.mas
also refeshes data when switch tab to prevent confusing buildup of data
> limit to 10 male per female

- js/CXGN/List.js
- mason/site/list.mas
Fixed a bug which caused multiple requests on list creation from the "Find synonyms" tool in the list managing modal.
> fixed bug which caused multiple requests on list creation

- js/CXGN/List.js
- lib/CXGN/BreedersToolbox/Accessions.pm
- mason/tools/available_seedlots.mas
Addresses bugs from comments (excluding synonym-search bug) on pull request #1282
> Bug fixes for Topic/accesions to seedlot tool

- lib/CXGN/Stock/Search.pm
- mason/search/stocks.mas
stock search allows 5000 results. slightly better query construction on stock search
> stock search improvement

- lib/CXGN/BreedersToolbox/Projects.pm
- t/unit_fixture/CXGN/BreedersToolbox/Projects.t
> Fixes location selects where locations showed up multiple times

- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
- mason/barcode/printer_settings.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
- remove plot name from 32A4 format.
> Pre-fill printer settings on barcode printing format selection.

- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/barcode/index.mas
- mason/breeders_toolbox/trial.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
Disable phenotype download link when phenotype is not uploaded for a trial.
> Disable phenotype download link

- js/CXGN/BreederSearch.js
- js/CXGN/BreedersToolbox/AddTrial.js
- js/CXGN/List.js
- mason/breeders_toolbox/selection_index.mas
> fixes duplicate list refresh buttons in add trial modal

- lib/SGN/Controller/AJAX/Cross.pm
cross wishlists for a single location are combined, keeping plots unque. all male plots included in germplasm info file. added timestamp and username to output files
> cross wishlist change

- lib/CXGN/Phenotypes/Search/Native.pm
- mason/breeders_toolbox/download.mas
download button was pointing to wrong form element
> fix manage download phenotypes

- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
- Implemented for Banana program use.
- Pre-fills printer settings on select of printing format.
- Optional field : 'Add text to label' could take location, trial name, year, etc.
> 20 sticker barcode labels per page.

- docs/README.md
Description 
See Title.
Checklist 
> Update docs/README.md with link to published docs

- lib/SGN/Model/solGS/solGS.pm
typo fix: write genotype values to genotype data file..
> typo fix: write genotype values..

- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
Description 
Adjusted to label printing material.
#1351
Checklist 
> Fix ncsu barcode printing format to label size.

- js/CXGN/Trial.js
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/breeders_toolbox/trial.mas
- mason/breeders_toolbox/trial/edit_trial_details_dialog.mas
Description 
Set default trial type for the trial.
Checklist 
> Set specified trial type in edit trial details dialog.

- lib/SGN/Controller/StockBarcode.pm
sorts plot and plant list by plot number before generating barcodes.
> Sort plot and plant list for barcode generation.

- lib/CXGN/Location.pm
- lib/SGN/Controller/AJAX/Locations.pm
- mason/breeders_toolbox/location_map.mas
Description 
Removes datasciencetoolkit calls to avoid mixed content error. Fixes checks in location object that prevent removal of some props.
closes #1369 
Checklist 
> Location adding and editing fixes

- js/CXGN/BreedersToolbox/AddMultipleTrial.js
- lib/SGN/Controller/AJAX/Trial.pm
Description 
Adds missing params and fixes return after one location in multilocation trial tool.
Closes #1382
Checklist 
> fix multi loc trial save errors

- mason/chado/relations.mas
Description 
fix  a comment that appeared on the UI
Checklist 
> fix comment that showed up on ui.

- js/CXGN/BreedersToolbox/AddMultipleTrial.js
- lib/SGN/Controller/AJAX/Trial.pm
Description 
reverts unnecessary multi-loc trial changes. closes #1402
Checklist 
> revert accidental multi-loc changes

- js/CXGN/List.js
Description 
fixes selected list id retrieval for batch functions in list manager
closes #1383 
Checklist 
> fix selected list id retrieval

- lib/SGN/Controller/Barcode.pm
- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
Description 
Enables user generate unique 32 barcodes per page.
Checklist 
> Option to print 32 unique barcode labels

- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
> Adjusted barcode top margin for IITA-3 printing format.

- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
Description 
This printing format is for testing barcode printing in Arusha.  
Checklist 
> Mobile printing barcode format.

- lib/SGN/Controller/Barcode.pm
- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
Description 
Generates crossing barcodes used in labeling crossing plots.
Checklist 
> crossing barcode format for banana program

- R/sgnPackages.r
> fix typo..

- lib/SGN/Controller/Barcode.pm
Description 
Checklist 
- [x ] The relevant issue has been closed.
> Fixed trial direct phenotyping barcode url bug.

- lib/SGN/Controller/StockBarcode.pm
> Fixed accession display on plot phenotyping barcode generation.

- lib/CXGN/Trial/TrialLayoutDownload.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/breeders_toolbox/genotyping_trials/detail.mas
Description 
closes #1447 
Checklist 
> fixes xls and csv layout download for genotyping plate

- cgi-bin/solpeople/account-confirm.pl
- cgi-bin/solpeople/new-account.pl
Description 
closes #1464 
Checklist 
> fix order and text of account confirm checks

- mason/barcode/index.mas
- mason/barcode/printer_settings.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
> fixed top margin for IITA barcode format. 

- ISSUE_TEMPLATE.md
Description 
Fixed Typo
Checklist 
> ISSUE_TEMPLATE Typo Fix

- lib/SGN/Controller/Barcode.pm
- lib/SGN/Controller/StockBarcode.pm
> Barcode cross format changes

- lib/SGN/Controller/Barcode.pm
- lib/SGN/Controller/StockBarcode.pm
> Encoded all field information into cross barcode format.

- lib/CXGN/BrAPI/v1/Phenotypes.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
Fixes BrAPI phenotype search parameters and updates it to account for the new columns in phenotype search.
Checklist 
> CXGN::BrAPI phenotype search fix

- lib/SGN/Controller/AJAX/Trial.pm
> Delete folder if multi-location trial fail to save.

- R/solGS/gs.r
- js/solGS/searchTrials.js
- js/solGS/solGS.js
- lib/SGN/Controller/solGS/solGS.pm
- lib/SGN/Model/solGS/solGS.pm
- lib/solGS/AnalysisReport.pm
- mason/solgs/search/solgs.mas
- mason/solgs/search/trait_search_form.mas
-- remove GS traits list index from search page
-- improves solGS homepage loading
-- remove trial combination match color code
-- add stringent filter for duplicate genotypes
> updates and fixes

- lib/SGN/Controller/StockBarcode.pm
> fixed geno barcode conflict.

- lib/CXGN/BrAPI/v1/Calls.pm
- lib/CXGN/BrAPI/v1/Germplasm.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
Adds the proposed BrAPI progeny call from plantbreeding/API#151
Checklist 
> BrAPI Progeny Call

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
Does proper check if trial has row and column number for plots.
Checklist 
> precheck row and column number

- lib/CXGN/Trial.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
> added username and timestamp to suppressed phenotypeprop row

- lib/SGN/Controller/StockBarcode.pm
> unify barcode top_margin name

- lib/CXGN/Phenotypes/TrialPhenotype.pm
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
> Create on the fly row and column numbers while displaying heatmap.

- mason/search/traits.mas
Description 
closes #1412
Checklist 
> add trait name and id joined with pipe to list

- lib/SGN/Controller/StockBarcode.pm
- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
> IITA-2 barcode format

- lib/CXGN/BrAPI/v1/Trials.pm
Description 
Speeds up trials query, and ensures it captures all breeding programs, all folders as trials, and all trials as studies.
closes #1579
Checklist 
> Update trials query

- lib/SGN/Controller/FieldBook.pm
Description 
file_id wasn't deleted from nd_experiment_md_files table.
Checklist 
> fixed fieldbook deletion bug

- lib/SGN/Controller/solGS/solGS.pm
-- fixes bug in multiple models page display
> fix trait name extraction..

- lib/SGN/Controller/solGS/solGS.pm
--create cache dir name for sites with no default genotyping protocol config var
> create cache dir name for sites with no default genotyping protocol

- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesExcelFormat.pm
- sgn.conf
> Make female plot and male plot as optional columns for cross upload

- ontology/cxgn_time.obo
> fix duplicate entries

- ontology/cxgn_time.obo
> set back hours to time of the year instead of time of the day

- ontology/cxgn_time.obo
> specify stage of collection

- mason/genomes/Nicotiana_benthamiana.mas
Description 
#1680 
Checklist 
> fix link for nicotiana bti page.

- mason/genomes/Capsicum_annuum.mas
Description 
A minor update to the pepper genome page
Checklist 
> added 10X pepper genome

- lib/CXGN/Pedigree/AddProgeny.pm
> Fix adding pedigree when adding progenies in cross

- lib/SGN/Controller/Locus.pm
Description 
https://github.com/solgenomics/sgn/issues/1392
Checklist 
> remove version numbers from locus name

- js/CXGN/BreedersToolbox/AddTrial.js
- lib/CXGN/Trial/FieldMap.pm
- lib/SGN/Controller/AJAX/Trial.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
- lib/SGN/View/Trial.pm
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
Description 
close #1639 
close #1673 
Checklist 
> Fix heatmap display for split-plot design trials.

- js/CXGN/BreedersToolbox/Crosses.js
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesExcelFormat.pm
- mason/breeders_toolbox/add_cross_dialogs.mas
- mason/breeders_toolbox/upload_crosses_dialogs.mas
Description <Improve cross upload>
Checklist 
> Improve cross upload

- db/00092/UpgradeGenotypeStorage.pm
> Patch to upgrade genotype storage

- ontology/cxgn_time.obo
Description 
shooting/flowering stage definition precised.
requested by Rhiannon Crichton
Checklist 
> refine flowering/shootong stage definition

- js/CXGN/BreedersToolbox/AddTrial.js
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
> Improve heatmap display speed.

- lib/CXGN/Trial.pm
> turn off debug

- js/workflow.js
Description 
adds ability to use selectors instead of Element objects in wf calls.
Checklist 
> Use selectors in Workflows

- mason/util/workflow.mas
Description 
Names where wrapping instead of truncating causing formating issues. This fixes that.
Checklist 
> fixed step name truncation

- db/00092/AddGenotypingTrialListCvterm.pm
- lib/CXGN/List/Validate/Plugin/GenotypingTrials.pm
- system_cvterms.txt
Description 
adds genotyping trial list type
closes #1711 
Checklist 
> adds genotyping trial list type and list validator

- lib/CXGN/Stock/ParseUpload/Plugin/AccessionsXLS.pm
- lib/CXGN/Stock/Seedlot/ParseUpload/Plugin/SeedlotInventoryCSV.pm
- lib/CXGN/Stock/Seedlot/ParseUpload/Plugin/SeedlotXLS.pm
- lib/CXGN/Trial/ParseUpload/Plugin/GenotypeTrialCoordinate.pm
- lib/CXGN/Trial/ParseUpload/Plugin/GenotypeTrialXLS.pm
- lib/CXGN/Trial/ParseUpload/Plugin/TrialExcelFormat.pm
- lib/SGN/Controller/AJAX/Pedigrees.pm
Description 
trims whitespace from identifiers in various uploads.
the downside is the file that was uploaded will still contain the whitespace in it.
closes #1677 
closes #1672 
Checklist 
> trim whitespace from uploads

- mason/chado/cvterm.mas
> cvterm accession already contains db_name

- js/brapi/PedigreeViewer.js
Description 
closes #1807 
Checklist 
> fixed pedigree loadtime

- R/solGS/combine_populations.r
fixes more than 2 trials combination issue..
> fix more than 2 trials combination issue..

- db/00094/AddGenotypingTrialprojectType.pm
Description 
Adds genotyping_trial project_type cvterm.
Checklist 
> genotyping trial project type

- cgi-bin/phenome/stock/stock_ajax_form.pl
> remove "name" field from stock page. Redundant to "uniquename"

- mason/locus/index.mas
- mason/locus/print_mrna_features.mas
> print feature sequences on locus page #1399

- PULL_REQUEST_TEMPLATE.md
> Add refactoring to checklist

- mason/site/footer/common.mas
> remove include intended for other branch for now.

- mason/brapiclient/home.mas
Description 
Add MGIS link to brapihome dropdown database list
Checklist 
> add mgis in brapi db list dropdown

- mason/brapiclient/home.mas
> speciy mgis to crop-diversity url

- mason/brapiclient/home.mas
> remove typo

- mason/brapiclient/germplasm_search.mas
> add mgis to brapi germplasm search

- mason/site/footer/common.mas
> fix commented out code.

- mason/breeders_toolbox/program/traits.mas
- mason/breeders_toolbox/program/trials.mas
> DbStats breeding program summaries

- lib/CXGN/Stock/Search.pm
Description 
Stock search connection to stock properties uses stock_id
closes #1919 
Checklist 
> Fixes error on stock search after editing a stock name

- js/brapi/BrAPI.js
Description 
BrAPI.js passes http auth credentials along
closes #1888 
Checklist 
> BrAPI pass credentials

- mason/search/traits.mas
Description 
Closes #1936 
Checklist 
> fix contact form link

- lib/SGN/Controller/solGS/solGS.pm
update phenotype data structure; filter out newly added metadata columns
> update phenotype data structuring..

- js/CXGN/BreedersToolbox/GenotypingTrial.js
- lib/CXGN/Trait/Search.pm
- lib/CXGN/Trial/ParseUpload/Plugin/GenotypeTrialCoordinateTemplate.pm
- lib/SGN/Controller/AJAX/GenotypingTrial.pm
- mason/breeders_toolbox/genotyping_trials/create_genotyping_trial_dialogs.mas
Description 
Can upload a CSV file with the following format:
Value | Column | Row | Identification | Person | Date
This is the default "Custom" template from Coordinate app
closes #1865 
Checklist 
> upload of coordinate custom genotyping trial template

- cgi-bin/phenome/stock/stock_ajax_form.pl
Description 
closes #1933 
Checklist 
> fix stock deletion

- lib/CXGN/BreedersToolbox/StocksFuzzySearch.pm
- lib/CXGN/Stock.pm
- lib/SGN/Controller/AJAX/Accessions.pm
- lib/SGN/Controller/Stock.pm
- mason/stock/additional_info_section.mas
- mason/stock/index.mas
Description 
closes #1970 
Checklist 
> fixes accession upload

- mason/breeders_toolbox/upload_locations_dialogs.mas
> fix typo in location upload form description.

- mason/site/toolbar/maps.mas
> add link to new cview on the maps toolbar menu

- db/00098/AddCrossingBlockTrialCvterm.pm
- system_cvterms.txt
> Add crossing_block_trial cvterm 

- lib/SGN/Controller/AJAX/BreedingProgram.pm
- mason/breeders_toolbox/program/traits.mas
> missing program_id var

- js/d3/graphers/stackedObservationPhenotypeHistogram.js
Description 
closes #1988
Checklist 
> Fix stacked histogram left axis

- mason/pedigree/stock_pedigree.mas
Description 
closes #1939
Checklist 
> Adds a loading indicator to the pedigree tree on the stock page

- lib/SGN/Controller/solGS/pca.pm
fix pca for list type population
> fix reference to wrong controller..

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
> use study variable brapi call for heatmap

- lib/CXGN/Trial/ParseUpload/Plugin/TrialExcelFormat.pm
Description 
During trial upload, new plot names must be unique against all other plots in the database, but not against all other stocks in the database.
Checklist 
> check only plot names

- lib/SGN/Controller/solGS/AnalysisProfile.pm
- lib/SGN/Controller/solGS/combinedTrials.pm
> fix function reference..

- sgn.conf
> removed duplicate slurm key

- mason/cookie_popup.mas
> change cookies_approved expire time to 1000000000

- mason/page/detail_page_2_col_section.mas
- mason/search/stocks.mas
- mason/search/stocks_graphicalfiltering.mas
Description 
Fixes stock search phenotypic graphical filtering tool
Checklist 
> fix stocks search graphical filtering

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
closes #2039 
Checklist 
> Improve HeatMap hover speed

- lib/CXGN/Trial/TrialDesignStore.pm
> Minor fixes to trial upload

- lib/SGN/Controller/solGS/solGS.pm
-- filter new metadata pheno columns
> update phenotype column filtering..

- lib/CXGN/Phenotypes/StorePhenotypes.pm
Description 
if value is 0, the trait checking will still check if it is a valid category.
Checklist 
> phenotype value checking

- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/trial/add_plants_per_plot.mas
> plant upload issue

- js/CXGN/BreedersToolbox/AddTrial.js
- lib/CXGN/Trial/TrialDesign.pm
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
> Alpha Lattice field map display

- lib/CXGN/Phenotypes/StorePhenotypes.pm
> fix trait check for null and 0

- lib/CXGN/Trial/TrialDesign.pm
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
- mason/breeders_toolbox/trial/trial_create_multiloc_dialogs.mas
> Fix custom plot numbering

- lib/CXGN/Trial.pm
> slightly faster trial deletion

- js/solGS/listTypeSelectionPopulation.js
- js/solGS/listTypeTrainingPopulation.js
- lib/SGN/Controller/solGS/AnalysisProfile.pm
- lib/SGN/Controller/solGS/List.pm
- lib/SGN/Controller/solGS/pca.pm
- lib/SGN/Model/solGS/solGS.pm
- lib/solGS/Cluster.pm
-- fixes list type genotype query
-- general code improvements
> fix list type genotype query;refactor

- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_genotrial_barcode.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
> Set fieldbook barcode format as default on barcode generation page.

- mason/barcode/index.mas
- mason/breeders_toolbox/trial/generate_genotrial_barcode.mas
- mason/breeders_toolbox/trial/generate_trial_barcode.mas
Description 
-fix barcode duplicate checkbox
-added links to label designer page to stock barcode generation dialogs
Checklist 
> Fix barcode page duplicate checkbox

- mason/projects/varitome/index.mas
> link to Tomato Analyzer download from the SGN ftp site

- t/unit_fixture/AJAX/BreedersToolbox/TrialMetadata.t
> fix trial metadata plot order test

- lib/CXGN/Trial/FieldMap.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
Replaces accessionName in plotName string when a plot accession is replaced using the fieldmap.
replaces accessionName in plotName string when a plot accession is re…
Checklist 
> replaces accessionName in plotName string

- lib/CXGN/List.pm
- lib/SGN/Controller/AJAX/IdentifierGeneration.pm
- lib/SGN/Controller/AJAX/List.pm
> ACAI Identifier Generation fix

- js/d3/graphers/stackedObservationPhenotypeHistogram.js
Description 
Fixed bug causing stackedObservationPhenotypeHistogram.js not to work.
closes #2170
Checklist 
> Added check for notes column

- R/solGS/phenotypic_correlation.r
- lib/SGN/Controller/solGS/Correlation.pm
- lib/SGN/Controller/solGS/Files.pm
- lib/SGN/Controller/solGS/solGS.pm
- lib/SGN/Model/solGS/solGS.pm
- lib/solGS/Cluster.pm
improves phenotype metadata handling
> fixes issues related to notes column addition

- mason/locus/index.mas
Description 
closes #2103 
Checklist 
> locus page edit button fix

- mason/image/display_image.mas
> remove html response alerts from image page

- lib/CXGN/Genotype/Search.pm
- mason/breeders_toolbox/genotyping_trials/create_genotyping_trial_dialogs.mas
> fixes cxgn genotype search

- lib/CXGN/Phenotypes/Search/MaterializedViewTable.pm
Description 
@afpowell if you can test this in the instance where it was an issue for you
closes #2182 
Checklist 
> removes generic newlines from phenotype download descriptions

- db/00103/FixTrialPluralTypes.pm
- mason/stock/index.mas
- system_cvterms.txt
Description 
Fixes stock detail page buttons
Adds a patch to fix #2223 
closes #2192 
Checklist 
> stock detail page buttons

- lib/CXGN/Genotype/StoreVCFGenotypes.pm
Description 
In Yam, multiple organisms are used often, so the load vcf code can accommodate this.
Checklist 
> VCF genotype storage

- mason/locus/index.mas
> fix link to new locus button

- js/CXGN/BreedersToolbox/Crosses.js
- js/CXGN/TrialTreeFolders.js
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesExcelFormat.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesSimpleExcel.pm
- lib/SGN/Controller/AJAX/Cross.pm
- mason/breeders_toolbox/add_cross_dialogs.mas
- mason/breeders_toolbox/cross/cross_properties_crossingtrial.mas
- mason/breeders_toolbox/cross/crosses_in_crossingtrial.mas
- mason/breeders_toolbox/cross/upload_update_crosses.mas
- mason/breeders_toolbox/upload_crosses_dialogs.mas
> Allow slash character for cross name and minor bug fixes related to cross

- ontology/cxgn_plant_level.obo
> add cycle level and main plant/tallest sucker

- lib/CXGN/Stock/Search.pm
Description 
closes https://github.com/solgenomics/sgn/issues/2271
Checklist 
> add synonyms to stock name search

- mason/image/embed_image.mas
Description 
Adds a mason template for embedding an image from the database.
Checklist 
> add a mason template for embedding an image stored in the database.

- lib/CXGN/Trial.pm
- mason/breeders_toolbox/genotyping_trials/detail.mas
- mason/breeders_toolbox/genotyping_trials/files_section.mas
- mason/breeders_toolbox/trial/upload_additional_file.mas
Description 
genotyping plate detail page has the same additional files section as the field trial detail page for uploading and sharing additional files.
closes #2256
Checklist 
> genotyping plate detail page has the same additional files section

- js/tools/LabelDesigner.js
> update help link for label designer

- lib/CXGN/Cross.pm
- lib/CXGN/Pedigree/AddCrossInfo.pm
- lib/CXGN/Pedigree/AddCrosses.pm
- lib/CXGN/Pedigree/AddProgeny.pm
- lib/CXGN/Stock/RelatedStocks.pm
- lib/CXGN/Stock/StockLookup.pm
- lib/SGN/Controller/AJAX/Cross.pm
- lib/SGN/Controller/Cross.pm
- t/unit_fixture/AJAX/Stocks/Related_stocks.t
> Changing stock_relationship cvterm for progenies from member_of to offspring_of

- db/00104/UpdateProgenyOffspringOfRelationship.pm
- lib/CXGN/Stock.pm
Description 
need to merge first topic/cross_issues @titima15 
Checklist 
> ok to merge Topic/stock population name

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
- fixed field map display for large studies
- sorted BrAPI study object for fieldMap display
Checklist 
> FieldMap Display for Large Studies: fixed page size limit and sorting of BrAPI object by plot number

- lib/SGN/Controller/Blast.pm
Description 
Fixes #2302.
Checklist 
> fix show and download links for matched BLAST sequence.

- lib/SGN/Controller/AJAX/Search/Trial.pm
- lib/SGN/Controller/AJAX/TissueSample.pm
Description 
Changes these download layout buttons to default look so that the link isn't so hard to read
Checklist 
> download layout buttons default look

- lib/CXGN/Location.pm
- lib/SGN/Controller/AJAX/Trial.pm
Description 
Fixes missing location get_prop function
Checklist 
> fix prop retrieval from location object

- lib/CXGN/BreedersToolbox/Projects.pm
Description 
Checklist 
We need a better way to handle utf8 on the Perl side.
> deal with utf8 encoded strings in the location data.

- lib/SGN/Controller/AJAX/TrialMetadata.pm
Description 
closes #2324 
Checklist 
> limit raised from 50 to 500 plants per plot

- lib/CXGN/People/Roles.pm
Description 
Checklist 
- [ x] Bug fix
> sort users by username

- lib/CXGN/BreedersToolbox/Projects.pm
- lib/SGN/Controller/BreedersToolbox.pm
- mason/breeders_toolbox/add_crossing_trial_dialogs.mas
Description 
fixes trial add and upload multi selects to show locations linked with more than 1 program.
Checklist 
> add separate method for retrieving locations by breeding program

- lib/SGN/Controller/AJAX/Trial.pm
> fix conflict

- js/source/entries/wizard.js
- js/source/modules/wizard-datasets.js
> fixes problem with fetch and with credentials not being sent

- README.md
> Update README.md - also add a link to the manual

- lib/CXGN/Genotype/ParseUpload/Plugin/GridFileIntertekCSV.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/IntertekCSV.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/VCF.pm
> Convert DS value to string

- lib/CXGN/List/Transform/Plugin/Accessions2AccessionIds.pm
Description 
Closes #2397
Checklist 
> streamline accession list transform 2 ids with fewer db queries

- R/solGS/combine_genotype_data.r
- R/solGS/combine_populations.r
- R/solGS/gs.r
-- adds option to calculate averages when modeling and adjusted means calc fails
-- requires new installation of phenoAnalysis R package (V. 0.3.3)
> add calcuate averages option when all modeling fails

- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/genotyping_trials/detail.mas
> "Check plate layout" link on genotyping plate detail page fixed

- lib/CXGN/Stock/Search.pm
- lib/SGN/Controller/AJAX/CrossWishlist.pm
- mason/breeders_toolbox/cross_wishlist.mas
Description 
Cross wishlist is pushed to ONA and works as it did previously.
Adds ploidy level and genome structure to "germplasm info" file.
closes #2484
closes #2281 
closes #2283 
Checklist 
> Cross wishlist push to ONA is working and changes made

- lib/SGN/Controller/AJAX/Stock.pm
Description 
The 'Find Trials in Common' function on `/breeders/accessions` was failing with an exception
Checklist 
> Find Trials in Common Bug

- ontology/cxgn_time.obo
> added pre and post flowering time for musa project

- lib/SGN/Controller/Static.pm
> link to solcode page

- lib/CXGN/Trial/TrialLayout.pm
- mason/breeders_toolbox/trial/add_tissue_sample_per_plant.mas
> Can create plant entries even if the plots are already linked to the genotyping plate

- lib/CXGN/Trial/TrialDesign.pm
Description 
Plot name  strcuture edits (replaced underscore by hyphen for custom plot (requested by IITA) 
Checklist 
> plot name format corrected

- mason/breeders_toolbox/trial/add_trial_treatment_dialogs.mas
> add new treatment types to mason template

- lib/SGN/Controller/Dynamic.pm
- mason/dynamic/solcyc.mas
Description 
fixes the page for solcyc
Checklist 
> Fix links for solcyc - add new page in mason (was cgi-bin), branch topic/fix solcyc links2

- lib/SGN/Controller/AJAX/Search/GenotypingProtocol.pm
> genotyping protocol search will show NA if no "file header information" available

- lib/CXGN/Genotype/Download/VCF.pm
> VCF format key for all genotyping protocols

- lib/CXGN/Stock/Seedlot.pm
> Updated cxgn_fixture.sql and tests pass

- db/00113/UpdateStockPropViewsUsePublic.pm
Description 
Includes updated cxgn_fixture.sql with working materialized_stockprop
closes #2573 
Checklist 
> Redefines materialized_stockprop to be in public schema

- lib/SGN/Controller/AJAX/BreedingProgram.pm
Description 
This fixes the problem with printing the accessions on the program page 
Checklist 
> sorting happens only at jquery dataTable

- lib/CXGN/Trial/TrialDesign.pm
- lib/CXGN/Trial/TrialDesign/Plugin/Alpha.pm
- lib/CXGN/Trial/TrialDesign/Plugin/CRD.pm
- lib/CXGN/Trial/TrialDesign/Plugin/Lattice.pm
- lib/CXGN/Trial/TrialDesign/Plugin/RCBD.pm
- lib/CXGN/Trial/TrialDesign/Plugin/splitplot.pm
Description 
Error associated to fieldMap colNumber fixed for all design.
Checklist 
> fix fieldmap colnumber

- lib/CXGN/Genotype/ParseUpload/Plugin/transposedVCF.pm
- mason/search/autohandler
- mason/search/phenotypes/autohandler
- mason/site/toolbar/search_menu.mas
Description 
The search menu and search buttons now match the links generally used in all the "Breedbase" sites mason. The solgenomics specific search menu and buttons are moved to the solgenomics mason repo https://github.com/solgenomics/solgenomics/commit/25a938ae5d15e4e2511140b5ae1dbfa4466f18b4
closes #2550 
Checklist 
> breedbase search buttons and search menu

- js/source/legacy/brapi/BrAPI.js
- js/source/legacy/brapi/PedigreeViewer.js
- js/source/legacy/d3/d3-pedigree-tree.js
Description 
Checklist 
- [ X] Bug fix
#2523
> tree draws just one parent instead the whole tree

- lib/SGN/Controller/AJAX/ImageAnalysis.pm
Description 
When saving image analysis result images, previously the  code required the input image to be linked to a project.
Now an input image only needs to be linked to a stock; however, input images can also be linked to a stock and a project.
Checklist 
> allow for non-project linked images in image analysis

- lib/CXGN/Phenotypes/ParseUpload/Plugin/PhenotypeSpreadsheetAssociatedImages.pm
> Prevent crash if missing values in Associate Image Phenotype Upload

- mason/tools/image_analysis.mas
Just added the Makerere AIR label under each of the image analysis options. 
Checklist 
- [ x] User-Facing Change
> added Makerere AIR lab label

- js/source/legacy/CXGN/BreedersToolbox/Crosses.js
- lib/Bio/GeneticRelationships/Pedigree.pm
- lib/CXGN/Pedigree/AddPedigrees.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesExcelFormat.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesSimpleExcel.pm
- lib/SGN/Controller/AJAX/Pedigrees.pm
- mason/breeders_toolbox/add_cross_dialogs.mas
- mason/breeders_toolbox/upload_crosses_dialogs.mas
- mason/breeders_toolbox/upload_pedigrees_dialogs.mas
- t/unit_fixture/CXGN/Pedigree/AddPedigrees.t
> Adding "sib" cross type for pedigree and cross

- mason/tools/image_analysis.mas
Necrosis detection documentation added
Checklist 
> added necrosis detection paper

- js/source/entries/sequenced_accessions.js
- mason/stock/sequencing_status.mas
> Removed alerts and fixed indentations

- js/source/legacy/CXGN/BreedersToolbox/AddTrial.js
- lib/CXGN/Trial/TrialDesign/Plugin/Augmented.pm
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
Description 
- FieldMap option added for augmented design.
- User choses layout format.
- uses for blockNumber as rowNumber
Checklist 
> Added fieldMap option for augmented design.

- mason/genomes/sequenced_accessions.mas
- mason/stock/sequencing_status.mas
Description 
closes #2633 
Checklist 
> load sequenced_accessions js for stock detail page sequencing_status.mas

- ontology/cxgn_time.obo
> added day 1 to day 365 in cxgn_time.obo

- js/source/entries/sequenced_accessions.js
- lib/CXGN/Stock/SequencingInfo.pm
- lib/SGN/Controller/AJAX/SequencedAccessions.pm
- t/unit_fixture/CXGN/Stock/SequencingInfo.t
Description 
This pull request improves the input form and fixes several bugs, removes debug pop-ups and adds tracking of the user who submitted the information. It only allows this user to delete the entry. The unit_fixture test was update, but this needs an integration test... 
Checklist 
> More sequenced accession fixes

- mason/stock/stockprops.mas
> Fixed stockprop deletion cancel button

- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/cross/crosses_in_crossingtrial.mas
> Option to add crosses in crossing experiment to list

- lib/SGN/Controller/Static.pm
Description 
The Static controller allows automatic forward to mason pages under /mason/pages, some may need a database handle which is provided here
Checklist 
> provide a schema object for static pages as some may use db access.

- docs/04_data_analysis_tools.md
fix text formatting and image filenames
> fix filenames

- lib/SGN/Controller/AJAX/HTMLSelect.pm
> set years for trial experiment from 70s to today

- js/source/legacy/CXGN/BreedersToolbox/Crosses.js
- lib/SGN/Controller/AJAX/Cross.pm
- t/unit_fixture/CXGN/Uploading/UploadAndAddCrossesCrossingtrial.t
Description 
closes #2713
Checklist 
> Update add crosses to use provided breeding program id

- lib/CXGN/Phenotypes/ParseUpload/Plugin/PhenotypeSpreadsheetNIRS.pm
- lib/CXGN/Phenotypes/StorePhenotypes.pm
Description 
Closes #2708 and #2709
Checklist 
> fix errors introduced from nirs branch

- bin/merge_stocks.pl
- lib/CXGN/Stock.pm
Description 
Closes #2723
Checklist 
> skip PUIs if merged stock will be deleted

- lib/SGN/Controller/AJAX/HTMLSelect.pm
Description 
fixes an issue that causes the site to crash because of a missing parameter (metadata_schema in brapi object)
Checklist 
> add missing parameter that causes site to crash.

- docs/03_managing_breeding_data/03_04.md
- docs/03_managing_breeding_data/03_09.md
- mason/breeders_toolbox/manage_genotyping.mas
- mason/breeders_toolbox/seedlots.mas
- mason/breeders_toolbox/upload_seedlots_inventory_dialogs.mas
- mason/fieldbook/home.mas
Description 
closes #2733
Checklist 
> update broken phenoapps links

- lib/SGN/Controller/BreedersToolbox.pm
- mason/breeders_toolbox/add_accessions_dialogs.mas
- mason/breeders_toolbox/manage_accessions.mas
> Fixes a bug that was crashing manage trials page

- mason/breeders_toolbox/add_accessions_dialogs.mas
Description 
Condition for if not logged in
#2753 
Checklist 
> condition if not logged in

- lib/CXGN/BreedersToolbox/Projects.pm
- lib/CXGN/Dataset.pm
- lib/CXGN/Dataset/Cache.pm
- lib/CXGN/Genotype/GRM.pm
> grm changes from manage_drone_time_series branch

- lib/SGN/Controller/AJAX/FieldBook.pm
Description 
Fixes t/unit_fixture/AJAX/Fieldbook.t
Checklist 
> default params. fixes test

- lib/CXGN/Genotype/StoreVCFGenotypes.pm
> fix missing var for genotype store

- bin/transfer_genome_project_info.pl
> fix genome info transfer script.

- lib/CXGN/Contact.pm
- sgn.conf
Description 
closes #2738
Checklist 
> refactor smtp conf variables to include layer option and to match package syntax

- lib/CXGN/Stock.pm
> fix update typo

- lib/SGN/Controller/AJAX/HTMLSelect.pm
Description 
There was a change to the CXGN::BrAPI in that it now requires the context.
closes #2790
Checklist 
> Fix traits search

- sgn.conf
> change cluster_host default from localhost  to empty string.

- lib/SGN/Controller/Static.pm
> path to tomato100 page

- lib/CXGN/BrAPI/v1/Studies.pm
- lib/CXGN/Phenotypes/ParseUpload/Plugin/Observations.pm
Description 
- Formatting studies dates according BrAPI specs #2850 https://github.com/PhenoApps/Field-Book/issues/121
- Allowing value of 0 in PUT studies observations #2749
Checklist 
- [x ] Bug fix
> Topic/brapi v1.3bugs

- mason/solgs/population.mas
> fix pop id arg

- R/heritability/h2_blup_rscript.R
> fixing Rplots.pdf error message on h2 tool

- R/heritability/h2_blup_rscript.R
> fixing h2 tool - Rscript

- R/heritability/h2_rscript.R
> fixing r script for h2 on details page

- mason/solgs/population.mas
> fix variable name

- R/stability/ammi_script.R
> fixing triplot issue on stability map

- lib/CXGN/ODK/Crosses.pm
> Fixed retrieving cross id, parents and field cross info for saving in musabase

- db/00122/UpdatePhenotypeJsonbTableMaterializedViewRowColumn.pm
Description 
The row and column data should be rank=0 instead of rank=1
Checklist 
> Fixes the row and column number data in the materialized view JSONb phenotype table

- lib/CXGN/ODK/Crosses.pm
> Summarize laboratory and nursery data from ona for crossing experiment detail page

- lib/CXGN/ODK/Crosses.pm
> Fixed a bug caused by inconsistent ona data structure

- lib/CXGN/ODK/Crosses.pm
> ONA bug fixes

- lib/SGN/Controller/StockBarcode.pm
> Add cross combination info on cross barcodes

- sgn_fixture_template.conf
Description 
add the cache_file_path property to the sgn_fixture_template.conf so that tests pass (ie, t/unit_fixture/CXGN/Dataset.t)
Checklist 
> add the cache_file_path property to the sgn_fixture_template.conf 

- mason/site/login_dialog.mas
> login prevent default in js

- R/heritability/h2_blup_rscript.R
Description 
- It was causing errors in production, I just changed the way to create a list of traits in R.
Checklist 
> fixing r script to calculate heritability

- R/heritability/h2_blup_rscript.R
Description 
It is just removing "limitsize" from png image.
Checklist 
> fixing image in h2

- R/heritability/h2_blup_rscript.R
Description 
Upgrading Rscript for heritability
Checklist 
> improving rscript for heritability

- R/heritability/h2_blup_rscript.R
- lib/SGN/Controller/AJAX/Heritability.pm
Description 
Adding another way to copy files to the temp folder.
Checklist 
> copying files to tempfile

- lib/SGN/Controller/AJAX/Stability.pm
Description 
-fixing script to generate tempfile properly.
Checklist 
> fixing tempfile to work with slurm

- R/heritability/h2_blup_rscript.R
- t/unit_mech/AJAX/Heritability.t
Description 
- fixing h2 test
- adding error message in Rscript for h2
Checklist 
> fixing h2 test and edding error message in Rscript

- js/source/legacy/CXGN/BreedersToolbox/Crosses.js
- lib/SGN/Controller/AJAX/Cross.pm
- mason/breeders_toolbox/add_cross_dialogs.mas
> Modified auto-generated cross unique id for polycross and modified add cross dialog

- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
Reinstate a deleted parameter:  context in Brapi
Checklist 
> fix bug - missing context in Brapi.pm

- js/source/modules/wizard-downloads.js
- lib/CXGN/Genotype/GRM.pm
- lib/CXGN/Phenotypes/PhenotypeMatrix.pm
- lib/CXGN/Trial/Download.pm
- lib/CXGN/Trial/Download/Plugin/TrialPhenotypeCSV.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
Description 
Fixes wizard GRM by simply using rrBLUP
Checklist 
> Wizard GRM fix

- lib/SGN/Controller/AJAX/Blast.pm
- lib/SGN/Controller/InSilicoPcr.pm
- mason/tools/blast/index.mas
- mason/tools/in_silico_pcr/in_silico_pcr.mas
Description 
Add word size option to blast and insilico PCR; remove matrix selection from insilico PCR; more insilico PCR to new blast+ codebase.
Checklist 
> fix BLAST for short sequences (and insilico PCR)

- js/source/legacy/CXGN/BreedersToolbox/FieldBook.js
Description 
fixed variable name that allows file creation from list (or selected trait)
Addresses issue #2945 
Checklist 
> Fix Field Book Trait File Creation from List

- js/source/legacy/CXGN/Blast.js
- mason/tools/blast/index.mas
Description 
pass word_size parameter to analysis.
Checklist 
> the word_size parameter was not passed to analysis... :-(

- lib/SGN/Controller/Static.pm
Description 
Adds an optional subfolder level to the static pages.
Checklist 
> add a subfolder level to the static pages.

- mason/breeders_toolbox/trial/add_trial_treatment_dialogs.mas
Description 
I am adding Irrigation and Drought as field management factors.
Checklist 
> Adding irrigation and drought as field management factor

- lib/CXGN/Phenotypes/ParseUpload/Plugin/ScioSpreadsheetNIRS.pm
Description 
It was creating creating hashes and variables using wrong data.
Checklist 
> fixing upload SCIO format for nirs

- lib/SGN/Controller/BrAPIClient.pm
- sgn.conf
Description 
Authorized clients not pulls from the config as JSON. Added the settings to the config.
Checklist 
> Move authorized clients to config file

- lib/CXGN/ODK/Crosses.pm
- lib/SGN/Controller/AJAX/Cross.pm
- mason/breeders_toolbox/cross/index.mas
> Retrieve and store hardening ids and openfield ids from ONA, and store openfield ids as progenies

- lib/CXGN/List/Validate/Plugin/Crosses.pm
- lib/CXGN/List/Validate/Plugin/Plots.pm
- lib/CXGN/List/Validate/Plugin/PlotsOrPlants.pm
- lib/CXGN/List/Validate/Plugin/PlotsOrSubplotsOrPlants.pm
- lib/CXGN/List/Validate/Plugin/PlotsOrSubplotsOrPlantsOrTissueSamples.pm
- lib/CXGN/List/Validate/Plugin/PlotsOrSubplotsOrPlantsOrTissueSamplesOrAnalysisInstances.pm
- lib/CXGN/List/Validate/Plugin/Populations.pm
- lib/CXGN/List/Validate/Plugin/Uniquenames.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossInfoExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesExcelFormat.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesSimpleExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/FamilyNameExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/ProgeniesExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/StoreExistingProgeniesExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/ValidateExistingProgeniesExcel.pm
- lib/CXGN/Stock/ParseUpload/Plugin/AccessionsXLS.pm
- lib/CXGN/Stock/Seedlot/ParseUpload/Plugin/SeedlotHarvestedXLS.pm
> Remove trailing spaces in strings

- lib/SGN/Controller/AJAX/BrAPI.pm
- sgn.conf
Also fixed the quotes in the sgn.conf file.
Description 
Checklist 
> Added 'Authorization' header

- js/source/legacy/CXGN/BreedersToolbox/GenotypingTrial.js
- mason/breeders_toolbox/genotyping_trials/create_genotyping_trial_dialogs.mas
- sgn.conf
> Moved genotyping facilities to conf file

- lib/SGN/Controller/BreedersToolbox.pm
- lib/SGN/Controller/Root.pm
- mason/breeders_toolbox/genotyping_trials/create_genotyping_trial_dialogs.mas
- mason/breeders_toolbox/genotyping_trials/trials.mas
- mason/breeders_toolbox/manage_genotyping.mas
- mason/breeders_toolbox/manage_samples.mas
- mason/breeders_toolbox/manage_upload.mas
- mason/help/workflow_guided/begin.mas
> Adding the list of genotyping facilities for Create Genotyping Trial dialog in controllers

- lib/SGN/Controller/BreedersToolbox.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- lib/SGN/Controller/Root.pm
- mason/breeders_toolbox/manage_projects.mas
- mason/breeders_toolbox/manage_upload.mas
- mason/breeders_toolbox/projects.mas
- mason/breeders_toolbox/trial.mas
- mason/breeders_toolbox/trial/add_trial_treatment_dialogs.mas
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
- mason/breeders_toolbox/trialtreefolders.mas
- mason/help/workflow_guided/begin.mas
- sgn.conf
> Make Field Management Factors configurable

- js/source/legacy/CXGN/BreedersToolbox/AddTrial.js
- lib/CXGN/Project.pm
- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
- lib/CXGN/Trial/ParseUpload/Plugin/TrialExcelFormat.pm
- lib/CXGN/Trial/TrialDesignStore/AbstractTrial.pm
- mason/breeders_toolbox/trial/trial_treatments.mas
Description : storing field management type and field management date when creating new trial and fixing experimental design section in field management factor detail page 
Checklist 
> Field Management Factor

- mason/breeders_toolbox/trial/edit_trial_details_dialog.mas
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
> adding 4.8 as plot width

- js/source/legacy/CXGN/BreedersToolbox/AddTrial.js
- lib/SGN/Controller/BreedersToolbox.pm
- lib/SGN/Controller/Root.pm
- mason/breeders_toolbox/manage_projects.mas
- mason/breeders_toolbox/manage_upload.mas
- mason/breeders_toolbox/projects.mas
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
- mason/breeders_toolbox/trialtreefolders.mas
- mason/help/workflow_guided/begin.mas
- sgn.conf
- t/unit_mech/AJAX/BreedersToolbox/TrialMetadata.t
> Replaced hardcoded design types with a list from sgn conf.

- mason/breeders_toolbox/cross_wishlist.mas
> Changing limit number of males for wishlist to 60

- bin/replace_plots.pl
Description 
Add a back-end script to change the field layout in bulk, based on a file.
Checklist 
> Topic/replace plots.pl

- lib/SGN/Controller/AJAX/DroneImagery/DroneImagery.pm
- lib/SGN/Controller/AJAX/DroneImagery/DroneImageryUpload.pm
Description 
Adds new Call for Imagebreed to allow for pipeline use. Fixes CORS issues for uploading drone images from pipeline.
Checklist 
> Added API call. Fixed CORS for drone imagery uploads

- lib/CXGN/BrAPI/v2/Crossing.pm
- lib/CXGN/BrAPI/v2/Germplasm.pm
- lib/CXGN/BrAPI/v2/SeedLots.pm
- lib/CXGN/BrAPI/v2/Studies.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
- t/unit_mech/AJAX/BrAPI_v2.t
Description 
Adding seedlot and crossing test #2824
Checklist 
> Topic/brapi 2.0test

- docs/03_managing_breeding_data/03_04.md
- mason/breeders_toolbox/add_seedlot_dialogs.mas
- mason/breeders_toolbox/upload_seedlots_dialogs.mas
Description 
This pull request tweaks the documentation for the seedlot features that were recently added, quality and source.
Checklist 
> tweak docs for seedlots for quality and source features.

- lib/CXGN/Trial/TrialDesign.pm
Description 
This is fixing the plot number for RCBD.
Checklist 
- [ X ] Bug fix
> fixing plot number on RCBD

- cgi-bin/phenome/stock/stock_ajax_form.pl
- lib/CXGN/Page/Form/AjaxFormPage.pm
- lib/CXGN/Stock.pm
> only curators or the object owner can edit the form details

- lib/SGN/Controller/AJAX/CrossWishlist.pm
> Modified cross wishlist to support yamcross

- sgn_fixture_template.conf
> add cluster_host to sgn_fixture_template.conf

- t/unit_fixture/CXGN/Trial/TrialForCrossesFamilyNames.t
- t/unit_fixture/CXGN/Uploading/UploadAndAddCrossesCrossingtrial.t
> Fixed tests

- ontology/cxgn_plant_section.obo
Description 
reviving the lost obo file for plant section. Currently used in Cassavabase and Sweetpotatobase 
Checklist 
> plant section ontology

- lib/SGN/Controller/AJAX/Accessions.pm
- lib/SGN/Controller/AJAX/Analysis.pm
- lib/SGN/Controller/AJAX/Cross.pm
- lib/SGN/Controller/AJAX/CrossWishlist.pm
- lib/SGN/Controller/AJAX/DocumentBrowser.pm
- lib/SGN/Controller/AJAX/DroneImagery/DroneImagery.pm
- lib/SGN/Controller/AJAX/DroneImagery/DroneImageryMainDisplay.pm
- lib/SGN/Controller/AJAX/DroneImagery/DroneImageryUpload.pm
- lib/SGN/Controller/AJAX/GenotypesVCFUpload.pm
- lib/SGN/Controller/AJAX/GenotypingProtocol.pm
- lib/SGN/Controller/AJAX/GenotypingQC.pm
- lib/SGN/Controller/AJAX/GenotypingTrial.pm
- lib/SGN/Controller/AJAX/Locations.pm
- lib/SGN/Controller/AJAX/Pedigrees.pm
- lib/SGN/Controller/AJAX/PhenotypesUpload.pm
- lib/SGN/Controller/AJAX/Seedlot.pm
- lib/SGN/Controller/AJAX/Trial.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
Description 
This should fix uploads that work with iframe uploads.
Checklist 
> add back text/html return type.

- lib/SGN/Controller/BreedersToolbox/Trial.pm
Description 
Use the JSON::XS->new()->decode method to parse JSON with UTF-8.
Checklist 
> fix an issue with the trial detail page when location codes contain UTF-8 characters

- lib/CXGN/Cross.pm
- t/unit_fixture/CXGN/Trial/TrialForCrossesFamilyNames.t
> Prevent cross deletion if that cross has associated seedlot or trial

- db/00130/AddVendorOrderIDProjectProp.pm
- js/source/legacy/CXGN/BreedersToolbox/GenotypingSubmission.js
- js/source/legacy/CXGN/BreedersToolbox/GenotypingTrial.js
- lib/CXGN/Genotype/CreatePlateOrder.pm
- lib/CXGN/Project.pm
- lib/SGN/Controller/AJAX/GenotypingTrial.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/breeders_toolbox/genotyping_trials/detail.mas
- mason/breeders_toolbox/genotyping_trials/layout_as_list.mas
- mason/breeders_toolbox/genotyping_trials/submit_plates_dialog.mas
- t/unit_fixture/CXGN/Genotype/CreatePlateOrder.t
Description 
Submit genotyping plates to facilities.
It uses parameters from sgn conf:
- genotyping_server_host
- genotyping_server_token
Closes #2454
Checklist 
> submit plates to facilities

- js/install_node.sh
- lib/CXGN/BrAPI/v2/Studies.pm
- lib/CXGN/Trial/Download.pm
- lib/CXGN/Trial/Download/Plugin/TrialLayoutCSV.pm
- lib/CXGN/Trial/Download/Plugin/TrialLayoutExcel.pm
- lib/CXGN/Trial/Search.pm
- lib/CXGN/Trial/TrialLayoutDownload.pm
- lib/SGN/Controller/AJAX/DroneImagery/DroneImagery.pm
- lib/SGN/Controller/AJAX/DroneImagery/DroneImageryUpload.pm
- lib/SGN/Controller/AJAX/FieldBook.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/breeders_toolbox/trial/download_layout_interface_dialog.mas
- t/unit_fixture/CXGN/Uploading/ValidateAllDroneImageryFunctions.t
Description 
When downloading the field layout, measurements are not included by default.
closes #3123 
Checklist 
> Field layout download fix

- lib/CXGN/JSONProp.pm
- lib/CXGN/Stock/SequencingInfo.pm
- lib/SGN/Controller/AJAX/SequencedAccessions.pm
- mason/site/toolbar/analyze.mas
- mason/site/toolbar/manage.mas
- mason/stock/sequencing_status.mas
- t/unit_fixture/CXGN/Stock/SequencingInfo.t
> Fix a feature that allows sequenced genomes to be managed through the database

- lib/CXGN/BrAPI/v2/Studies.pm
Description 
It comments some fields that slows down data retrieving (30 mins) in the studies brapi v2 endpoint:
data agreement
data_links
folders
Checklist 
- [ X] Bug fix
- [ X] Further work is required.
> fix brapi studies

- docs/04_data_analysis_tools.md
> fixes mixed model documentation section title.

- lib/CXGN/Phenotypes/PhenotypeMatrix.pm
Description 
Closes #3016
Checklist 
> fix variable name used to retrieve entryType

- lib/SGN/Controller/BreedersToolbox/Trial.pm
Add URL endpoint: `/breeders/trial/view_by_name/{trial_name}`
Redirect to the trial detail page of a matching trial
> Trial Controller: View Trial by name

- lib/SGN/Controller/Marker.pm
Add URL endpoint: `/marker/view_by_name/{marker_name}`
Redirect to the marker detail page of a matching marker
> Marker Controller: View marker by name

- lib/CXGN/Analysis.pm
- lib/CXGN/Analysis/AnalysisCreate.pm
- lib/SGN/Controller/AJAX/Analysis.pm
Description 
Check analysis name to fix a rare bug
closes #3160
Checklist 
> NIRS model saving fix

- lib/CXGN/Stock/Search.pm
Description 
Fixes broken ajax accession table. Encode utf8 for special characters  was needed.
Closes #3109
Closes #3101
Checklist 
- [ x] Bug fix
- [x ] The relevant issue has been closed.
> encode utf8 in synonyms

- lib/SGN/Controller/AJAX/Dataset.pm
Description 
closes #3153 
Checklist 
> remove submitter/curator check in dataset save

- mason/site/toolbar/about.mas
> add video tutorial link to about menu.

- bin/change_accessions_to_crosses.pl
> Changing from accession stock type to cross stock type

- js/source/legacy/solGS/solGS.js
- lib/SGN/Controller/solGS/solGS.pm
-- fixes bug checking training pop size  with non-default genotyping protocols
> add missing genotype protocol id arg

- lib/CXGN/Trial/Folder.pm
- lib/SGN/Controller/AJAX/BreedersToolbox/Folder.pm
- mason/breeders_toolbox/folder/edit_folder_name.mas
Description 
fixes #3192 
Checklist 
> fix renaming folder

- js/source/legacy/solGS/solGS.js
> json parse args

- R/solGS/gs.r
- R/solGS/kinship.r
--fixes issues related with special characters in colnames
> fix "-" character in df colnames

- lib/CXGN/BrAPI/v1/Calls.pm
- lib/CXGN/BrAPI/v1/Studies.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
It adds  studies layouts to brapi v1.3
Closes  #3206
Checklist 
- [ x] Bug fix
- [ x] The relevant issue has been closed.
> add brapi v1.3 studies layouts 

- lib/CXGN/BrAPI/v1/ObservationVariables.pm
- lib/CXGN/BrAPI/v1/Observations.pm
- lib/CXGN/Phenotypes/StorePhenotypes.pm
- t/unit_fixture/CXGN/Uploading/Storebrapiobservations.t
Description 
fix brapi variables id to upload data from fieldbook
closes #3182
Checklist 
- [ x] Bug fix
> fix brapi variables id to upload data from fieldbook

- bin/delete_cvterms.pl
- bin/rename_stocks.pl
> improved versions of delete_cvterms.pl and rename_stocks.pl scripts.

- lib/CXGN/Project.pm
Description 
fix: get country name for genotyping project page details. 
Closes #3217
Checklist 
- [X ] Bug fix
- [ X] The relevant issue has been closed.
> fix: get country name for genotyping project page details

- lib/CXGN/ODK/Crosses.pm
- mason/breeders_toolbox/manage_odk_data_collection.mas
> Fixed manage odk

- lib/SGN/Controller/Stock.pm
- static/robots.txt
Description 
This function keeps crashing cassavabase through bots. Added login requirement.
Checklist 
> Add login requirement to download_genotypes function

- mason/breeders_toolbox/location_table.mas
Description 
Closes #3235
Checklist 
> add excel, csv and pdf download options to location datatable

- lib/CXGN/Trial/TrialLayoutDownload.pm
- mason/breeders_toolbox/trial/add_trial_treatment_dialogs.mas
- mason/breeders_toolbox/trial/trial_treatments.mas
Description 
Prasad requested ability to add management factors to plants. This is from the Trial detail page -> Experimental Design -> Add Management Factors.
Checklist 
> add management factor on plant level from trial detail page

- js/source/legacy/d3/graphers/stackedObservationPhenotypeHistogram.js
Description 
Adding axes labels to histogram
Checklist 
- [x ] Bug fix
> add axes labels to histogram

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
Close  #3262
Checklist 
- [ x ] Bug fix
> fix token in field layout tools - heatmap

- bin/load_genotypes_vcf_cxgn_postgres.pl
- db/00135/UpdateWizardMaterializedViewsForGenoProtocols.pm
- lib/CXGN/Genotype/ParseUpload.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/GridFileIntertekCSV.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/IntertekCSV.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/VCF.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/transposedVCF.pm
- lib/CXGN/Genotype/StoreVCFGenotypes.pm
- lib/CXGN/List/Validate/Plugin/Stocks.pm
- mason/breeders_toolbox/genotyping_trials/upload_genotyping_data_dialogs.mas
Description 
Allow for genotype upload with mixed stock types
closes #3281
Checklist 
> Allow for genotype upload with mixed stock types

- lib/CXGN/BrAPI/v1/Germplasm.pm
- lib/SGN/Controller/AJAX/Stock.pm
- mason/pedigree/stock_pedigree_string.mas
Description 
it improves:
- pedigree brapi call
- getting pedigree parents string 
Closes #3259
Checklist 
- [ X ] Bug fix
> speed up pedigree tree viewer 

- mason/breeders_toolbox/upload_nirs_spreadsheet_dialogs.mas
- mason/tools/high_dimensional_phenotypes/upload_high_dim_spreadsheet_dialogs.mas
- mason/tools/nirs/nirs_analysis_train_dialogs.mas
Description 
Adding new devices on NIRs upload tool
Checklist 
> adding new devices to NIRs upload

- db/00137/AddLabId.pm
> creating db patch to add new cvterm lab ID

- lib/CXGN/Phenotypes/ParseUpload/Plugin/MetabolomicsSpreadsheetCSV.pm
- lib/CXGN/Phenotypes/ParseUpload/Plugin/SpreadsheetNIRS.pm
- lib/CXGN/Phenotypes/ParseUpload/Plugin/TranscriptomicsSpreadsheetCSV.pm
- lib/SGN/Controller/AJAX/HighDimensionalPhenotypes.pm
- mason/tools/high_dimensional_phenotypes/upload_high_dim_spreadsheet_dialogs.mas
Description 
Adds fields for upload of protocol for metabolomics high-dim phenotypes
closes #3164
Checklist 
> add metabolomics fields to upload

- mason/chado/cvterm.mas
> only curators can edit trait properties

- lib/CXGN/Search/CannedForms.pm
The markers search page was only showing genetic maps and was coded to only show cM units. On T3 we have mostly physical maps. Changed the search query to display all maps and retrieve units from field in database. Also changed display to sort non numeric chromosomes correctly. 
Closes #3295 
Checklist 
> Search markers - show all maps and get units from database

- lib/CXGN/BrAPI/v1/Studies.pm
- lib/CXGN/BrAPI/v2/Studies.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
-Add seedLot name to observationUnits in BrAPI v1
-Fix studyType search in studies
#3292
Checklist 
- [ X ] Fixture update only
> add seedlot name to observationunit brapi

- lib/CXGN/Pedigree/ParseUpload/Plugin/ValidateExistingProgeniesExcel.pm
> Fix validation

- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
Description 
Closes #3332 
Checklist 
> fix duplicate plot name error reporting

- ontology/cxgn_time.obo
> unobsolete date of term, see discussion #3323

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
it failed when auth_token was not given
Checklist 
> fix fieldmap auth

- lib/CXGN/BrAPI/Exceptions/Exception.pm
- lib/CXGN/BrAPI/Exceptions/ServerException.pm
- lib/CXGN/BrAPI/v2/ExternalReferences.pm
- lib/CXGN/BrAPI/v2/ObservationUnits.pm
- lib/CXGN/BrAPI/v2/ObservationVariables.pm
- lib/CXGN/BrAPI/v2/ServerInfo.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
- sgn.conf
Description 
removes server_permission from serverInfo
adds exceptions and references packages
Checklist 
> add brapi methods to sgn conf

- mason/tools/sequence_metadata/jbrowse_config_sequence_metadata.mas
- mason/tools/sequence_metadata/query_sequence_metadata.mas
Description 
This puts info for JBrowse link into a separate mason file that can be overwritten in the mason repo.
Checklist 
> Sequence Metadata: JBrowse configuration

- lib/SGN/Controller/AJAX/Heritability.pm
- lib/SGN/Controller/AJAX/Stability.pm
> fix phenotype file quotes for stability and heritability tools

- lib/SGN/Controller/AJAX/Solgwas.pm
> fix quotes for phenotype file in gwas tool

- lib/SGN/Controller/AJAX/CrossWishlist.pm
- mason/breeders_toolbox/cross_wishlist.mas
> Store cross wishlist metadata

- js/source/legacy/brapi/PedigreeViewer.js
Description 
fix pageSize and set 20 nodes as min
Closes #3379
Checklist 
- [x ] Bug fix
> fix pedigree viewer pageSize and set 20 nodes as min

- lib/CXGN/Analysis.pm
-- required for setting project owner
> pass analysis owner id arg for set_trial_owner

- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
I noticed that the rows and columns were appended to arrays based on their explicit mention in the excel file. So if they are not explicitly mentioned, they will not be appended to rows and cols arrays and subsequently will not be appended to the unique_rows and unique_cols arrays. Therefore, I simply used the max row and max column and re-initialized the unique_rows and unique_cols arrays to include a range of numbers 1 to the max rows and columns, respectively.
Checklist 
> Fixed rows and columns in field layout

- mason/search/organisms.mas
Description 
This closes one of the oldest issues in the system, issue #34 from 2011!!!!!!!!!!!
Checklist 
> add autocomplete to organism search field. closes #34.

- mason/breeders_toolbox/trial.mas
- mason/breeders_toolbox/trial/change_plot_accessions_dialogs.mas
Description 
Added confirmation message for Change accessions via file upload
Checklist 
> Add confirmation message to change accession file upload

- mason/breeders_toolbox/genotyping_protocol/index.mas
should not show "Delete Genotype Protocol" unless curator
#3469 
Checklist 
> do not show "Delete Genotype Protocol" unless curator

- lib/SGN/Controller/AJAX/ImageAnalysis.pm
- lib/SGN/Controller/AJAX/Search/Image.pm
- mason/tools/image_analysis.mas
Description 
Fixes bug where some returned image scores and errors were not displaying in result table
Fixes error where results Datatable not resetting if same request attempted without reloading page
Adds download option to results datatable
Adds trial links
closes #3429
Checklist 
> Updates for image analysis tool

- mason/breeders_toolbox/trial/edit_fieldMap.mas
Description 
Removes Substitute Accession feature.
Checklist 
> Remove substitute accession feature

- ontology/cxgn_time.obo
> consolidate events and plant categories, merge after_harvest terms

- lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm
Description 
closes #3398
Checklist 
> modify multi-trial upload to handle mixed order design info

- lib/SGN/Controller/BreedersToolbox.pm
Description 
Closes #2695
Checklist 
> adds login check and redirect for search wizard page

- lib/CXGN/Project.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
Description 
Adds tissue sample owner.
Checklist 
> added tissue sample owners

- lib/CXGN/BrAPI/v2/ObservationVariables.pm
> fix brapi GET /variables bug

- lib/SGN/Controller/Static.pm
Description 
Remove hardcoded sgn-specific projects and redirect to separate mason repo.
Paired with a necessary PR in the solgenomics-specific mason repo
Checklist 
> redirect project pages

- lib/CXGN/Trial/TrialLayout/AbstractLayout.pm
- lib/CXGN/Trial/TrialLayout/Analysis.pm
- lib/CXGN/Trial/TrialLayout/Genotyping.pm
- lib/CXGN/Trial/TrialLayout/Phenotyping.pm
- lib/CXGN/Trial/TrialLayout/SamplingTrial.pm
Description 
Fixes retrieval of genotyping plate layout
closes #3546 
Checklist 
> fixes retrieval of genotyping plate layout

- lib/CXGN/Phenotypes/HighDimensionalPhenotypesSearch.pm
> Catch high dim search

- lib/CXGN/BrAPI/v2/ExternalReferences.pm
- lib/CXGN/BrAPI/v2/ObservationVariables.pm
Description 
Fixes #3545
Checklist 
> fixes insert external references 

- lib/SGN/Controller/AJAX/ImageAnalysis.pm
- mason/tools/image_analysis.mas
Description 
closes #3552
Checklist 
> Fix image analysis save error on cassavabase

- mason/tools/label_designer/select_layout.mas
Description 
Adds  pixel/cm guidance for user, in addition to the pixel/inch already present.
Closes #3560 
Checklist 
> add pixel per cm conversion

- mason/solgs/population/combined/combined.mas
- mason/solgs/population/multiple_traits_output.mas
-- fixes acronyms display in some solGS pages
> replace old acronym template with a new one

- lib/CXGN/NOAANCDC.pm
- lib/SGN/Controller/AJAX/Locations.pm
- lib/SGN/Controller/NOAANCDC.pm
- mason/breeders_toolbox/noaa_ncdc_analysis.mas
Description 
Query NOAA NCDC database for weather info at a given NOAA weather station and produce daily temperature and precipitation charts spanning the queried years, for an optionally selected window of days in a year.
Checklist 
> NOAA NCDC weather charts

- lib/CXGN/Project.pm
Description 
Fixes an issue with trial deletion.
Checklist 
> fix bug in project deletion.

- sgn_test.conf
- t/README.md
- t/test_fixture.pl
Description 
Addresses issue: https://github.com/solgenomics/sgn/issues/3519
Changes:
- Added documentation on how to run tests.
- Added a `sgn_test.conf` file that is meant to be untouched so that their is a consistent testing environment
- Added a configuration to the `test_fixture.pl` script so that you can specify the server logs output file. 
I used a file that @MFlores2021 sent me that she said she used for tests. I only use a small subset of the features in BreedBase, so the `sgn_test.conf` file should be looked over to see if it contains all necessary configs. 
Checklist 
> Add dedicated testing configuration

- t/lib/SGN/Test/WWW/WebDriver.pm
- t/test_fixture.pl
See https://github.com/solgenomics/breedbase_dockerfile/pull/29
> Updates to support docker-compose testing

- db/00143/SpeedUpMatviews.pm
Description 
fixes withdata in patch
Checklist 
> remove last with data from view def

- db/00143/SpeedUpMatviews.pm
> cast location_id from text to integer

- js/source/legacy/CXGN/BreedersToolbox/UploadPhenotype.js
- lib/CXGN/Phenotypes/StorePhenotypes.pm
- mason/tools/high_dimensional_phenotypes/upload_high_dim_spreadsheet_dialogs.mas
Description 
closes #3565
Checklist 
> Improves phenotype upload feedback and fixes overwriting bug

- t/unit_fixture/CXGN/Genotype/CreatePlateOrder.t
Description 
fixes create plate order test
Checklist 
- [ x] Bug fix
> fixes create plate order test

- lib/CXGN/Genotype/ParseUpload/Plugin/IntertekCSV.pm
- lib/SGN/Controller/AJAX/GenotypesVCFUpload.pm
- t/unit_fixture/CXGN/Uploading/VCFGenotypes.t
> Fix Intertek genotype upload for tissue samples

- t/unit_fixture/CXGN/Onto.t
Description 
Fixes the t/unit_fixture/CXGN/Onto.t test
Checklist 
> fix onto test.

- db/00145/CreateMaterializedMarkerview.pm
Description 
Put `REFRESH MATERIALIZED VIEW` statement in an `EXECUTE` statement to prevent an error on postgres versions < 12.
Checklist 
> Fix CreateMaterializedMarkerview DB Patch

- lib/CXGN/BrAPI/v2/Observations.pm
Description 
Handles missing user_id error in POST /observations 
Closes #3592
Checklist 
- [ X ] Bug fix
- [ X ] The relevant issue has been closed.
> andle missing user_id error

- db/00146/CreateMaterializedMarkerviewUpdated.pm
- mason/markers/genotyped/external_links.mas
Description 
This PR removes an unnecessary embedded mason component and fixes a bug in the matview query that causes the query to fail if one or more markers do not have a position set.
Checklist 
> Materialized_markerview fixes

- lib/CXGN/Genotype/Search.pm
in the genotype protocol page a download could not be opened in TASSEL program because the GT field was not the first field
#3534 
there is still a problem with sorting the VCF file but that is complicated by chromosome data that a non standard string instead of numeric
Checklist 
- [x ] Bug fix
> make GT field first in VCF as required by specifications

- js/source/legacy/CXGN/List.js
> Fixed list validation

- js/source/entries/boxplotter.js
- lib/CXGN/BrAPI/v1/ObservationUnits.pm
- lib/CXGN/BrAPI/v2/ObservationUnits.pm
Description 
-Updates to v2 search observationunits endpoints
-Get observations 
Checklist 
> update boxplotter to brapi v2

- t/lib/SGN/Test/Data.pm
- t/unit_fixture/SGN/Image.t
- t/unit_fixture/SGN/Test/Data.t
> fix db access in tests for Data.t, Image.t and Feature.t

- mason/breeders_toolbox/genotyping_trials/upload_genotyping_data_dialogs.mas
> Added autocomplete species name and warning messages for ssr upload

- lib/CXGN/Phenotypes/PhenotypeMatrix.pm
- lib/CXGN/Phenotypes/Search/Native.pm
Description 
Closes #3628
Checklist 
> Adds notes column to native search downloads

- db/00149/AddMissingSeedlotViews.pm
Description 
This DB Patch adds the missing views:
- seedlots
- locationsXseedlots
Fixes #3646 
Checklist 
> DB Patch: Add missing seedlot views

- lib/CXGN/Login.pm
> last_access_time refers to sp_token table

- js/source/legacy/CXGN/BreedersToolbox/UploadTrial.js
Description 
closes #3650
Checklist 
> fixes reporting of file name error in multi-trial upload

- js/source/legacy/CXGN/BreedersToolbox/Crosses.js
- lib/Bio/GeneticRelationships/Pedigree.pm
- lib/CXGN/Pedigree/AddPedigrees.pm
- lib/SGN/Controller/AJAX/Pedigrees.pm
- mason/breeders_toolbox/add_cross_dialogs.mas
- mason/breeders_toolbox/upload_pedigrees_dialogs.mas
- mason/pedigree/stock_pedigree.mas
- t/unit_fixture/CXGN/Pedigree/AddPedigrees.t
> Reselected cross type for pedigree

- lib/SGN/Controller/AJAX/Order.pm
- mason/order/catalog.mas
> Ordering notification for vendors

- js/source/legacy/solGS/Dataset.js
- js/source/legacy/solGS/phenoHistogram.js
- lib/SGN/Controller/solGS/AnalysisQueue.pm
- lib/SGN/Controller/solGS/Path.pm
- mason/solgs/population/trait_phenotype_histogram.mas
-- remove trailing slash at the end of hostname; doubles '/' when concatenating hostname with paths.
-- improve check for dataset categories
> remove trailing slash at the end of hostname

- lib/SGN/Controller/AJAX/TrialMetadata.pm
Description 
closes #3703 
Checklist 
>  if not more obs units than values return zero percent missing

- db/00151/SaveChromosomeRankInNdProtocol.pm
- lib/CXGN/Genotype/StoreVCFGenotypes.pm
> Saves chromosome rank info for genotyping protocols

- mason/tools/mixedmodels.mas
> remove warning in the mixed model tool.

- lib/CXGN/Dataset.pm
- lib/CXGN/Dataset/File.pm
- lib/SGN/Controller/AJAX/Heritability.pm
- lib/SGN/Controller/AJAX/Stability.pm
- t/unit_mech/AJAX/Heritability.t
- t/unit_mech/AJAX/Stability.t
> Fix heritability and stability tools; add tests

- mason/search/stocks_graphicalfiltering.mas
- mason/tools/graphicalfiltering/index.mas
- mason/tools/trial_comparison/index.mas
Description 
This fixes:
-Trial comparison 
-Graphical filtering
Close #3720
Checklist 
- [ x] Bug fix
> migrate tools to brapi v2

- lib/CXGN/BrAPI/v2/ObservationUnits.pm
Description 
matview refresh was happening for every observation unit
Checklist 
> optimized brapi/v2/observationunits update

- mason/search/stocks_graphicalfiltering.mas
- mason/tools/graphicalfiltering/index.mas
Description 
Fixes saving filtered accession as lists in the graphical filtering tool
Closes  #2141 
Checklist 
- [X ] Bug fix
- [X ] The relevant issue has been closed.
> Fix: adding filtered accession to lists

- mason/breeders_toolbox/download.mas
- t/unit/CXGN/PRepDesign.t
Description 
There are not only GBS genotypes in the db :-)
Checklist 
> Remove 'GBS' from Genotypes download

- mason/breeders_toolbox/location_table.mas
> fix parsing of locaton json.

- lib/SGN/Controller/AJAX/LabelDesigner.pm
Description 
This adds additional attributes to the Label Designer to be included on the printed barcode labels for specific list types:
- Seedlots:
- seedlot id = stock id of seedlot
- seedlot contents = accession or cross name of seedlot's contents
- seedlot box = box attribute of seedlot
- Accessions:
- accession id = stock id of accession
Checklist 
> Label Designer: Additional List Attributes

- js/source/legacy/CXGN/List.js
Description 
Closes #3667 
Checklist 
> Fix list validate working modal

- js/source/entries/wizard.js
- js/source/legacy/CXGN/BreedersToolbox/MarkerSet.js
- js/source/modules/wizard-downloads.js
- mason/breeders_toolbox/breeder_search_page.mas
- mason/breeders_toolbox/markers/manage_markers.mas
- mason/search/stocks.mas
> Markerset type for genotyping download

- lib/SGN/Controller/AJAX/DroneImagery/DroneImagery.pm
> produce clean output on STDOUT in DroneImagery functions (for tests)

- .github/workflows/test.yml
Description 
Not running the Selenium tests until they're ready
Checklist 
> Comment-out Selenium tests in GitHub Actions workflow

- lib/SGN/Controller/BreedersToolbox/Trial.pm
> Fixed locations on crossing experiment page

- lib/CXGN/Dataset.pm
- lib/CXGN/Dataset/File.pm
- lib/SGN/Controller/AJAX/Solgwas.pm
Description 
An issue in CXGN::Dataset::File caused gwas not to work.
Fix a path in gwas tool.
Checklist 
> fix gwas/dataset issue

- mason/breeders_toolbox/trialtreefolders.mas
> Fixed sampling trial link on manage trial page

- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
Description 
Accession upload from file was broken because of a stray wiggly bracket... :-(
Checklist 
> fix an issue with accession uploading.

- bin/find_stock_uniquename.pl
-- was first upper casing names before matching with names in file.
> preserve db stock names case-sensitive when comparing with names in file

- db/00144/FixFieldbookImageCvterm.pm
> remove stray parenthesis to prevent this dbpatch from crashing.

- js/source/legacy/CXGN/List.js
- mason/breeders_toolbox/download.mas
Description 
In the download section, the accession list check fails always because the function in CXGN.List returns 1 instead of 0 if successful.
Checklist 
> fix download list check

- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
Description 
List addition of accession was broken because the actual addition code was not present in the caught promise.
Checklist 
> fix accession upload by list.

- docs/03_managing_breeding_data/03_04.md
- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
- lib/CXGN/Stock/Seedlot.pm
- lib/SGN/Controller/AJAX/Seedlot.pm
- lib/SGN/Controller/Seedlot.pm
- mason/breeders_toolbox/delete_seedlots.mas
- mason/breeders_toolbox/seedlots.mas
- t/unit_mech/AJAX/Stocks/DeleteSeedlots.t
> Seedlot deletion using a list

- lib/SGN/Controller/AJAX/LabelDesigner.pm
Addresses issue #3848 .
Description 
Checklist 
> Fix LabelDesigner crashes with certain plot lists

- mason/site/login_dialog.mas
Description 
Minor fix to the login dialog:
submit the login form when the enter key is pressed in the username or password fields
(previously pressing the enter key would bring up the new user dialog)
Checklist 
> Login: submit login form on <enter>

- lib/SGN/Controller/BreedersToolbox/Download.pm
-- name download files after their respective data type (metadata.csv, phenotype.csv)
> make download filename data type specific

- js/source/entries/fieldmap.js
Description 
fixed harvesting order error.
Checklist 
> fixed harvesting order error

- R/solgwas/solgwas_genoPCA_script.R
- R/solgwas/solgwas_script.R
- lib/SGN/Controller/AJAX/Solgwas.pm
- mason/help/solgwas.mas
genotype file does not have chrom and pos columns
1. get chrom and pos information from materialized_markerview
2. filter markers that have more than 20% missing data
3. replace a few more special characters that cause problems in R or in arguements
https://github.com/solgenomics/sgn/issues/3765
https://github.com/solgenomics/sgn/issues/3214
Checklist 
> GWAS fix location

- lib/CXGN/Project.pm
Description 
Allows tissue samples to be added multiple times on trial detail page
closes #3844 
Checklist 
> Add tissue samples multiple times to trial

- lib/CXGN/Dataset.pm
- t/unit_fixture/CXGN/Dataset.t
> Fix dataset retrieve functions to be array of arrays

- lib/CXGN/BreedersToolbox/Projects.pm
Description 
Remove debugging print of all locations to the error log file
Checklist 
> Projects.pm: Remove log of locations

- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
> fix typos as reported

- lib/SGN/Controller/AJAX/BrAPI.pm
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
> remove hard coded hostname from brapi authorization string

- R/solgwas/solgwas_script.R
- lib/SGN/Controller/AJAX/Solgwas.pm
get protocol_id from dataset instead of site default
ignore quotes in phenotype file
Checklist 
> fix GWAS locations

- js/source/entries/fieldmap.js
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
Fixes design holes by filling them in.
Checklist 
> fixed holes in design error!

- .github/workflows/test.yml
Description 
Re-enable Selenium tests in GitHub Actions workflow so proposed jquery updates can be tested 
Checklist 
> Re-enable selenium tests on pull request

- .github/workflows/test.yml
Description 
Finish https://github.com/solgenomics/sgn/pull/3896
Checklist 
> Start selenium service in GA test workflow

- lib/CXGN/BrAPI/v2/Images.pm
Description 
closes #3887
Checklist 
> use original filename in brapi image data store

- js/source/legacy/CXGN/List.js
- lib/CXGN/List/Validate/Plugin/Accessions.pm
- mason/site/list.mas
> fix issues with list multiple synonyms validation

- lib/SGN/Controller/AJAX/Seedlot.pm
Description 
partially closes #3908
Checklist 
> add submitter check on seedlot creation

- lib/CXGN/Trial/TrialDesign/Plugin/RRC.pm
- lib/SGN/Controller/AJAX/Trial.pm
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
Description 
Fix row-column serpentine numbering issue and make row num requirement explicit 
Checklist 
> row column design bug fix

- lib/SGN/Controller/AJAX/GenotypesVCFUpload.pm
> fix utf8 encoding and correctly parse DOS formatted files.

- js/source/legacy/solGS/selectionIndex.js
--fixes listing of selection populations in helper tools in the multi models page.
> fix predicted (multi traits) selection pops filter

- lib/SGN/Controller/AJAX/Trial.pm
Description 
Just deleted one line for refreshing fullview matview
Checklist 
> took out a fullview mat refresh

- mason/breeders_toolbox/location_table.mas
Description 
from Manage > Location page
Checklist 
> Filter [Computation] location

- lib/SGN/Controller/AJAX/Locations.pm
> do not allow the computation location to be deleted

- mason/breeders_toolbox/trial/download_layout_interface_dialog.mas
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
Refactored spatial layout download.
Checklist 
> refactored download spatial layout feature

- mason/breeders_toolbox/accessions/find_trials_by_accessions.mas
Description 
fixes an issue (#3942) that prevents the list to be submitted even if it contains valid accessions.
Checklist 
> fix list validation in find trials with common accessions tool.

- README.md
> update links in the description

- db/00156/AddProjectTypeId.pm
Description 
Need to update SGN bio-chado-schema with this table change 
Checklist 
> db patch for project.type_id foreign key

- lib/CXGN/Project.pm
> fix the type_id in a query that caused an issue with label designer

- lib/CXGN/Project.pm
- lib/CXGN/Trial/TrialDesignStore/PhenotypingTrial.pm
- lib/SGN/Controller/AJAX/DroneImagery/DroneImagery.pm
> fix more type_id queries.

- t/selenium2/01_list/list.t
> pass list selenium test

- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
- lib/CXGN/Stock.pm
- lib/SGN/Controller/AJAX/Cross.pm
- lib/SGN/Controller/AJAX/Stock.pm
- mason/breeders_toolbox/manage_accessions.mas
- mason/stock/related_stock.mas
- t/unit_mech/AJAX/Search/CrossSearch.t
> Accessions with pedigree info section on manage accessions page

- .github/workflows/test.yml
> do not run selenium tests.

- lib/SGN/Model/solGS/solGS.pm
-- populating genotyping protocols menu in the analyses pages that use genotype data was getting slower and slower (>30sec) as the genotyping_protocolsXtrials matview is getting larger. Querying the genotyping_protocols matview solves the problem. Hopefully, only genotyping_protocols with genotype data are in the production DBs.
> speed up genotyping protocols query

- t/test_fixture.pl
Description 
Speeds up process of running tests. 
Updates fixture dump by running db patches up through 00156. Updates test_fixture to start with patch 00157 when running tests 
Checklist 
> run up through patch 00156 on fixture dump

- bin/refresh_matviews.pl
Description 
Add `all_but_genoview` to the list of acceptable refresh modes to prevent the script from dying.
Checklist 
> Fix refresh_matviews.pl script

- js/source/entries/boxplotter.js
- lib/CXGN/BrAPI/v2/ObservationUnits.pm
- mason/tools/boxplotter.mas
Description 
Adding pageSize as default 100000
Adding Create boxplot button instead of in change on the dropdowns (it was confusing since some datasets takes so long to load).
Adding "Loading ...." message 
Checklist 
> fixing boxplot bugs

- js/source/legacy/CXGN/List.js
- mason/barcode/index.mas
- mason/search/bulk.mas
- mason/search/stocks.mas
Description 
Alphabetize list types, printing formats, bulk search, and accession and plots dropdown menus. 
resolves Issue #3926
Checklist 
> Alphabetize Dropdown Menus

- js/source/legacy/tools/LabelDesigner.js
- mason/tools/label_designer/select_datasource.mas
Description 
Added text description to label designer that listed data source options: list, crossing experiment, trial, or genotyping plate.
Resolves #3801 
Checklist 
> Add description of data source options to label designer

- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
Description 
Update list of possible design types in multi-trial file format info dialog
Checklist 
> add missing trial type codes

- bin/download_accession_attributes.pl
> add script to download stock attributes based on list of stock names.

- mason/breeders_toolbox/trial/edit_fieldMap.mas
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
Added documentation to the more info button in the fieldmap viewer.
Checklist 
> added documentation

- t/unit_mech/AJAX/_BrAPI_v1.t
Description 
Fixes some number issues in location 
Checklist 
> brapi v1 location number fixes

- lib/SGN.pm
- lib/SGN/Script/Server.pm
- sgn_test.conf
Description 
determines the user of the dir js/node_modules and uses that user to run npm run build.
Checklist 
> adapt npm user to file ownership.

- lib/SGN.pm
- lib/SGN/Script/Server.pm
> correct logic of user addition for npm user

- lib/SGN/Controller/AJAX/Order.pm
- mason/order/catalog.mas
> Fixed whitespace issue for ordering system.

- js/source/legacy/CXGN/BreedersToolbox/Crosses.js
- lib/SGN/Controller/BreedersToolbox.pm
- mason/breeders_toolbox/cross/upload_crosses_dialogs.mas
- mason/breeders_toolbox/crossing_experiment_tree.mas
- mason/breeders_toolbox/manage_crosses.mas
> Restrict cross wishlist to sites with odk service

- js/source/entries/fieldmap.js
Description 
Simple formatting change that was requested.
Checklist 
> fixed formatting for download harvesting/planting order file

- R/GCPC_YamBase.R
> fix dominance genotype dosages

- lib/CXGN/BrAPI/v2/Events.pm
Description 
it modifies events endpoint to new brapi standard.
date
studyName
eventType
eventDescription
Closes #4055 
Checklist 
- [ x ] New feature
> brapi /events endpoint modification

- cgi-bin/search/est.pl
- cgi-bin/tools/align_viewer/index.pl
- lib/CXGN/Image/Search.pm
- lib/SGN/Controller/Search.pm
> fix image search query to use placeholders.

- lib/CXGN/Project.pm
Description 
as reported by Prasad. Symptom was, plants could not be created.
closes #4074.
Checklist 
> fix another type_id issue with a query

- lib/CXGN/Stock/Order.pm
- lib/CXGN/Stock/OrderBatch.pm
- lib/CXGN/Stock/ParseUpload/Plugin/CatalogXLS.pm
- lib/SGN/Controller/AJAX/Order.pm
- lib/SGN/Controller/Catalog.pm
- mason/order/add_catalog_item_dialog.mas
- mason/order/catalog.mas
- mason/order/edit_catalog_details_dialog.mas
- mason/order/upload_catalog_items_dialog.mas
- sgn.conf
- t/unit_fixture/CXGN/Stock/CatalogOrder.t
> Sending ordering info to Banana Ordering System

- .github/workflows/test.yml
Description 
it contained  a tab instead of spaces... :-(
Checklist 
> fix test.yml file

- t/selenium2/search/locus.t
- t/selenium2/search/stock.t
- t/selenium2/search/trial.t
Description 
it fixes  selenium search folder tests
Checklist 
> fix selenium search folder tests

- js/source/modules/wizard-search.js
Description 
closes #3842
Checklist 
> leave already selected items selected during select all

- lib/CXGN/Genotype/ParseUpload/Plugin/VCF.pm
- lib/CXGN/Genotype/ParseUpload/Plugin/transposedVCF.pm
- t/unit_fixture/CXGN/MixedModels.t
Description 
closes #4083.
Checklist 
> remove LFs from lines read from file for compatibility with DOS files.

- lib/CXGN/ODK/Crosses.pm
- lib/CXGN/Pedigree/AddCrossInfo.pm
> Fixed saving cross info from ona

- lib/CXGN/Phenotypes/PhenotypeMatrix.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/breeder_search_page.mas
Description 
fixes related phenotype download on wizard page when maximum and minimum values are specified for any given trait.
closes #4102 
Checklist 
> fix related pheno download on wizard page

- js/source/legacy/brapi/BrAPI.js
- lib/SGN/Controller/AJAX/Stock.pm
Description 
Fix for pedigree in brapi.js visualization. 
However, I don't have any means to test it other than live js injection from a browser.
Checklist 
> brapi.js pedigree fix

- R/solGS/gs.r
Fix 'try' function bug in R 4.2
> fix try return value check

- R/Nirs/nirs_upload_filter_aggregate.R
- lib/SGN/Controller/AJAX/HighDimensionalPhenotypes.pm
Description 
Fix for NIRS test with R 4_2 warnings / errors changes
Checklist 
> ValidateNIRS fixed for R 4.2

- mason/breeders_toolbox/location_map.mas
> clarify multiple programs can be selected per location

- .github/workflows/test.yml
Description 
Update of workflow to docker 0.49 and add selenium tests for the main PULL workflow
Checklist 
> update of workflow to selenium tests and docker 0.49

- ontology/cxgn_time.obo
> add "at termination" breeding time event requested for musabase

- lib/SGN/Controller/AJAX/CrossWishlist.pm
> Fixed wishlist tempfiles dir

- .github/workflows/test.yml
- t/selenium2/breeders/create_genotyping_trial.t
Description 
A simple fix for the name of a folder in selenium tests
Checklist 
> fixed folder name for selenium/breeders

- t/lib/SGN/Test/Fixture.pm
Description 
Fix for clean_up_db() function. 
Fixed clear_db  functionality is essential to run multiple similar tests but with different input extensions for files.
To test a  new fix I would suggest running the following with clean_up_db() :
t/unit_fixture/CXGN/Uploading/TrialUpload.t
t/unit_fixture/CXGN/Uploading/ValidateNIRS.t
t/unit_fixture/CXGN/Uploading/ValidateAllDroneImageryFunctions.t
Which typically would fail because db updates and deletes errors. 
Checklist 
> clean_up_db fixed

- R/GCPC.R
- lib/CXGN/Dataset/File.pm
- lib/SGN/Controller/AJAX/GCPC.pm
> tweaks to GCPC tool; create file at the proper location for CXGN::Dataset::File

- js/source/modules/wizard-downloads.js
Description 
Fix vcf genotype download from wizard.  
Checklist 
> fix format arg typo -- stringify value

- js/source/modules/wizard-downloads.js
> Fix additional genotype downloads

- mason/tools/high_dimensional_phenotypes/upload_high_dim_spreadsheet_dialogs.mas
Description 
This fixes issue #4108
Checklist 
> Ensure additional HDP protocol fields show when creating new protocol

- bin/load_people.pl
- bin/send_passwords.pl
Description 
Script loads user data from an xlsx file
Checklist 
> add script to load user accounts

- lib/CXGN/Pedigree/AddGrafts.pm
- lib/SGN/Controller/AJAX/Grafting.pm
- sgn.conf
> fix accession name check in graft upload

- bin/load_stocks.pl
> generic stock loading script

- docs/03_managing_breeding_data/03_03.md
- js/source/legacy/CXGN/BreedersToolbox/UploadRenameAccessions.js
- lib/CXGN/Stock.pm
- lib/SGN/Controller/AJAX/Accessions/Rename.pm
- mason/breeders_toolbox/manage_accessions.mas
- mason/breeders_toolbox/upload_accession_rename_dialog.mas
- mason/breeders_toolbox/upload_graft_dialogs.mas
- t/data/stock/renaming/accession_renaming_1.csv
- t/data/stock/renaming/accession_renaming_2.csv
- t/data/stock/renaming/accession_renaming_3.csv
- t/unit_mech/AJAX/Stocks/UploadRenameAccessions.t
> add a bulk accession rename feature

- lib/CXGN/Trial/ParseUpload/Plugin/TrialChangePlotAccessionsCSV.pm
> remove windows style line endings for a better user experience on windows

- t/unit_fixture/CXGN/Stock/CatalogOrder.t
> Fix catalog and order test

- lib/CXGN/Pedigree/ParseUpload/Plugin/AdditionalInfoExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossInfoExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesExcelFormat.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesSimpleExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/FamilyNameExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/ProgeniesExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/ValidateExistingProgeniesExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/WishlistExcel.pm
> Remove whitespaces from headers before validating

- lib/CXGN/Pedigree/TargetNumbers.pm
> Musabase specific cross property

- mason/breeders_toolbox/trial/weather.mas
Description 
Fixes trial detail page weather links by updating the weather db url now that rtbbase is on https 
closes #461
Checklist 
> update weather db url to https

- mason/site/login_dialog.mas
Description 
#4409 
Checklist 
> after successful login do not set goto_url to login

- lib/CXGN/Cross.pm
- lib/SGN/Controller/AJAX/Stock.pm
- mason/breeders_toolbox/manage_accessions.mas
- t/unit_fixture/CXGN/Pedigree/AddPedigrees.t
> Accessions missing pedigree table on manage accessions page

- js/source/legacy/CXGN/Login.js
- lib/SGN/Authentication/User.pm
- lib/SGN/Controller/AJAX/Authenticate.pm
- lib/SGN/Controller/AJAX/Login.pm
- lib/SGN/Controller/BrAPIClient.pm
> use the sp_token table to manage logins also in brapi calls

- lib/CXGN/BrAPI.pm
- lib/CXGN/BrAPI/v2/Pedigree.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
Add new feature brapi GET /pedigree 
Checklist 
> brapi /pedigree endpoint

- lib/CXGN/MixedModels.pm
Description 
Mixed model analysis storage broken because of R-based names in files, instead of regular trait names
Checklist 
> fix analysis storage for mixed models

- js/source/legacy/CXGN/Login.js
- lib/SGN/Controller/AJAX/Login.pm
> tweak login system calls again.

- lib/SGN/Controller/AJAX/ImageAnalysis.pm
- mason/tools/image_analysis.mas
Description 
closes #4358
Checklist 
> add model metrics dialog to image analysis results

- lib/CXGN/Trial/Download/Plugin/AccessionsWithPedigreeXLSX.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- lib/SGN/Controller/Search/Cross.pm
- mason/breeders_toolbox/manage_accessions.mas
- t/unit_mech/AJAX/Search/CrossSearch.t
> Download all accessions with pedigree info

- lib/SGN/Controller/Blast.pm
Description 
query for db_ids was not correct
Checklist 
> fix issue with blast links

- lib/SGN/Controller/InSilicoPcr.pm
Description 
The messages can gum up the entire server... :-(
Checklist 
> Remove debug messages in in silico PCR tool

- lib/CXGN/Genotype/GenotypingProject.pm
- lib/CXGN/Project.pm
- lib/SGN/Controller/AJAX/Search/GenotypingDataProject.pm
- mason/search/genotyping_data_projects.mas
- t/unit_fixture/CXGN/Trial/TrialCreate.t
> Added number of plates and number of accessions in genotyping project search table

- js/source/legacy/solGS/genotypingProtocol.js
- js/source/legacy/solGS/pca.js
Description 
-- refactored getting protocol id to use for selected population.
Checklist 
> use getgenotypingprotocolid method

- mason/breeders_toolbox/seedlots.mas
- mason/breeders_toolbox/upload_seedlots_inventory_dialogs.mas
Description 
The inventory app is currently not available from the Google Store. Remove link to avoid 404s.
Checklist 
> remove inventory app link

- lib/CXGN/Stock/ParseUpload/Plugin/AccessionsXLS.pm
> detect duplicate accessions in upload validation step

- lib/CXGN/BrAPI/v2/SeedLots.pm
- lib/CXGN/BreedersToolbox/Accessions.pm
- lib/CXGN/Stock/Seedlot.pm
- lib/SGN/Controller/AJAX/HTMLSelect.pm
Description 
Fix searching seedlots with accession names by adding a description variable to multiple files.
Closes #4295 
Checklist 
- [ x] Bug fix
- [ x] The relevant issue has been closed.
> Fix seedlot search with accession names

- lib/CXGN/Project.pm
Description 
closes #1410
Checklist 
> Exclude seedlots from selection index control select boxes

- lib/CXGN/BrAPI.pm
- lib/CXGN/BrAPI/v2/Pedigree.pm
- lib/CXGN/BrAPI/v2/Plates.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
Description 
Add new endpoints: 
plates
search/plates
/lists/{listDbId}/data
search/pedigree 
Fixes pedigree duplicated nodes.
Checklist 
> Updates brapi v2.1

- docs/index.md
- lib/SGN/Controller/Help.pm
- mason/help/index.mas
- mason/site/toolbar/about.mas
> Fix default help and about menu items

- lib/SGN/Controller/AJAX/Catalog.pm
- mason/order/catalog_item_details.mas
- mason/order/order_details.mas
> Adding manage order and manage catalog links on details pages

- ontology/cxgn_time.obo
Description 
required for musabase post-composing 
Checklist 
> post inoculation event

- .github/workflows/test.yml
- t/selenium2/03_dataset/dataset.t
A docker version update for gitaction and selenium dataset line added to tests.
Checklist 
> gitaction docker version update and selenium dataset added

- lib/CXGN/BreedersToolbox/Projects.pm
Description 
fix parentheses in expression that may cause an issue.
Checklist 
> try to fix accession phenotype download again

- mason/site/toolbar/analyze.mas
Description 
Just making some options available to the toolbar.
Checklist 
> Adding options to Analyze toolbar in breedbase

- lib/SGN/Controller/AJAX/Search/Genotype.pm
> Fixed genotyping data table on genotyping project page

- mason/search/stocks.mas
Description 
fixed accession "selected" value from mason file as default to search
https://github.com/solgenomics/sgn/issues/4537#issue-1712022645
Checklist 
> fixed accession "selected" value from mason file as default to search

- bin/load_people.pl
Description 
minor fixes to the POD of a loading script for account information
Checklist 
> fix perldoc errors in the bin/load_people.pl script.

- lib/CXGN/Genotype/GenotypingProject.pm
- lib/CXGN/Genotype/Protocol.pm
- lib/CXGN/Trial/TrialLayoutDownload/GenotypingPlateLayout.pm
- lib/SGN/Controller/AJAX/Search/Genotype.pm
- lib/SGN/Controller/AJAX/Search/GenotypingDataProject.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/genotyping_data_project/genotyping_plates.mas
- t/unit_fixture/CXGN/Trial/TrialCreate.t
> Add number of samples and number of samples with data for plate info section on genotyping project page

- lib/SGN/Controller/solGS/Anova.pm
Description 
fixes  #4565
Checklist 
> removing not used uniqint module.

- bin/delete_stocks.pl
In rare cases, stocks of different types may have overlapping name spaces, so the stock type needs to be specified for deletion.
Description 
Checklist 
> add stock type to delete script

- lib/CXGN/Project.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/create_tissue_samples_dialogs.mas
- t/unit_fixture/CXGN/Trial/AddPlantsandTissueSamplesToTrial.t
> Checkbox to use tissue numbers 

- bin/load_blast.pl
Description 
Requires a fix in cxgn-corelibs as well, as implemented in the branch topic/fix_blast_dbix_schema
Checklist 
> add a script to populate the blast tables

- lib/CXGN/Location.pm
- mason/breeders_toolbox/location_map.mas
- mason/breeders_toolbox/upload_locations_dialogs.mas
Description 
This adds a new Location type of "Town" since we have a lot of trials where the only location information we are given is the name of the closest town.
Checklist 
> Location: add Town type

- lib/CXGN/Stock/SearchVector.pm
- mason/search/vectors.mas
Description 
Adds the  delete columns option on search vectors datatable
closes #4598 
Checklist 
>  delete columns  on search vectors 

- lib/CXGN/Genotype/GenotypingProject.pm
- lib/CXGN/Stock/TissueSample/Search.pm
- lib/SGN/Controller/AJAX/Search/GenotypingDataProject.pm
- lib/SGN/Controller/BreedersToolbox/Trial.pm
- mason/breeders_toolbox/genotyping_data_project/genotyping_plates.mas
- mason/breeders_toolbox/genotyping_trials/detail.mas
- t/unit_fixture/CXGN/Trial/TrialCreate.t
> Moved number of samples with genotype info from genotyping project page to genotyping plate details page

- mason/breeders_toolbox/trial/trial_details.mas
- t/unit_fixture/CXGN/Trial.t
> fixed small error

- lib/CXGN/Fieldbook/TraitInfo.pm
Description 
Update the trait file generation to handle traits that were created via BrAPI
Checklist 
> Updating Field Book trait file generation when traits are created via BrAPI

- lib/CXGN/BrAPI/v2/ObservationUnits.pm
- lib/SGN/Controller/AJAX/BrAPI.pm
- sgn.conf
Description 
Added a temporary feature flag to control whether "No ManagementFactor" is returned in the brapi observation unit treatments or not
Checklist 
> Added a temporary feature flag to control observation unit treatment factor default value

- lib/CXGN/Pedigree/AddPedigrees.pm
Description
This just wraps some code in else blocks to stop processing if an error is encountered
Checklist 
> Add Pedigree: stop processing if error encountered

- .github/workflows/test.yml
Description 
updated docker version for github actions to 0.82
Checklist 
> updated docker version for github actions to 0.82

- R/solGS/gs.r
Description 
-- update deprecated arrange_r dplyr function
Checklist 
> update deprecated arrange_ function

- bin/load_blast.pl
Description 
small tweak to make POD look more readable.
Checklist 
> fix load_blast.pl POD

- db/00174/AddListCreateDate.pm
Description 
-- add if not exists constraint to add column create_date
Checklist 
> add create_date...if not exists

- .github/workflows/test.yml
> change docker version used for testing to "latest"

- lib/SGN/Controller/BreedersToolbox/Download.pm
> fix stock attribute download so that it also downloads synonyms

- lib/CXGN/Stock/SearchVector.pm
Description 
Searchs by vector name where not working.
closes #4713
Checklist 
> fix keyword search on vector search

- lib/CXGN/Trial/ParseUpload/Plugin/GenotypeTrialXLS.pm
- lib/CXGN/Trial/ParseUpload/Plugin/SamplingTrialXLS.pm
- mason/breeders_toolbox/genotyping_trials/create_genotyping_trial_dialogs.mas
- mason/breeders_toolbox/sampling_trials/create_sampling_trials_dialogs.mas
- mason/breeders_toolbox/trial/add_tissue_sample_per_plant.mas
- mason/help/workflow_guided/tissue_sample_help.mas
> Added 'tuber' tissue type for genotyping plate

- js/source/legacy/d3/graphers/stackedObservationPhenotypeHistogram.js
> fixing histogram when management factors are present

- db/00182/UpdatePhenotypeJsonbTableMaterializedViewForTreatments.pm
Description 
update `treatments` column in `materialized_phentoype_jsonb_table` to only include treatments actually applied to the observation unit
Changes made to mat view query:
```diff
90a94
+     my $treatment_experiment_type_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'treatment_experiment', 'experiment_type')->cvterm_id();
107,112c111,114
-     jsonb_object_agg(coalesce(
-     case
-         when (treatment.name) IS NULL then null
-         else (treatment.name)
-     end,
-     'No ManagementFactor'), treatment.description) AS treatments,
---
+     COALESCE(
+         jsonb_object_agg(treatment.name, treatment.description) FILTER (WHERE treatment.name IS NOT NULL), 
+         '{"No ManagementFactor": null}'::jsonb
+     ) …
```
> Pheno JSONB Mat View: fix treatments column

- js/source/entries/fieldmap.js
- lib/CXGN/Trial.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
This adds the "HarvestMaster" download type to the field layout download on the trial detail page.  This format includes range and row columns that are required for the Harvest Master software.  It also adds rep, block, and control columns to the existing download format.
Checklist 
> Field Layout Download: Harvest Master download type

- README.md
> add a line about the new easy to use breedbase_site repo

- R/dataset/rosner_test.R
- js/source/entries/dataset_scatterplot.js
- lib/SGN/Controller/AJAX/Dataset.pm
- lib/SGN/Controller/Dataset.pm
- mason/dataset/index.mas
Description 
Implemented IQR metrics for outliers as well changed granularity of slider 
https://github.com/solgenomics/sgn/issues/4710
Implemented Rosner test through R  rosnerTest{EnvStats}
- controller 
- R file with function
- UI changes 
https://github.com/solgenomics/sgn/issues/4694
R_libs changes are needed for Rosner test functionality. Correct commit is done. 
Checklist 
> Outliers update - Rosner test and IQR metric

- R/solGS/hclustering.r
> make plot file search more specific

- lib/CXGN/Stock/SearchVector.pm
- lib/SGN/Controller/AJAX/Search/Vector.pm
- mason/search/vectors.mas
> fix  advance vector search

- js/source/legacy/CXGN/BreedersToolbox/AddTrial.js
- mason/breeders_toolbox/trial/trial_create_dialogs.mas
> Make planting date optional for trial

- bin/rename_trials.pl
> Topic/rename trials 

- lib/SGN/Controller/AJAX/HTMLSelect.pm
> sort trial types alphabetically.

- db/00183/AddStockPropValueJsonb.pm
> add a dbpatch for a stockprop.value_jsonb field.

- mason/tools/fieldmap.mas
Description 
This fixes a couple of small problems with the geo field layout:
- Add back in the D3 (version 4) import
- Add the user's auth token to the BrAPI requests for updating the plots
Fixes #4778 
Checklist 
> Geo Field Layout Fixes

- lib/CXGN/BrAPI/v2/Scales.pm
also convert "categorical" to BrAPI lingo.
Description 
Checklist 
> add categorical to the list of available trait formats 

- bin/merge_stocks.pl
- lib/CXGN/Stock.pm
- t/data/scripts/merge_stocks_test_file.txt
- t/unit_fixture/CXGN/Stock/MergeStock.t
- t/unit_fixture/scripts/merge_stocks.t
Description 
Also, add simple test for merge_stocks.pl script, tweaks.
Checklist 
> eliminate spurious errors after merge_stocks.pl script run

- js/source/modules/wizard-downloads.js
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/breeder_search_page.mas
fix error when no protocol and multiple projects
Checklist 
> fix error when no protocol and multiple projects

- js/source/legacy/CXGN/BreedersToolbox/Crosses.js
- lib/Bio/GeneticRelationships/Pedigree.pm
- lib/CXGN/Pedigree/AddCrosses.pm
- lib/CXGN/Pedigree/AddPedigrees.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesExcelFormat.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesSimpleExcel.pm
- lib/CXGN/Pedigree/ParseUpload/Plugin/CrossesSimplifiedParentInfoExcel.pm
- lib/SGN/Controller/Cross.pm
- mason/breeders_toolbox/cross/add_cross_dialogs.mas
- mason/breeders_toolbox/cross/upload_crosses_dialogs.mas
- mason/pedigree/stock_pedigree.mas
> add dihaploid_induction as a new cross_type

- lib/CXGN/BrAPI/v2/Studies.pm
> fixes studies sort order

- mason/stock/index.mas
- mason/stock/related_stock.mas
Description 
To show all the lines that have been created using a given vector
Checklist 
> add related stocks to vector detail page

- lib/SGN/Controller/AJAX/Seedlot.pm
> Fixed upload seedlot description

- js/source/legacy/CXGN/BreedersToolbox/FieldBook.js
Description 
This just removes an unnecessary JS alert that was confusing users
Checklist 
> Fieldbook trait file generator: remove debugging alert

- mason/breeders_toolbox/trial/trial_raw_data.mas
Description 
Increase the pageSize of the BrAPI request used to get the traits listed in the "Phenotype Raw Data" section on the Trial Detail page.
Fixes #4908 
Checklist 
> Phenotype Raw Data: increase pageSize of BrAPI GET request

- lib/SGN/Controller/AJAX/PhenotypesUpload.pm
- mason/breeders_toolbox/manage_trial_phenotyping.mas
> Fixed error on direct phenotyping page and disable the ability to change stored trait value

- bin/load_marker_data.pl
- lib/SGN/Controller/AJAX/Search/Annotation.pm
- lib/SGN/Controller/Search/Annotation.pm
- mason/search/annotation/stub.mas
Description 
This PR creates an annotation page based on a gene annotation file.
Checklist 
> create annotation page from file

- R/mixed_models_sommer.R
- js/source/entries/mixedmodels.js
- lib/CXGN/MixedModels.pm
- lib/SGN/Controller/AJAX/MixedModels.pm
> mixed model results table missing accessions

- js/source/legacy/brapi/BrAPIFieldmap.js
Description 
This fixes a bug from my earlier PR #4914. There was a problem loading plots in the Geo Field Map when editing the layout.
Checklist 
> Geo Field Map: fix loading plots when editing layout

- lib/SGN/Controller/AJAX/GCPC.pm
> do not retrieve sex info if term not available.

- .github/workflows/static.yml
- .github/workflows/test.yml
- .github/workflows/test_static.yml
- cgi-bin/tools/tree_browser/index.pl
- lib/SGN/Controller/AJAX/DroneImagery/DroneImageryUpload.pm
- lib/SGN/Controller/BreedersToolbox/GraphicalFiltering.pm
- lib/SGN/Controller/BreedersToolbox/TrialComparison.pm
fix startup warnings
bad assignment with "or" operator
add version to package
#1027 
Checklist 
> fix startup warnings

- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
- lib/CXGN/Pedigree/AddPopulations.pm
- lib/CXGN/Population.pm
- lib/SGN/Controller/AJAX/BreedersToolbox/Population.pm
- lib/SGN/Controller/AJAX/Cross.pm
- lib/SGN/Controller/Stock.pm
- mason/breeders_toolbox/manage_populations_dialogs.mas
- mason/page/detail_page_2_col_section.mas
- mason/stock/index.mas
- mason/stock/population_delete.mas
- mason/stock/population_members.mas
- t/unit_mech/AJAX/BreedersToolbox/Population.t
> Improve population related functions and population details page

- lib/CXGN/BrAPI/v2/Scales.pm
Description 
remove spaces from scale datatypes in /variables brapi call
Closes #4954
> remove spaces from scale datatypes

- lib/CXGN/Trial.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
Description 
This adds an accession entry number column to the plot layout download on the trial detail page.
Checklist 
> Plot Layout Download: add entry numbers to download file

- mason/breeders_toolbox/upload_transactions_dialogs.mas
> Fixed seedlot spreadsheet info

- lib/CXGN/Genotype/MarkersSearch.pm
Description 
make marker search case insensitive, remove spaces.
closes #4959
Checklist 
> make marker search case insensitive, remove spaces

- lib/SGN/Controller/AJAX/TrialMetadata.pm
> Fix connection profile

- mason/solgs/genotyping_protocol/index.mas
Description 
-- display wait message while querying for genotyping protocols
Checklist 
> display wait message while querying for geno protocols

- lib/SGN/Controller/AJAX/Accession_usage.pm
> Fix phenotype performance table

- mason/breeders_toolbox/trial/edit_trial_details_dialog.mas
- mason/breeders_toolbox/trial/trial_details.mas
- sgn.conf
- t/selenium2/03_dataset/dataset.t
- t/selenium2/breeders/upload_multi_trial_file.t
- t/unit_fixture/CXGN/Trial.t
Description 
closes #4973 
Checklist 
> made transplanting date to appear on edit trial detail page

- lib/SGN/Controller/AJAX/LabelDesigner.pm
> Fix generating cross barcodes using list

- lib/CXGN/Genotype/Search.pm
- lib/SGN/Controller/AJAX/Search/Genotype.pm
> Improve genotyping metadata display and download when tissue samples are linked to plants or plots.

- lib/SGN/Controller/AJAX/IdentifierGeneration.pm
- lib/SGN/Controller/AJAX/LabelDesigner.pm
- mason/breeders_toolbox/cross/upload_update_crosses.mas
- mason/site/toolbar/manage.mas
- t/unit_mech/AJAX/IdentifierGeneration.t
> Fix input box for identifier generation

- js/source/legacy/CXGN/Dataset.js
- js/source/legacy/dataset.js
- lib/CXGN/Dataset.pm
- lib/SGN/Controller/AJAX/Dataset.pm
- mason/dataset/index.mas
fixes the dataset detail page so that public/private/delete buttons work
add option to edit description field
#5010 
#4935
Checklist 
> dataset detail fixes

- js/source/legacy/tools/LabelDesigner.js
> Increase timeout for label designer tool.

- sgn.conf
Description 
fixes #5047 
Checklist 
> fix fieldbook authentication string in config

- mason/phenome/display_owners.mas
Description 
locus pages were not displaying locus owners correctly 
Checklist 
> display owners div

- bin/update_stock_props.pl
Description 
fixes #5049 
Checklist 
> add a script to update specific stock attribute values.

- js/source/legacy/CXGN/BreedersToolbox/Accessions.js
> Fixing upload accessions using file

- bin/delete_trials.pl
Improve trial deletion script by adding options to read trial names (-F) and trial ids (-f) from a file; tweak POD.
Description 
Checklist 
> tweak trial deletion script

- js/source/entries/wizard.js
Description 
Make list items in the search wizard clickable to open the item's detail page
Checklist 
> Search Wizard: Link list items to detail pages

- bin/upload_multiple_trial_design.pl
- js/source/legacy/CXGN/BreedersToolbox/UploadTrial.js
- lib/SGN/Controller/AJAX/Trial.pm
- mason/breeders_toolbox/trial/trial_upload_dialogs.mas
Description 
this will fix: #5067
Checklist 
> fix multi trial upload error reporting

- lib/SGN/Controller/QuickSearch.pm
- mason/search/quick_search.mas
> add vectors to quicksearch

- ontology/cxgn_time.obo
Description 
closes #5095 
Checklist 
> add season time events

- js/source/legacy/CXGN/List.js
Description 
This adds a link next to each list item in the list editor to that item's detail page:
Fixes #5097 
Checklist 
> List Editor: add link to item detail page

- bin/load_people.pl
Description 
do not create account if email is already in database.
Checklist 
> minor tweak for load_people.pl 

- lib/SGN/Controller/AJAX/Audit.pm
code was causing error/crash in audit code when viewing stock details
added error checking in JSON code
Checklist 
> add error checking to audit code

- js/source/legacy/CXGN/BreedersToolbox/UploadPedigrees.js
Description 
fixes #5167 
Checklist 
> add POST to the ajax request so that larger pedigree upload requests work

- mason/chado/cvterm.mas
> fix typo in Synonym

- lib/SGN/Controller/AJAX/BrAPI.pm
…_require_login is set to 1.
Description 
Checklist 
> fix brapi logins

- bin/rename_locations.pl
Description 
bin/rename_locations.pl 
Checklist 
> add a script to rename locations in bulk

- js/source/legacy/solGS/ajaxAutocomplete.js
- js/source/legacy/solGS/cluster.js
- js/source/legacy/solGS/combineTrials.js
- js/source/legacy/solGS/genotypingProtocol.js
- js/source/legacy/solGS/listTypeSelectionPopulation.js
- js/source/legacy/solGS/searchTrials.js
- js/source/legacy/solGS/selectionPopulations.js
- js/source/legacy/solGS/solGS.js
- mason/solgs/genotyping_protocol/index.mas
- mason/solgs/population/training_population.mas
- mason/solgs/search/selection_populations.mas
- mason/solgs/search/solgs.mas
- mason/solgs/search/trial_search_form.mas
- mason/solgs/search/trials_search_result.mas
- mason/solgs/tools/correlation/analysis.mas
- mason/solgs/tools/correlation/genetic_correlation.mas
- t/selenium2/solgs/anova.t
- t/selenium2/solgs/cluster.t
- t/selenium2/solgs/combine_trials.t
- t/selenium2/solgs/correlation.t
- t/selenium2/solgs/genetic_gain.t
- t/selenium2/solgs/hcluster.t
- t/selenium2/solgs/heritability.t
- t/selenium2/solgs/kcluster.t
- t/selenium2/solgs/kinship.t
- t/selenium2/solgs/list_type_training_pop.t
- t/selenium2/solgs/pca.t
- t/selenium2/solgs/selection_index.t
- t/selenium2/solgs/solgs.t
Description 
-- rename html elements attribute names for ease or understanding and maintainance
-- Show a message to a user to select a genotyping protocol  or upload genotype data before trying to use solGS tools that need genotype data,  in websites with no default genotyping protocol settings or no genotype data.
Checklist 
> display genotype data missing warning

- t/test_fixture.pl
- t/unit_mech/AJAX/_BrAPIv2_phenotyping.t
> test_fixture.pl: cleanup logfile correctly in all threads

- lib/SGN/Controller/AJAX/Stock.pm
- mason/stock/trials.mas
Description 
Requested change from Isaak to change the name of the datatable in the experiment usage section of accession details
Checklist 
> "analyses" --> "stored analyses"

- lib/SGN/Controller/AJAX/DroneImagery/DroneImageryUpload.pm
Description 
This pull request fixes an error when creating a new drone vehicle to upload images.
Fixes ticket #5239 
Checklist 
> fix adding new drone vehicle

- bin/drop_test_databases.pl
> tweak pod for drop_test_databases.pl script.

- lib/CXGN/BrAPI/v2/Scales.pm
Description 
Add support for boolean and counter trait formats
closes #5255
Checklist 
> Add counter and boolean trait formats

- js/source/legacy/CXGN/Stock.js
- lib/CXGN/Stock.pm
- lib/CXGN/Transformation/Transformation.pm
- lib/SGN/Controller/AJAX/Stock.pm
- lib/SGN/Controller/AJAX/Transformation.pm
- lib/SGN/Controller/Stock.pm
- mason/page/detail_page_2_col_section.mas
- mason/stock/delete.mas
- mason/stock/index.mas
- mason/transformation/obsolete_stock_dialog.mas
- mason/transformation/obsoleted_transformants_section.mas
- mason/transformation/transformants_section.mas
- mason/transformation/transformation.mas
- mason/transformation/transformation_project_details.mas
- t/unit_fixture/CXGN/VerifyDeletion/StockObsoletion.t
> Allow user to add obsolete note

- lib/CXGN/Phenotypes/Search/Native.pm
> Clearly define relationship between observation unit and germplasm

- lib/CXGN/Trial/Download/Plugin/ExcelBasic.pm
- lib/CXGN/Trial/Download/Plugin/ExcelBasicSimple.pm
Description 
Fixes: #5238 
Checklist 
> fixing notes on phenotyping spreadsheet

- sgn.conf
> fixing sgn.conf with phenotype outlier filter

- lib/CXGN/DbStats.pm
> fix some queries that need explicit table refs

- db/00190/UpdateMaterializedPhenoviewTissueSample.pm
- js/source/entries/wizard.js
- lib/SGN/Controller/AJAX/BreederSearch.pm
- t/unit_fixture/CXGN/BreederSearch.t
> Adding tissue sample to wizard

- lib/SGN/Controller/AJAX/Audit.pm
Description 
Adding encode/decode to avoid problems when reading latin characters. 
fixes #5313 
Checklist 
> Fixing decode latin characters

- mason/brapiclient/phenotypes_search.mas
- mason/brapiclient/phenotyping_handhelds.mas
- mason/brapiclient/studies_table.mas
- mason/breeders_toolbox/trial/download_layout_interface_dialog.mas
- mason/stock/download_stock_phenotypes_dialog.mas
Description 
fixes #5347
Checklist 
> change xls to xlsx in UI to make downloads work

- ontology/cxgn_time.obo
Description 
need to update intentorybase-test + add 'events' to local conf file 
Checklist 
> Timepoint events in the cxgn time ontology. Requested by InventoryBase

- R/solGS/kclustering.r
- lib/solGS/JobSubmission.pm
clustering fails in prcomp for genotype data if there is no variance
#5338
Checklist 
> Fix analysis cluster

- lib/SGN/Controller/BreedersToolbox/Trial.pm
> fixes download trial layout in xlsx

- lib/CXGN/Stock/Search.pm
> change stock dates to iso format

- js/source/entries/qualitycontrol.js
- lib/CXGN/Phenotypes/Search/MaterializedViewTable.pm
- lib/CXGN/Phenotypes/Search/Native.pm
- lib/SGN/Controller/AJAX/QualityControl.pm
- mason/breeders_toolbox/breeder_search_page.mas
- mason/breeders_toolbox/trial/download_phenotypes_dialog.mas
- mason/breeders_toolbox/trial/download_trials_phenotypes_dialog.mas
- mason/stock/download_stock_phenotypes_dialog.mas
> fixing outliers phenotype download 

- lib/CXGN/BrAPI/v1/Studies.pm
- lib/CXGN/BrAPI/v2/Studies.pm
BrAPI year field should be an integer not string
#5045 
Checklist 
- [x ] Bug fix
> BrAPI fixes to year field

- lib/SGN/Controller/BreedersToolbox.pm
- mason/breeders_toolbox/manage_transcriptomics.mas
- mason/page/detail_page_2_col_section.mas
- mason/tools/transcriptomics/manage_transcriptomics_main.mas
Description 
Creates a page for managing the transcriptomics high-dimensional phenotype data, similar to the existing NIRS page.
Checklist 
> Create separate page for managing transcriptomics

- mason/breeders_toolbox/download.mas
Description 
Fixed #5363 
Checklist 
> fix the name for the genotype protocol select

- bin/Reports/phenotype_properties_check.pl
- lib/CXGN/Contact.pm
- lib/SGN/Controller/AJAX/Report.pm
- lib/SGN/Controller/Report.pm
- mason/site/toolbar/manage.mas
- mason/tools/report.mas
- sgn.conf
Description 
With this feature is possible to develop personalized reports from scripts. For example, check naming convention for accessions, trials, plots, seedlots. Create report for data quality, plots with trait values bellow minimum or above maximum...
All scripts available might be listed in sgn_local.conf as 'report_engine' as following:
Scripts must be mounted on bin/Reports using docker-compose.yml for each breedbase instance.
I am adding to sgn a general script to check plot values outside the correct range.
report_engine phenotype_properties_check; seedlot_name_check; stock_name_check
All available scripts will show up as an option for the report:
The result from this report is stored in a zip file and will be sent by email. …
> Personalized Reports

- js/source/entries/fieldmap.js
- lib/CXGN/BrAPI/v2/Observations.pm
- mason/breeders_toolbox/trial/phenotype_heatmap.mas
Description 
This fixes the possibility of missing data in the phenotype heatmap.  It updates the BrAPI observations requests to get multiple pages, if needed, and to only request the data for the selected trait.
Fixes #5376 
Checklist 
> Phenotype Heatmap: fix observations query

- js/source/legacy/CXGN/Trial.js
Description 
Fix planting/harvest date formats after editing them in the Edit Trial Details dialog from the trial detail page.
Fixes #5377 
Checklist 
> Edit Trial Details: fix date formatting

- db/00193/UpdateListTypeLocusCvterms.pm
- lib/CXGN/List/Validate/Plugin/Locus.pm
Description 
#5198 
Checklist 
- [x ] New feature
> add locus name to list type and validation

- mason/breeders_toolbox/cross/seedlots_from_crossingtrial.mas
- mason/breeders_toolbox/cross/upload_crossingtrial_seedlots_dialog.mas
Description 
Fixes the locations when creating seedlots from a crossing experiment
Fixes #5448
Checklist 
> Seedlots from Crosses: fix location dropdown

- mason/stock/index.mas
> if url value exists we can assume it is safe to build the dbxref link

- mason/stock/accession_usage.mas
Description 
Closes #5483.
Checklist 
> fix typo in title (performance vs performace).

- mason/tools/image_analysis.mas
Description 
Fixes #5485 
Checklist 
> Change image search ajax request to post in image analysis

- lib/CXGN/Fieldbook/TraitProps.pm
> fix variable declaration in loop to make load_trait_props.pl script work

- lib/CXGN/Stock.pm
- lib/SGN/Controller/AJAX/FieldBook.pm
- mason/breeders_toolbox/trial/download_layout_interface_dialog.mas
improve error checking in uploading field book files
#5476 
Stock.pm code was crashing because of arguements in function, probably bad pedigree entries
Checklist 
- [ x] Bug fix
> fix error with uploading field book file, better error checking

- lib/SGN/Controller/AJAX/User.pm
Description 
There are three email address fields in the sp_person table, used for different functions. Only one is populated with this script which can lead to issues later on.
Closes #5527 
Checklist 
> tweak email address storage for quick account creation script.

- bin/load_composed_cvprops.pl
- db/00193/AddBiochemOnto.pm
> new cvprop for biochem ChEBI traits, and add the cxgn_metadata cvterm to cvprops loading script

- lib/CXGN/PhenotypingTrial.pm
- lib/CXGN/Trial/TrialDesignStore/AbstractTrial.pm
- lib/SGN/Controller/AJAX/TrialMetadata.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/trial/design_section.mas
- mason/breeders_toolbox/trial/summary_stock_entries.mas
- t/unit_fixture/CXGN/Trial/AddPlantsandTissueSamplesToTrial.t
> Add plant and tissue sample for cross and family name trial stock type

- mason/site/login_dialog.mas
Description 
Fixes #5525 
Checklist 
> Add show password check box to login page

- R/solGS/rrblup_gblup_gs.r
- js/source/legacy/solGS/analysisSelect.js
- js/source/legacy/solGS/correlation.js
- js/source/legacy/solGS/trialsSelect.js
- mason/dataset/index.mas
- mason/page/detail_page_2_col_section.mas
- mason/solgs/population/models/model/detail.mas
- mason/solgs/population/selection_prediction_detail.mas
- mason/solgs/population/training_population.mas
- mason/solgs/tools/analysis_select.mas
- mason/solgs/tools/correlation/analysis.mas
- mason/solgs/tools/correlation/plot.mas
- mason/solgs/tools/dataset_trials_analysis.mas
- mason/solgs/tools/trials_select.mas
- t/selenium2/solgs/correlation.t
Description 
-- adds correlation analysis to dataset detail page. 
-- Users can do correlation analysis at the dataset level and trials in the dataset.
-- designed to be flexible  to add more descriptive analysis 
closes #5511, #5508
Checklist 
> Add correlation analysis to dataset page

- lib/CXGN/Image/Search.pm
- lib/SGN/Controller/AJAX/Search/Image.pm
- mason/search/images.mas
Description 
Allows searching by accession to find images of related stocks
Fixes #5320 
Checklist 
> Add related accessions to image search

- bin/Reports/phenotype_properties_check.pl
- lib/SGN/Controller/AJAX/Report.pm
- mason/tools/report.mas
It is in substitution on the PR #5585 
1- Supports running multiple report formats in a single request.
2 - Executes report generation asynchronously, allowing the user interface to remain responsive while reports are processed in the background.
3- Implements automatic error notification: if the report script fails, an email is sent to notify users of the error details.
4- Fixes phenotype QC report
> Update Report Engine

- mason/tools/label_designer/design_label.mas
- mason/tools/label_designer/save_and_download.mas
- mason/tools/label_designer/select_datasource.mas
Description 
Mostly minor text tweaks to align with revisions to the Breedbase manual; also updating link to the manual that is displayed in the label designer workflow.
Checklist 
> Minor text tweaks to label designer interface

- js/source/legacy/brapi/BrAPIFieldmap.js
Description 
Fixes #5650 
Checklist 
> Fix polygon created when there are more than three points on geo field map

- lib/CXGN/Transformation/Transformation.pm
- lib/SGN/Controller/AJAX/Stock.pm
- lib/SGN/Controller/AJAX/Transformation.pm
- lib/SGN/Controller/Stock.pm
- lib/SGN/Controller/Transformation.pm
- mason/page/detail_page_2_col_section.mas
- mason/stock/delete.mas
- mason/stock/index.mas
- mason/transformation/obsolete_accessions_dialog.mas
- mason/transformation/transformants_section.mas
- mason/transformation/transformation.mas
> Obsolete multiple transformants at once

- lib/CXGN/Cross.pm
- lib/SGN/Controller/BreedersToolbox/Download.pm
- mason/breeders_toolbox/download.mas
- t/unit_fixture/CXGN/Uploading/UploadAndAddCrossesCrossingtrial.t
> Download cross and family name info using progeny list

- bin/fix_tissue_samples_plot_associations.pl
> add a script to fix tissue sample / plot associations.

- lib/SGN/Controller/AJAX/SpatialModel.pm
Description 
Spatial corrections broke because a few key lines of code were deleted or replaced with an older version. This fixes those changes.
Checklist 
> fixing completely mysterious rollback of previous commit

- db/00199/FixTissueSampleSearch.pm
Description 
This ticket fixes the tissue sample counting when associated to genotyping protocols and genotyping projects
Fixes #5300 #5520 
Checklist 
> fixing tissue sample counting
